apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-backup-credentials
  namespace: databases
spec:
  dataFrom:
    - extract:
        key: lungmen.akn/cloudnative-pg/backup/s3-credentials
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
