# Copyright (C) 2024 vscode (you@you.you)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------

explanation: |md
  # nex·rpi Architecture

  This document describes the architecture \
  of the nex·rpi platform in a visual way \
  with all the components and how they \
  interact with each other.
  \
  _A service that is not described here is \
  [kubevault](https://github.com/chezmoi-sh/kubevault), which is a tool for managing \
  secrets relying on Kubernetes API without any \
  "component"._\
| {
  near: top-left
}

classes: {
  # Object classes
  application: {
    shape: rectangle
    style: {
      fill-pattern: dots
      multiple: true
      shadow: false
    }
  }
  application-system: {
    shape: rectangle
    style: {
      fill-pattern: dots
      multiple: true
      stroke-dash: 3
    }
  }

  undeployed: {
    style: {
      opacity: 0.3
    }
  }

  namespace: {
    shape: page
    style: {
      fill-pattern: lines
      stroke-dash: 5
      text-transform: lowercase
    }
  }
  network: {
    shape: cloud
    style: {
      fill-pattern: dots
      text-transform: uppercase
      font-size: 24
      bold: true
    }
  }

  # Connections classes
  connect-from-network: {
    style.stroke-width: 8
  }
  connect-to-internet: {
    style: {
      stroke-dash: 3
    }
  }
  connect-to-network: {
    style.stroke-width: 8
  }
  connect-vpn-trunk: {
    style: {
      animated: true
      bold: true
      font-size: 32
      stroke-width: 8
    }
  }
  connect-vpn: {
    style.animated: true
  }
}

internet: {class: network}
localnet: {class: network}

nex·rpi: {
  network: {class: namespace}
  security: {class: namespace}
  storage: {class: namespace}

  style.fill-pattern: none
}

# - Tailscale
nex·rpi.network.Tailscale: {
  class: [application; undeployed]
  icon: assets/tailscale.svg
  link: https://tailscale.com/
  tooltip: TailScale is a mesh VPN that makes it easy to connect your devices, wherever they are.
}
nex·rpi.network.Tailscale <-> internet: VPN {class: [connect-vpn-trunk; undeployed]}
nex·rpi.network.Tailscale -> localnet: VPN Subnet proxy {class: [connect-vpn-trunk; undeployed]}

# - AdGuard Home
nex·rpi.network.AdGuard Home: {
  class: [application; undeployed]
  icon: assets/adguard-home.svg
  link: https://adguard.com/en/adguard-home/overview.html
  tooltip: AdGuard Home is a network-wide software for blocking ads & tracking.
}
nex·rpi.network.AdGuard Home -> internet: DNS / DoH {class: [connect-to-internet; undeployed]}
nex·rpi.network.AdGuard Home <- localnet: {
  class: [connect-to-network; undeployed]
  source-arrowhead: |md
    DNS (8053)
    DoT & DoQ (8853)
  |
}
nex·rpi.network.AdGuard Home <- nex·rpi.Traefik: {
  class: undeployed
  source-arrowhead: DoH & HTTP (8080)
}

# - yaLDAP
nex·rpi.security.yaLDAP: {
  class: [application; undeployed]
  icon: assets/yaldap.png
  link: https://yaldap.com/
  tooltip: yaLDAP is a modern LDAP server.
}
nex·rpi.security.yaLDAP <- nex·rpi.security.Authelia: {
  class: undeployed
  source-arrowhead: LDAP (8389)
}
nex·rpi.security.yaLDAP <- nex·rpi.Traefik: {
  class: undeployed
  source-arrowhead: LDAP (8389)
}

# - Authelia
nex·rpi.security.Authelia: {
  class: [application; undeployed]
  icon: assets/authelia.svg
  link: https://www.authelia.com/
  tooltip: Authelia is an open-source authentication and authorization server.
}
nex·rpi.security.Authelia <- nex·rpi.Traefik: {
  class: undeployed
  source-arrowhead: HTTP (9091)
}

# - SmallStep CA
nex·rpi.security.SmallStep CA: {
  class: [application; undeployed]
  icon: assets/smallstep.png
  link: https://smallstep.com/
  tooltip: SmallStep CA is a zero-trust certificate authority.
}
nex·rpi.security.SmallStep CA <- nex·rpi.Traefik: {
  class: undeployed
  source-arrowhead: HTTP (9000)
}
nex·rpi.security.SmallStep CA <- nex·rpi.Cert-Manager: {
  class: undeployed
  source-arrowhead: HTTP (9000)
}

# - MinIO
nex·rpi.storage.MinIO: {
  class: [application; undeployed]
  icon: assets/minio.svg
  link: https://min.io/
  tooltip: MinIO is a high-performance, distributed object storage system.
}
nex·rpi.storage.MinIO -> internet: HTTPS (443) {class: [connect-to-internet; undeployed]}
nex·rpi.storage.MinIO <- nex·rpi.Traefik: {
  class: undeployed
  source-arrowhead: HTTP (9000)
}

# - Zot Registry
nex·rpi.storage.zot registry: {
  class: [application; undeployed]
  icon: assets/zot-registry.svg
  link: https://zotregistry.dev/
  tooltip: Zot Registry is a self-hosted, privacy-focused, and easy-to-use image registry.
}
nex·rpi.storage.zot registry -> internet: HTTPS (443) {class: [connect-to-internet; undeployed]}
nex·rpi.storage.zot registry -> nex·rpi.storage.MinIO: {
  class: undeployed
  source-arrowhead: HTTP (9000)
}

# - Gatus
nex·rpi.Gatus: {
  class: [application; undeployed]
  icon: assets/gatus.svg
  link: https://gatus.io/
  tooltip: Gatus is a service health dashboard.
}
nex·rpi.Gatus -> internet: DNS (53)\nHTTPS (443) {class: [connect-to-internet; undeployed]}
nex·rpi.Gatus -> nex·rpi: {
  class: undeployed
  target-arrowhead: HTTPS (443)
}
nex·rpi.Gatus <- nex·rpi.Traefik: {
  class: undeployed
  source-arrowhead: HTTP (8080)
}

# - Homepage
nex·rpi.Homepage: {
  class: [application; undeployed]
  icon: assets/homepage.png
  link: https://gethomepage.dev/
  tooltip: Homepage is a simple, lightweight, and easy-to-use dashboard.
}
nex·rpi.Homepage -> internet: HTTPS (443) {class: [connect-to-internet; undeployed]}
nex·rpi.Homepage <-> nex·rpi.Traefik: {
  class: undeployed
  source-arrowhead: HTTP (3000)
  target-arrowhead: HTTPS (443)
}

# - Cert-Manager
nex·rpi.Cert-Manager: {
  class: [application-system]
  icon: assets/cert-manager.svg
  link: https://cert-manager.io/
  tooltip: Cert-Manager is a Kubernetes controller that automates the management and issuance of TLS certificates.
}
nex·rpi.Cert-Manager -> internet: HTTPS (443) {class: [connect-to-internet]}

# - External-DNS
nex·rpi.ExternalDNS: {
  class: [application-system]
  icon: assets/external-dns.png
  link: https://github.com/kubernetes-sigs/external-dns
  tooltip: ExternalDNS is a Kubernetes controller that configures DNS resources.
}
nex·rpi.ExternalDNS -> internet: HTTPS (443) {class: [connect-to-internet]}

# - External-Secret
nex·rpi.External-Secret: {
  class: [application-system]
  icon: assets/external-secret.svg
  link: https://external-secrets.io/
  tooltip: External-Secret is a Kubernetes controller that allows you to use external secret management systems.
}

# - Traefik
nex·rpi.Traefik: {
  class: [application-system]
  icon: assets/traefik.svg
  link: https://traefik.io/
  tooltip: Traefik is a modern HTTP reverse proxy and load balancer.
}
nex·rpi.Traefik <- localnet: {
  class: [connect-from-network]
  source-arrowhead: |md
    DNS (53)
    HTTP (80)
    HTTPS (443)
    DNS-over-TLS (853)
  |
}
