encryptionsalt: v1:agX4pNhPZ3Y=:v1:39UQDzNp+0o/rxa9:2tGZNL4YATbjQ2Qa1pVS/OTsrjnP2w==
config:
  kazimierz-akn-infra:ssh_authorized_keys: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPH7IEv+Q6s6WSPlWVva6UlCbkhePQdZYbN1TbI7rCDx
  kazimierz-akn-infra:unsecure: "false"
  kazimierz-akn-infra:cloudflare_zone_id:
    secure: v1:hIOJwej5EdxOtRaq:7KObpoMJHwzKM/5JHMvICYb0nDHWkSZZMrafroOmXGEGoFGcGaRV+J8EWxBTt+KZ
  oci:region: eu-paris-1
  kazimierz-akn-infra:cloudflare_account_id:
    secure: v1:74yL2K4KuCM0Kyez:itTM6JfYAJNCu/oOavcacVzRrLsGigd6T8/Ejdc/iltxPIi+NpW96dZ72T489Wc8
  pocket-id-api:baseUrl: https://auth.chezmoi.sh
  pocket-id-api:apiKeyHeader: X-API-KEY
