---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyseerr-database-jellyseerr
spec:
  dataFrom:
    - extract:
        key: lungmen.akn/jellyseerr/database/postgresql
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    name: jellyseerr-database-jellyseerr
    template:
      data:
        username: jellyseerr
        password: "{{ .password }}"
