---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: apps-atuin
spec:
  cluster:
    name: postgres-apps
  name: atuin
  owner: atuin
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin-database-credentials
spec:
  dataFrom:
    - extract:
        key: lungmen.akn/atuin/database/postgresql
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    template:
      data:
        username: atuin
        password: "{{ .password }}"
