---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: apps-jellyseerr
spec:
  cluster:
    name: postgres-apps
  name: jellyseerr
  owner: jellyseerr
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyseerr-database-credentials
spec:
  dataFrom:
    - extract:
        key: lungmen.akn/jellyseerr/database/postgresql
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    template:
      data:
        username: jellyseerr
        password: "{{ .password }}"
