---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: apps-linkding
spec:
  cluster:
    name: postgres-apps
  name: linkding
  owner: linkding
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-database-credentials
spec:
  dataFrom:
    - extract:
        key: lungmen.akn/linkding/database/postgresql
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    template:
      data:
        username: linkding
        password: "{{ .password }}"
