encryptionsalt: v1:WI/uHyMiTw8=:v1:r5rEpOiujBDfqrei:wyKJhoGkxyVFg0ZZtO6QSVEAebB6hg==
config:
  pbs:endpoint: https://pbs.pve.chezmoi.sh:8007
  pbs:insecure: "true"
  chezmoi-sh-infra:cloudflare_account_id:
    secure: v1:RC9hckvq5hYbOq/s:Tnnlg50zt9NkIwjEDtI8l+7aIy2CdHYTJUT8NrbzJHSBLbCCA/OYASBrhQfmqHdb
  chezmoi-sh-infra:cloudflare_zone_id:
    secure: v1:kjjfI91R96RPUXzm:d5dP4b7RBlUciLQyVXb5NU/olfnffpUtsFL9yxZf673N4afm9bAAJ+oI2fu1c/Bb
  chezmoi-sh-infra:garage_admin_token:
    secure: v1:N8/cY//l2q6mAKgL:GAYXb6A024F69taNfCAkWt4S29TIoJecvUzxdOKmRe3LVrr2tWVLQfxawxuKs4S3
  chezmoi-sh-infra:garage_rpc_secret:
    secure: v1:mfJ3FDbbHXdNLhym:Zo6fWjl9OUpBcEgpu4tw45gM+WkiYQYRWYFx7bmnSUKVW11aG/GnNP7oeTiBnMWDUa5J9/fX/iHaWB8C4vCkT+dEZmvR1i1y3ZD+l/myW4Q=
  chezmoi-sh-infra:garage_web_ui_password:
    secure: v1:C4bn+ZQfrgX2eQlU:sL2GXtnYGqbon7k88g+5pj2a3iJ0fSLQhSTssId2
  chezmoi-sh-infra:garage_web_ui_username:
    secure: v1:gmCF7n75MuShAoHX:IZIghnY+OeMs9sfLdzXGhXe29oMbp/1OBC0lWkG/OVE=
  chezmoi-sh-infra:notificationsSlackWebhookUrl:
    secure: v1:eGBY+TWz9wYKFPFA:ln4jXnyzm1E/aiM5gXDbJMpJ8+taN3FyqCUUhEMwvcU81EH6aGG0l1l3Xja20ucXCiSi7kNF+fVliDc4Gt9AKvOFLQ/byQrHGFnAMjT02i5nMPgApd5MVrZq6zVSHw8ukw==
  tailscale:tailnet:
    secure: v1:sLhY5DfYf/T18EyL:xvQ3lkIJoS04v9jaycJxyv4UlbruzkYAm3Dna3DVQs+C
  truenas:destroyProtection: "true"
  truenas:url: https://nas.chezmoi.sh
  proxmox:endpoint: https://pve-01.pve.chezmoi.sh:8006/api2/json
  proxmox:insecure: "true"
