// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Client extends pulumi.CustomResource {
    /**
     * Get an existing Client resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ClientState, opts?: pulumi.CustomResourceOptions): Client {
        return new Client(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pangolin:index/client:Client';

    /**
     * Returns true if the given object is an instance of Client.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Client {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Client.__pulumiType;
    }

    /**
     * Whether the client is archived. Archived clients are kept for audit but cannot connect. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    declare public readonly archived: pulumi.Output<boolean>;
    /**
     * Whether the client is blocked. Blocked clients are denied from connecting until unblocked. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    declare public readonly blocked: pulumi.Output<boolean>;
    /**
     * The numeric ID of the client.
     */
    declare public /*out*/ readonly clientId: pulumi.Output<number>;
    /**
     * The name of the client.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The human-readable ID of the client.
     */
    declare public /*out*/ readonly niceId: pulumi.Output<string>;
    /**
     * The OLM ID the client authenticates with (paired with <span pulumi-lang-nodejs="`secret`" pulumi-lang-dotnet="`Secret`" pulumi-lang-go="`secret`" pulumi-lang-python="`secret`" pulumi-lang-yaml="`secret`" pulumi-lang-java="`secret`" pulumi-lang-hcl="`secret`">`secret`</span>).
     */
    declare public /*out*/ readonly olmId: pulumi.Output<string>;
    /**
     * Whether the client is currently online.
     */
    declare public /*out*/ readonly online: pulumi.Output<boolean>;
    /**
     * The client secret. Only available at creation time; stored in state.
     */
    declare public /*out*/ readonly secret: pulumi.Output<string>;

    /**
     * Create a Client resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ClientArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ClientArgs | ClientState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ClientState | undefined;
            resourceInputs["archived"] = state?.archived;
            resourceInputs["blocked"] = state?.blocked;
            resourceInputs["clientId"] = state?.clientId;
            resourceInputs["name"] = state?.name;
            resourceInputs["niceId"] = state?.niceId;
            resourceInputs["olmId"] = state?.olmId;
            resourceInputs["online"] = state?.online;
            resourceInputs["secret"] = state?.secret;
        } else {
            const args = argsOrState as ClientArgs | undefined;
            resourceInputs["archived"] = args?.archived;
            resourceInputs["blocked"] = args?.blocked;
            resourceInputs["name"] = args?.name;
            resourceInputs["clientId"] = undefined /*out*/;
            resourceInputs["niceId"] = undefined /*out*/;
            resourceInputs["olmId"] = undefined /*out*/;
            resourceInputs["online"] = undefined /*out*/;
            resourceInputs["secret"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["secret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Client.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Client resources.
 */
export interface ClientState {
    /**
     * Whether the client is archived. Archived clients are kept for audit but cannot connect. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    archived?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the client is blocked. Blocked clients are denied from connecting until unblocked. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    blocked?: pulumi.Input<boolean | undefined>;
    /**
     * The numeric ID of the client.
     */
    clientId?: pulumi.Input<number | undefined>;
    /**
     * The name of the client.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The human-readable ID of the client.
     */
    niceId?: pulumi.Input<string | undefined>;
    /**
     * The OLM ID the client authenticates with (paired with <span pulumi-lang-nodejs="`secret`" pulumi-lang-dotnet="`Secret`" pulumi-lang-go="`secret`" pulumi-lang-python="`secret`" pulumi-lang-yaml="`secret`" pulumi-lang-java="`secret`" pulumi-lang-hcl="`secret`">`secret`</span>).
     */
    olmId?: pulumi.Input<string | undefined>;
    /**
     * Whether the client is currently online.
     */
    online?: pulumi.Input<boolean | undefined>;
    /**
     * The client secret. Only available at creation time; stored in state.
     */
    secret?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Client resource.
 */
export interface ClientArgs {
    /**
     * Whether the client is archived. Archived clients are kept for audit but cannot connect. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    archived?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the client is blocked. Blocked clients are denied from connecting until unblocked. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    blocked?: pulumi.Input<boolean | undefined>;
    /**
     * The name of the client.
     */
    name?: pulumi.Input<string | undefined>;
}
