// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getResourceRoles(args: GetResourceRolesArgs, opts?: pulumi.InvokeOptions): Promise<GetResourceRolesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("pangolin:index/getResourceRoles:getResourceRoles", {
        "resourceId": args.resourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getResourceRoles.
 */
export interface GetResourceRolesArgs {
    resourceId: number;
}

/**
 * A collection of values returned by getResourceRoles.
 */
export interface GetResourceRolesResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly resourceId: number;
    readonly roles: outputs.GetResourceRolesRole[];
}
export function getResourceRolesOutput(args: GetResourceRolesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetResourceRolesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("pangolin:index/getResourceRoles:getResourceRoles", {
        "resourceId": args.resourceId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getResourceRoles.
 */
export interface GetResourceRolesOutputArgs {
    resourceId: pulumi.Input<number>;
}
