// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRoles(opts?: pulumi.InvokeOptions): Promise<GetRolesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("pangolin:index/getRoles:getRoles", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getRoles.
 */
export interface GetRolesResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly roles: outputs.GetRolesRole[];
}
export function getRolesOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRolesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("pangolin:index/getRoles:getRoles", {
    }, opts, utilities.getPackage());
}
