// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Invitation extends pulumi.CustomResource {
    /**
     * Get an existing Invitation resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: InvitationState, opts?: pulumi.CustomResourceOptions): Invitation {
        return new Invitation(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pangolin:index/invitation:Invitation';

    /**
     * Returns true if the given object is an instance of Invitation.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Invitation {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Invitation.__pulumiType;
    }

    /**
     * Email address of the invitee.
     */
    declare public readonly email: pulumi.Output<string>;
    /**
     * Expiry timestamp as milliseconds since Unix epoch.
     */
    declare public /*out*/ readonly expiresAt: pulumi.Output<number>;
    /**
     * Full invitation URL including the single-use token. The recipient opens this to accept.
     */
    declare public /*out*/ readonly inviteLink: pulumi.Output<string>;
    /**
     * When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, regenerates an existing invitation for the same email instead of erroring on conflict. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    declare public readonly regenerate: pulumi.Output<boolean>;
    /**
     * Numeric ID of the role to assign once the invitation is accepted.
     */
    declare public readonly roleId: pulumi.Output<number>;
    /**
     * Numeric IDs of the roles attached to this invitation. Mirrors <span pulumi-lang-nodejs="`roleId`" pulumi-lang-dotnet="`RoleId`" pulumi-lang-go="`roleId`" pulumi-lang-python="`role_id`" pulumi-lang-yaml="`roleId`" pulumi-lang-java="`roleId`" pulumi-lang-hcl="`role_id`">`roleId`</span> today but the API supports multiple in principle.
     */
    declare public /*out*/ readonly roles: pulumi.Output<number[]>;
    /**
     * When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, Pangolin sends an invitation email to the address. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span> (use the returned <span pulumi-lang-nodejs="`inviteLink`" pulumi-lang-dotnet="`InviteLink`" pulumi-lang-go="`inviteLink`" pulumi-lang-python="`invite_link`" pulumi-lang-yaml="`inviteLink`" pulumi-lang-java="`inviteLink`" pulumi-lang-hcl="`invite_link`">`inviteLink`</span> directly).
     */
    declare public readonly sendEmail: pulumi.Output<boolean>;
    /**
     * How long the invite remains valid, in hours. Server default applies when omitted.
     */
    declare public readonly validHours: pulumi.Output<number | undefined>;

    /**
     * Create a Invitation resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: InvitationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: InvitationArgs | InvitationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as InvitationState | undefined;
            resourceInputs["email"] = state?.email;
            resourceInputs["expiresAt"] = state?.expiresAt;
            resourceInputs["inviteLink"] = state?.inviteLink;
            resourceInputs["regenerate"] = state?.regenerate;
            resourceInputs["roleId"] = state?.roleId;
            resourceInputs["roles"] = state?.roles;
            resourceInputs["sendEmail"] = state?.sendEmail;
            resourceInputs["validHours"] = state?.validHours;
        } else {
            const args = argsOrState as InvitationArgs | undefined;
            if (args?.email === undefined && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if (args?.roleId === undefined && !opts.urn) {
                throw new Error("Missing required property 'roleId'");
            }
            resourceInputs["email"] = args?.email;
            resourceInputs["regenerate"] = args?.regenerate;
            resourceInputs["roleId"] = args?.roleId;
            resourceInputs["sendEmail"] = args?.sendEmail;
            resourceInputs["validHours"] = args?.validHours;
            resourceInputs["expiresAt"] = undefined /*out*/;
            resourceInputs["inviteLink"] = undefined /*out*/;
            resourceInputs["roles"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["inviteLink"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Invitation.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Invitation resources.
 */
export interface InvitationState {
    /**
     * Email address of the invitee.
     */
    email?: pulumi.Input<string | undefined>;
    /**
     * Expiry timestamp as milliseconds since Unix epoch.
     */
    expiresAt?: pulumi.Input<number | undefined>;
    /**
     * Full invitation URL including the single-use token. The recipient opens this to accept.
     */
    inviteLink?: pulumi.Input<string | undefined>;
    /**
     * When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, regenerates an existing invitation for the same email instead of erroring on conflict. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    regenerate?: pulumi.Input<boolean | undefined>;
    /**
     * Numeric ID of the role to assign once the invitation is accepted.
     */
    roleId?: pulumi.Input<number | undefined>;
    /**
     * Numeric IDs of the roles attached to this invitation. Mirrors <span pulumi-lang-nodejs="`roleId`" pulumi-lang-dotnet="`RoleId`" pulumi-lang-go="`roleId`" pulumi-lang-python="`role_id`" pulumi-lang-yaml="`roleId`" pulumi-lang-java="`roleId`" pulumi-lang-hcl="`role_id`">`roleId`</span> today but the API supports multiple in principle.
     */
    roles?: pulumi.Input<pulumi.Input<number>[] | undefined>;
    /**
     * When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, Pangolin sends an invitation email to the address. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span> (use the returned <span pulumi-lang-nodejs="`inviteLink`" pulumi-lang-dotnet="`InviteLink`" pulumi-lang-go="`inviteLink`" pulumi-lang-python="`invite_link`" pulumi-lang-yaml="`inviteLink`" pulumi-lang-java="`inviteLink`" pulumi-lang-hcl="`invite_link`">`inviteLink`</span> directly).
     */
    sendEmail?: pulumi.Input<boolean | undefined>;
    /**
     * How long the invite remains valid, in hours. Server default applies when omitted.
     */
    validHours?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a Invitation resource.
 */
export interface InvitationArgs {
    /**
     * Email address of the invitee.
     */
    email: pulumi.Input<string>;
    /**
     * When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, regenerates an existing invitation for the same email instead of erroring on conflict. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    regenerate?: pulumi.Input<boolean | undefined>;
    /**
     * Numeric ID of the role to assign once the invitation is accepted.
     */
    roleId: pulumi.Input<number>;
    /**
     * When <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>, Pangolin sends an invitation email to the address. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span> (use the returned <span pulumi-lang-nodejs="`inviteLink`" pulumi-lang-dotnet="`InviteLink`" pulumi-lang-go="`inviteLink`" pulumi-lang-python="`invite_link`" pulumi-lang-yaml="`inviteLink`" pulumi-lang-java="`inviteLink`" pulumi-lang-hcl="`invite_link`">`inviteLink`</span> directly).
     */
    sendEmail?: pulumi.Input<boolean | undefined>;
    /**
     * How long the invite remains valid, in hours. Server default applies when omitted.
     */
    validHours?: pulumi.Input<number | undefined>;
}
