// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class OrgIdp extends pulumi.CustomResource {
    /**
     * Get an existing OrgIdp resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OrgIdpState, opts?: pulumi.CustomResourceOptions): OrgIdp {
        return new OrgIdp(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pangolin:index/orgIdp:OrgIdp';

    /**
     * Returns true if the given object is an instance of OrgIdp.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OrgIdp {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OrgIdp.__pulumiType;
    }

    /**
     * The OIDC authorization URL.
     */
    declare public readonly authUrl: pulumi.Output<string>;
    /**
     * Whether to auto-provision users on first login. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    declare public readonly autoProvision: pulumi.Output<boolean>;
    /**
     * The OIDC client ID.
     */
    declare public readonly clientId: pulumi.Output<string>;
    /**
     * The OIDC client secret.
     */
    declare public readonly clientSecret: pulumi.Output<string>;
    /**
     * The path in the ID token for the user email.
     */
    declare public readonly emailPath: pulumi.Output<string>;
    /**
     * The path in the ID token to use as the user identifier (e.g. <span pulumi-lang-nodejs="`sub`" pulumi-lang-dotnet="`Sub`" pulumi-lang-go="`sub`" pulumi-lang-python="`sub`" pulumi-lang-yaml="`sub`" pulumi-lang-java="`sub`" pulumi-lang-hcl="`sub`">`sub`</span>).
     */
    declare public readonly identifierPath: pulumi.Output<string>;
    /**
     * The display name of the IDP.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The path in the ID token for the user display name.
     */
    declare public readonly namePath: pulumi.Output<string>;
    /**
     * The ID of the organization this IDP is bound to.
     */
    declare public readonly orgId: pulumi.Output<string>;
    /**
     * The numeric IDP ID.
     */
    declare public /*out*/ readonly orgIdpId: pulumi.Output<number>;
    /**
     * Optional expression mapping a token claim to the org binding. Null when unset.
     */
    declare public readonly orgMapping: pulumi.Output<string>;
    /**
     * The OAuth callback URL to configure in your OIDC provider. Only returned on create - empty after import.
     */
    declare public /*out*/ readonly redirectUrl: pulumi.Output<string>;
    /**
     * Optional expression mapping a token claim to a Pangolin role for this org. Null when unset.
     */
    declare public readonly roleMapping: pulumi.Output<string>;
    /**
     * Space-separated OIDC scopes (e.g. `openid email profile`).
     */
    declare public readonly scopes: pulumi.Output<string>;
    /**
     * Optional tags associated with the IDP.
     */
    declare public readonly tags: pulumi.Output<string>;
    /**
     * The OIDC token URL.
     */
    declare public readonly tokenUrl: pulumi.Output<string>;
    /**
     * OIDC variant - refines `type = oidc` to a provider family. One of <span pulumi-lang-nodejs="`oidc`" pulumi-lang-dotnet="`Oidc`" pulumi-lang-go="`oidc`" pulumi-lang-python="`oidc`" pulumi-lang-yaml="`oidc`" pulumi-lang-java="`oidc`" pulumi-lang-hcl="`oidc`">`oidc`</span> (generic, default), <span pulumi-lang-nodejs="`google`" pulumi-lang-dotnet="`Google`" pulumi-lang-go="`google`" pulumi-lang-python="`google`" pulumi-lang-yaml="`google`" pulumi-lang-java="`google`" pulumi-lang-hcl="`google`">`google`</span>, <span pulumi-lang-nodejs="`azure`" pulumi-lang-dotnet="`Azure`" pulumi-lang-go="`azure`" pulumi-lang-python="`azure`" pulumi-lang-yaml="`azure`" pulumi-lang-java="`azure`" pulumi-lang-hcl="`azure`">`azure`</span>.
     */
    declare public readonly variant: pulumi.Output<string>;

    /**
     * Create a OrgIdp resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OrgIdpArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OrgIdpArgs | OrgIdpState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OrgIdpState | undefined;
            resourceInputs["authUrl"] = state?.authUrl;
            resourceInputs["autoProvision"] = state?.autoProvision;
            resourceInputs["clientId"] = state?.clientId;
            resourceInputs["clientSecret"] = state?.clientSecret;
            resourceInputs["emailPath"] = state?.emailPath;
            resourceInputs["identifierPath"] = state?.identifierPath;
            resourceInputs["name"] = state?.name;
            resourceInputs["namePath"] = state?.namePath;
            resourceInputs["orgId"] = state?.orgId;
            resourceInputs["orgIdpId"] = state?.orgIdpId;
            resourceInputs["orgMapping"] = state?.orgMapping;
            resourceInputs["redirectUrl"] = state?.redirectUrl;
            resourceInputs["roleMapping"] = state?.roleMapping;
            resourceInputs["scopes"] = state?.scopes;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["tokenUrl"] = state?.tokenUrl;
            resourceInputs["variant"] = state?.variant;
        } else {
            const args = argsOrState as OrgIdpArgs | undefined;
            if (args?.authUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'authUrl'");
            }
            if (args?.clientId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientId'");
            }
            if (args?.clientSecret === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientSecret'");
            }
            if (args?.identifierPath === undefined && !opts.urn) {
                throw new Error("Missing required property 'identifierPath'");
            }
            if (args?.orgId === undefined && !opts.urn) {
                throw new Error("Missing required property 'orgId'");
            }
            if (args?.scopes === undefined && !opts.urn) {
                throw new Error("Missing required property 'scopes'");
            }
            if (args?.tokenUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'tokenUrl'");
            }
            resourceInputs["authUrl"] = args?.authUrl;
            resourceInputs["autoProvision"] = args?.autoProvision;
            resourceInputs["clientId"] = args?.clientId;
            resourceInputs["clientSecret"] = args?.clientSecret ? pulumi.secret(args.clientSecret) : undefined;
            resourceInputs["emailPath"] = args?.emailPath;
            resourceInputs["identifierPath"] = args?.identifierPath;
            resourceInputs["name"] = args?.name;
            resourceInputs["namePath"] = args?.namePath;
            resourceInputs["orgId"] = args?.orgId;
            resourceInputs["orgMapping"] = args?.orgMapping;
            resourceInputs["roleMapping"] = args?.roleMapping;
            resourceInputs["scopes"] = args?.scopes;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["tokenUrl"] = args?.tokenUrl;
            resourceInputs["variant"] = args?.variant;
            resourceInputs["orgIdpId"] = undefined /*out*/;
            resourceInputs["redirectUrl"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clientSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(OrgIdp.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering OrgIdp resources.
 */
export interface OrgIdpState {
    /**
     * The OIDC authorization URL.
     */
    authUrl?: pulumi.Input<string | undefined>;
    /**
     * Whether to auto-provision users on first login. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    autoProvision?: pulumi.Input<boolean | undefined>;
    /**
     * The OIDC client ID.
     */
    clientId?: pulumi.Input<string | undefined>;
    /**
     * The OIDC client secret.
     */
    clientSecret?: pulumi.Input<string | undefined>;
    /**
     * The path in the ID token for the user email.
     */
    emailPath?: pulumi.Input<string | undefined>;
    /**
     * The path in the ID token to use as the user identifier (e.g. <span pulumi-lang-nodejs="`sub`" pulumi-lang-dotnet="`Sub`" pulumi-lang-go="`sub`" pulumi-lang-python="`sub`" pulumi-lang-yaml="`sub`" pulumi-lang-java="`sub`" pulumi-lang-hcl="`sub`">`sub`</span>).
     */
    identifierPath?: pulumi.Input<string | undefined>;
    /**
     * The display name of the IDP.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The path in the ID token for the user display name.
     */
    namePath?: pulumi.Input<string | undefined>;
    /**
     * The ID of the organization this IDP is bound to.
     */
    orgId?: pulumi.Input<string | undefined>;
    /**
     * The numeric IDP ID.
     */
    orgIdpId?: pulumi.Input<number | undefined>;
    /**
     * Optional expression mapping a token claim to the org binding. Null when unset.
     */
    orgMapping?: pulumi.Input<string | undefined>;
    /**
     * The OAuth callback URL to configure in your OIDC provider. Only returned on create - empty after import.
     */
    redirectUrl?: pulumi.Input<string | undefined>;
    /**
     * Optional expression mapping a token claim to a Pangolin role for this org. Null when unset.
     */
    roleMapping?: pulumi.Input<string | undefined>;
    /**
     * Space-separated OIDC scopes (e.g. `openid email profile`).
     */
    scopes?: pulumi.Input<string | undefined>;
    /**
     * Optional tags associated with the IDP.
     */
    tags?: pulumi.Input<string | undefined>;
    /**
     * The OIDC token URL.
     */
    tokenUrl?: pulumi.Input<string | undefined>;
    /**
     * OIDC variant - refines `type = oidc` to a provider family. One of <span pulumi-lang-nodejs="`oidc`" pulumi-lang-dotnet="`Oidc`" pulumi-lang-go="`oidc`" pulumi-lang-python="`oidc`" pulumi-lang-yaml="`oidc`" pulumi-lang-java="`oidc`" pulumi-lang-hcl="`oidc`">`oidc`</span> (generic, default), <span pulumi-lang-nodejs="`google`" pulumi-lang-dotnet="`Google`" pulumi-lang-go="`google`" pulumi-lang-python="`google`" pulumi-lang-yaml="`google`" pulumi-lang-java="`google`" pulumi-lang-hcl="`google`">`google`</span>, <span pulumi-lang-nodejs="`azure`" pulumi-lang-dotnet="`Azure`" pulumi-lang-go="`azure`" pulumi-lang-python="`azure`" pulumi-lang-yaml="`azure`" pulumi-lang-java="`azure`" pulumi-lang-hcl="`azure`">`azure`</span>.
     */
    variant?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a OrgIdp resource.
 */
export interface OrgIdpArgs {
    /**
     * The OIDC authorization URL.
     */
    authUrl: pulumi.Input<string>;
    /**
     * Whether to auto-provision users on first login. Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    autoProvision?: pulumi.Input<boolean | undefined>;
    /**
     * The OIDC client ID.
     */
    clientId: pulumi.Input<string>;
    /**
     * The OIDC client secret.
     */
    clientSecret: pulumi.Input<string>;
    /**
     * The path in the ID token for the user email.
     */
    emailPath?: pulumi.Input<string | undefined>;
    /**
     * The path in the ID token to use as the user identifier (e.g. <span pulumi-lang-nodejs="`sub`" pulumi-lang-dotnet="`Sub`" pulumi-lang-go="`sub`" pulumi-lang-python="`sub`" pulumi-lang-yaml="`sub`" pulumi-lang-java="`sub`" pulumi-lang-hcl="`sub`">`sub`</span>).
     */
    identifierPath: pulumi.Input<string>;
    /**
     * The display name of the IDP.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The path in the ID token for the user display name.
     */
    namePath?: pulumi.Input<string | undefined>;
    /**
     * The ID of the organization this IDP is bound to.
     */
    orgId: pulumi.Input<string>;
    /**
     * Optional expression mapping a token claim to the org binding. Null when unset.
     */
    orgMapping?: pulumi.Input<string | undefined>;
    /**
     * Optional expression mapping a token claim to a Pangolin role for this org. Null when unset.
     */
    roleMapping?: pulumi.Input<string | undefined>;
    /**
     * Space-separated OIDC scopes (e.g. `openid email profile`).
     */
    scopes: pulumi.Input<string>;
    /**
     * Optional tags associated with the IDP.
     */
    tags?: pulumi.Input<string | undefined>;
    /**
     * The OIDC token URL.
     */
    tokenUrl: pulumi.Input<string>;
    /**
     * OIDC variant - refines `type = oidc` to a provider family. One of <span pulumi-lang-nodejs="`oidc`" pulumi-lang-dotnet="`Oidc`" pulumi-lang-go="`oidc`" pulumi-lang-python="`oidc`" pulumi-lang-yaml="`oidc`" pulumi-lang-java="`oidc`" pulumi-lang-hcl="`oidc`">`oidc`</span> (generic, default), <span pulumi-lang-nodejs="`google`" pulumi-lang-dotnet="`Google`" pulumi-lang-go="`google`" pulumi-lang-python="`google`" pulumi-lang-yaml="`google`" pulumi-lang-java="`google`" pulumi-lang-hcl="`google`">`google`</span>, <span pulumi-lang-nodejs="`azure`" pulumi-lang-dotnet="`Azure`" pulumi-lang-go="`azure`" pulumi-lang-python="`azure`" pulumi-lang-yaml="`azure`" pulumi-lang-java="`azure`" pulumi-lang-hcl="`azure`">`azure`</span>.
     */
    variant?: pulumi.Input<string | undefined>;
}
