// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ResourcePassword extends pulumi.CustomResource {
    /**
     * Get an existing ResourcePassword resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ResourcePasswordState, opts?: pulumi.CustomResourceOptions): ResourcePassword {
        return new ResourcePassword(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pangolin:index/resourcePassword:ResourcePassword';

    /**
     * Returns true if the given object is an instance of ResourcePassword.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ResourcePassword {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ResourcePassword.__pulumiType;
    }

    /**
     * The password required to access the resource.
     */
    declare public readonly password: pulumi.Output<string>;
    /**
     * The ID of the resource to protect with a password.
     */
    declare public readonly resourceId: pulumi.Output<number>;

    /**
     * Create a ResourcePassword resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ResourcePasswordArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ResourcePasswordArgs | ResourcePasswordState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ResourcePasswordState | undefined;
            resourceInputs["password"] = state?.password;
            resourceInputs["resourceId"] = state?.resourceId;
        } else {
            const args = argsOrState as ResourcePasswordArgs | undefined;
            if (args?.password === undefined && !opts.urn) {
                throw new Error("Missing required property 'password'");
            }
            if (args?.resourceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'resourceId'");
            }
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["resourceId"] = args?.resourceId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ResourcePassword.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ResourcePassword resources.
 */
export interface ResourcePasswordState {
    /**
     * The password required to access the resource.
     */
    password?: pulumi.Input<string | undefined>;
    /**
     * The ID of the resource to protect with a password.
     */
    resourceId?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a ResourcePassword resource.
 */
export interface ResourcePasswordArgs {
    /**
     * The password required to access the resource.
     */
    password: pulumi.Input<string>;
    /**
     * The ID of the resource to protect with a password.
     */
    resourceId: pulumi.Input<number>;
}
