// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ResourcePincode extends pulumi.CustomResource {
    /**
     * Get an existing ResourcePincode resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ResourcePincodeState, opts?: pulumi.CustomResourceOptions): ResourcePincode {
        return new ResourcePincode(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pangolin:index/resourcePincode:ResourcePincode';

    /**
     * Returns true if the given object is an instance of ResourcePincode.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ResourcePincode {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ResourcePincode.__pulumiType;
    }

    /**
     * The PIN code (numeric string, typically 6 digits) required to access the resource.
     */
    declare public readonly pincode: pulumi.Output<string>;
    /**
     * The ID of the resource to protect with a PIN code.
     */
    declare public readonly resourceId: pulumi.Output<number>;

    /**
     * Create a ResourcePincode resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ResourcePincodeArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ResourcePincodeArgs | ResourcePincodeState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ResourcePincodeState | undefined;
            resourceInputs["pincode"] = state?.pincode;
            resourceInputs["resourceId"] = state?.resourceId;
        } else {
            const args = argsOrState as ResourcePincodeArgs | undefined;
            if (args?.pincode === undefined && !opts.urn) {
                throw new Error("Missing required property 'pincode'");
            }
            if (args?.resourceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'resourceId'");
            }
            resourceInputs["pincode"] = args?.pincode ? pulumi.secret(args.pincode) : undefined;
            resourceInputs["resourceId"] = args?.resourceId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["pincode"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ResourcePincode.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ResourcePincode resources.
 */
export interface ResourcePincodeState {
    /**
     * The PIN code (numeric string, typically 6 digits) required to access the resource.
     */
    pincode?: pulumi.Input<string | undefined>;
    /**
     * The ID of the resource to protect with a PIN code.
     */
    resourceId?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a ResourcePincode resource.
 */
export interface ResourcePincodeArgs {
    /**
     * The PIN code (numeric string, typically 6 digits) required to access the resource.
     */
    pincode: pulumi.Input<string>;
    /**
     * The ID of the resource to protect with a PIN code.
     */
    resourceId: pulumi.Input<number>;
}
