// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ResourceAccessToken extends pulumi.CustomResource {
    /**
     * Get an existing ResourceAccessToken resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ResourceAccessTokenState, opts?: pulumi.CustomResourceOptions): ResourceAccessToken {
        return new ResourceAccessToken(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pangolin:index/resourceAccessToken:ResourceAccessToken';

    /**
     * Returns true if the given object is an instance of ResourceAccessToken.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ResourceAccessToken {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ResourceAccessToken.__pulumiType;
    }

    /**
     * Creation timestamp (epoch milliseconds).
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<number>;
    /**
     * Optional description.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Expiration timestamp (epoch milliseconds). Null when the token does not expire.
     */
    declare public /*out*/ readonly expiresAt: pulumi.Output<number>;
    /**
     * The ID of the HTTP resource this token authorizes access to.
     */
    declare public readonly resourceId: pulumi.Output<number>;
    /**
     * Session lifetime in milliseconds, as returned by the API.
     */
    declare public /*out*/ readonly sessionLength: pulumi.Output<number>;
    /**
     * Optional human-readable title.
     */
    declare public readonly title: pulumi.Output<string>;
    /**
     * The bearer access token. Only available at creation time; empty after import. Treat as a credential.
     */
    declare public /*out*/ readonly token: pulumi.Output<string>;
    /**
     * SHA-256 hash of the bearer token, exposed by the list endpoints. Not populated on the freshly-created resource; surfaced on subsequent reads.
     */
    declare public /*out*/ readonly tokenHash: pulumi.Output<string>;
    /**
     * Lifetime in seconds. When omitted, the API defaults to roughly 30 days (<span pulumi-lang-nodejs="`sessionLength " pulumi-lang-dotnet="`SessionLength " pulumi-lang-go="`sessionLength " pulumi-lang-python="`session_length " pulumi-lang-yaml="`sessionLength " pulumi-lang-java="`sessionLength " pulumi-lang-hcl="`session_length ">`sessionLength </span>= 2592000000` ms) and <span pulumi-lang-nodejs="`expiresAt`" pulumi-lang-dotnet="`ExpiresAt`" pulumi-lang-go="`expiresAt`" pulumi-lang-python="`expires_at`" pulumi-lang-yaml="`expiresAt`" pulumi-lang-java="`expiresAt`" pulumi-lang-hcl="`expires_at`">`expiresAt`</span> is null (token never expires).
     */
    declare public readonly validForSeconds: pulumi.Output<number | undefined>;

    /**
     * Create a ResourceAccessToken resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ResourceAccessTokenArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ResourceAccessTokenArgs | ResourceAccessTokenState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ResourceAccessTokenState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["description"] = state?.description;
            resourceInputs["expiresAt"] = state?.expiresAt;
            resourceInputs["resourceId"] = state?.resourceId;
            resourceInputs["sessionLength"] = state?.sessionLength;
            resourceInputs["title"] = state?.title;
            resourceInputs["token"] = state?.token;
            resourceInputs["tokenHash"] = state?.tokenHash;
            resourceInputs["validForSeconds"] = state?.validForSeconds;
        } else {
            const args = argsOrState as ResourceAccessTokenArgs | undefined;
            if (args?.resourceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'resourceId'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["resourceId"] = args?.resourceId;
            resourceInputs["title"] = args?.title;
            resourceInputs["validForSeconds"] = args?.validForSeconds;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["expiresAt"] = undefined /*out*/;
            resourceInputs["sessionLength"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["tokenHash"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ResourceAccessToken.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ResourceAccessToken resources.
 */
export interface ResourceAccessTokenState {
    /**
     * Creation timestamp (epoch milliseconds).
     */
    createdAt?: pulumi.Input<number | undefined>;
    /**
     * Optional description.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Expiration timestamp (epoch milliseconds). Null when the token does not expire.
     */
    expiresAt?: pulumi.Input<number | undefined>;
    /**
     * The ID of the HTTP resource this token authorizes access to.
     */
    resourceId?: pulumi.Input<number | undefined>;
    /**
     * Session lifetime in milliseconds, as returned by the API.
     */
    sessionLength?: pulumi.Input<number | undefined>;
    /**
     * Optional human-readable title.
     */
    title?: pulumi.Input<string | undefined>;
    /**
     * The bearer access token. Only available at creation time; empty after import. Treat as a credential.
     */
    token?: pulumi.Input<string | undefined>;
    /**
     * SHA-256 hash of the bearer token, exposed by the list endpoints. Not populated on the freshly-created resource; surfaced on subsequent reads.
     */
    tokenHash?: pulumi.Input<string | undefined>;
    /**
     * Lifetime in seconds. When omitted, the API defaults to roughly 30 days (<span pulumi-lang-nodejs="`sessionLength " pulumi-lang-dotnet="`SessionLength " pulumi-lang-go="`sessionLength " pulumi-lang-python="`session_length " pulumi-lang-yaml="`sessionLength " pulumi-lang-java="`sessionLength " pulumi-lang-hcl="`session_length ">`sessionLength </span>= 2592000000` ms) and <span pulumi-lang-nodejs="`expiresAt`" pulumi-lang-dotnet="`ExpiresAt`" pulumi-lang-go="`expiresAt`" pulumi-lang-python="`expires_at`" pulumi-lang-yaml="`expiresAt`" pulumi-lang-java="`expiresAt`" pulumi-lang-hcl="`expires_at`">`expiresAt`</span> is null (token never expires).
     */
    validForSeconds?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a ResourceAccessToken resource.
 */
export interface ResourceAccessTokenArgs {
    /**
     * Optional description.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The ID of the HTTP resource this token authorizes access to.
     */
    resourceId: pulumi.Input<number>;
    /**
     * Optional human-readable title.
     */
    title?: pulumi.Input<string | undefined>;
    /**
     * Lifetime in seconds. When omitted, the API defaults to roughly 30 days (<span pulumi-lang-nodejs="`sessionLength " pulumi-lang-dotnet="`SessionLength " pulumi-lang-go="`sessionLength " pulumi-lang-python="`session_length " pulumi-lang-yaml="`sessionLength " pulumi-lang-java="`sessionLength " pulumi-lang-hcl="`session_length ">`sessionLength </span>= 2592000000` ms) and <span pulumi-lang-nodejs="`expiresAt`" pulumi-lang-dotnet="`ExpiresAt`" pulumi-lang-go="`expiresAt`" pulumi-lang-python="`expires_at`" pulumi-lang-yaml="`expiresAt`" pulumi-lang-java="`expiresAt`" pulumi-lang-hcl="`expires_at`">`expiresAt`</span> is null (token never expires).
     */
    validForSeconds?: pulumi.Input<number | undefined>;
}
