// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SiteResourceRole extends pulumi.CustomResource {
    /**
     * Get an existing SiteResourceRole resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SiteResourceRoleState, opts?: pulumi.CustomResourceOptions): SiteResourceRole {
        return new SiteResourceRole(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pangolin:index/siteResourceRole:SiteResourceRole';

    /**
     * Returns true if the given object is an instance of SiteResourceRole.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SiteResourceRole {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SiteResourceRole.__pulumiType;
    }

    /**
     * The ID of the role to assign.
     */
    declare public readonly roleId: pulumi.Output<number>;
    /**
     * The ID of the private site resource.
     */
    declare public readonly siteResourceId: pulumi.Output<number>;

    /**
     * Create a SiteResourceRole resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SiteResourceRoleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SiteResourceRoleArgs | SiteResourceRoleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SiteResourceRoleState | undefined;
            resourceInputs["roleId"] = state?.roleId;
            resourceInputs["siteResourceId"] = state?.siteResourceId;
        } else {
            const args = argsOrState as SiteResourceRoleArgs | undefined;
            if (args?.roleId === undefined && !opts.urn) {
                throw new Error("Missing required property 'roleId'");
            }
            if (args?.siteResourceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'siteResourceId'");
            }
            resourceInputs["roleId"] = args?.roleId;
            resourceInputs["siteResourceId"] = args?.siteResourceId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SiteResourceRole.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SiteResourceRole resources.
 */
export interface SiteResourceRoleState {
    /**
     * The ID of the role to assign.
     */
    roleId?: pulumi.Input<number | undefined>;
    /**
     * The ID of the private site resource.
     */
    siteResourceId?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a SiteResourceRole resource.
 */
export interface SiteResourceRoleArgs {
    /**
     * The ID of the role to assign.
     */
    roleId: pulumi.Input<number>;
    /**
     * The ID of the private site resource.
     */
    siteResourceId: pulumi.Input<number>;
}
