---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - network-policy.default-hardened.yaml
  - network-policy.allow-to-kube-apiserver.yaml
  - network-policy.allow-to-s3-backup.yaml
