---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homebox-auth-pepper
spec:
  dataFrom:
    - extract:
        key: lungmen.akn/homebox/auth/api-key-pepper
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    name: homebox-auth-pepper
