---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homebox-storage-credentials
spec:
  dataFrom:
    - extract:
        key: lungmen.akn/homebox/storage/s3.chezmoi.sh
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    name: homebox-storage-credentials
