---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homebox

labels:
  - pairs:
      app.kubernetes.io/name: homebox
      app.kubernetes.io/instance: homebox
    includeTemplates: true
    includeSelectors: true

resources:
  - homebox.auth.externalsecret.yaml
  - homebox.database.externalsecret.yaml
  - homebox.deployment.yaml
  - homebox.httproute.yaml
  - homebox.oidc.externalsecret.yaml
  - homebox.storage.externalsecret.yaml

  - security/

images:
  # renovate: datasource=docker depName=ghcr.io/sysadminsmedia/homebox
  - name: ghcr.io/sysadminsmedia/homebox
    newName: oci.chezmoi.sh/ghcr.io/sysadminsmedia/homebox
    newTag: "0.26.2"
