// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Certificate extends pulumi.CustomResource {
	/**
	 * Get an existing Certificate resource's state with the given name, ID, and optional extra
	 * properties used to qualify the lookup.
	 *
	 * @param name The _unique_ name of the resulting resource.
	 * @param id The _unique_ provider ID of the resource to lookup.
	 * @param state Any extra arguments used during the lookup.
	 * @param opts Optional settings to control the behavior of the CustomResource.
	 */
	public static get(
		name: string,
		id: pulumi.Input<pulumi.ID>,
		state?: CertificateState,
		opts?: pulumi.CustomResourceOptions,
	): Certificate {
		return new Certificate(name, <any>state, { ...opts, id: id });
	}

	/** @internal */
	public static readonly __pulumiType = "truenas:index/certificate:Certificate";

	/**
	 * Returns true if the given object is an instance of Certificate.  This is designed to work even
	 * when multiple copies of the Pulumi SDK have been loaded into the same process.
	 */
	public static isInstance(obj: any): obj is Certificate {
		if (obj === undefined || obj === null) {
			return false;
		}
		return obj["__pulumiType"] === Certificate.__pulumiType;
	}

	/**
	 * The PEM-encoded certificate data. Required for CERTIFICATE_CREATE_IMPORTED.
	 */
	public declare readonly certificate: pulumi.Output<string>;
	/**
	 * The certificate city/locality (L).
	 */
	public declare readonly city: pulumi.Output<string>;
	/**
	 * The common name (CN) of the certificate.
	 */
	public declare readonly common: pulumi.Output<string>;
	/**
	 * The certificate country (C). Two-letter ISO 3166 code.
	 */
	public declare readonly country: pulumi.Output<string>;
	/**
	 * The certificate creation type: CERTIFICATE_CREATE_IMPORTED, CERTIFICATE_CREATE_CSR, CERTIFICATE_CREATE_IMPORTED_CSR, or CERTIFICATE_CREATE_ACME.
	 */
	public declare readonly createType: pulumi.Output<string>;
	/**
	 * The digest algorithm (e.g., SHA256, SHA384).
	 */
	public declare readonly digestAlgorithm: pulumi.Output<string>;
	/**
	 * The full distinguished name.
	 */
	public /*out*/ declare readonly dn: pulumi.Output<string>;
	/**
	 * The certificate email address.
	 */
	public declare readonly email: pulumi.Output<string>;
	/**
	 * Whether the certificate has expired.
	 */
	public /*out*/ declare readonly expired: pulumi.Output<boolean>;
	/**
	 * The certificate valid-from date.
	 */
	public /*out*/ declare readonly from: pulumi.Output<string>;
	/**
	 * The key length in bits (1024, 2048, 4096).
	 */
	public declare readonly keyLength: pulumi.Output<number>;
	/**
	 * The key type: RSA or EC.
	 */
	public declare readonly keyType: pulumi.Output<string>;
	/**
	 * The certificate lifetime in days (1-36500).
	 */
	public declare readonly lifetime: pulumi.Output<number>;
	/**
	 * The name of the certificate.
	 */
	public declare readonly name: pulumi.Output<string>;
	/**
	 * The certificate organization (O).
	 */
	public declare readonly organization: pulumi.Output<string>;
	/**
	 * The certificate organizational unit (OU).
	 */
	public declare readonly organizationalUnit: pulumi.Output<string>;
	/**
	 * The PEM-encoded private key. Required for CERTIFICATE_CREATE_IMPORTED.
	 */
	public declare readonly privatekey: pulumi.Output<string | undefined>;
	/**
	 * Subject alternative names.
	 */
	public declare readonly sans: pulumi.Output<string[]>;
	/**
	 * The certificate state/province (ST).
	 */
	public declare readonly state: pulumi.Output<string>;
	public declare readonly timeouts: pulumi.Output<
		outputs.CertificateTimeouts | undefined
	>;
	/**
	 * The certificate valid-until date.
	 */
	public /*out*/ declare readonly until: pulumi.Output<string>;

	/**
	 * Create a Certificate resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 * @param opts A bag of options that control this resource's behavior.
	 */
	constructor(
		name: string,
		args: CertificateArgs,
		opts?: pulumi.CustomResourceOptions,
	);
	constructor(
		name: string,
		argsOrState?: CertificateArgs | CertificateState,
		opts?: pulumi.CustomResourceOptions,
	) {
		const resourceInputs: pulumi.Inputs = {};
		opts = opts || {};
		if (opts.id) {
			const state = argsOrState as CertificateState | undefined;
			resourceInputs["certificate"] = state?.certificate;
			resourceInputs["city"] = state?.city;
			resourceInputs["common"] = state?.common;
			resourceInputs["country"] = state?.country;
			resourceInputs["createType"] = state?.createType;
			resourceInputs["digestAlgorithm"] = state?.digestAlgorithm;
			resourceInputs["dn"] = state?.dn;
			resourceInputs["email"] = state?.email;
			resourceInputs["expired"] = state?.expired;
			resourceInputs["from"] = state?.from;
			resourceInputs["keyLength"] = state?.keyLength;
			resourceInputs["keyType"] = state?.keyType;
			resourceInputs["lifetime"] = state?.lifetime;
			resourceInputs["name"] = state?.name;
			resourceInputs["organization"] = state?.organization;
			resourceInputs["organizationalUnit"] = state?.organizationalUnit;
			resourceInputs["privatekey"] = state?.privatekey;
			resourceInputs["sans"] = state?.sans;
			resourceInputs["state"] = state?.state;
			resourceInputs["timeouts"] = state?.timeouts;
			resourceInputs["until"] = state?.until;
		} else {
			const args = argsOrState as CertificateArgs | undefined;
			if (args?.createType === undefined && !opts.urn) {
				throw new Error("Missing required property 'createType'");
			}
			resourceInputs["certificate"] = args?.certificate;
			resourceInputs["city"] = args?.city;
			resourceInputs["common"] = args?.common;
			resourceInputs["country"] = args?.country;
			resourceInputs["createType"] = args?.createType;
			resourceInputs["digestAlgorithm"] = args?.digestAlgorithm;
			resourceInputs["email"] = args?.email;
			resourceInputs["keyLength"] = args?.keyLength;
			resourceInputs["keyType"] = args?.keyType;
			resourceInputs["lifetime"] = args?.lifetime;
			resourceInputs["name"] = args?.name;
			resourceInputs["organization"] = args?.organization;
			resourceInputs["organizationalUnit"] = args?.organizationalUnit;
			resourceInputs["privatekey"] = args?.privatekey
				? pulumi.secret(args.privatekey)
				: undefined;
			resourceInputs["sans"] = args?.sans;
			resourceInputs["state"] = args?.state;
			resourceInputs["timeouts"] = args?.timeouts;
			resourceInputs["dn"] = undefined /*out*/;
			resourceInputs["expired"] = undefined /*out*/;
			resourceInputs["from"] = undefined /*out*/;
			resourceInputs["until"] = undefined /*out*/;
		}
		opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
		const secretOpts = { additionalSecretOutputs: ["privatekey"] };
		opts = pulumi.mergeOptions(opts, secretOpts);
		super(
			Certificate.__pulumiType,
			name,
			resourceInputs,
			opts,
			false /*dependency*/,
			utilities.getPackage(),
		);
	}
}

/**
 * Input properties used for looking up and filtering Certificate resources.
 */
export interface CertificateState {
	/**
	 * The PEM-encoded certificate data. Required for CERTIFICATE_CREATE_IMPORTED.
	 */
	certificate?: pulumi.Input<string | undefined>;
	/**
	 * The certificate city/locality (L).
	 */
	city?: pulumi.Input<string | undefined>;
	/**
	 * The common name (CN) of the certificate.
	 */
	common?: pulumi.Input<string | undefined>;
	/**
	 * The certificate country (C). Two-letter ISO 3166 code.
	 */
	country?: pulumi.Input<string | undefined>;
	/**
	 * The certificate creation type: CERTIFICATE_CREATE_IMPORTED, CERTIFICATE_CREATE_CSR, CERTIFICATE_CREATE_IMPORTED_CSR, or CERTIFICATE_CREATE_ACME.
	 */
	createType?: pulumi.Input<string | undefined>;
	/**
	 * The digest algorithm (e.g., SHA256, SHA384).
	 */
	digestAlgorithm?: pulumi.Input<string | undefined>;
	/**
	 * The full distinguished name.
	 */
	dn?: pulumi.Input<string | undefined>;
	/**
	 * The certificate email address.
	 */
	email?: pulumi.Input<string | undefined>;
	/**
	 * Whether the certificate has expired.
	 */
	expired?: pulumi.Input<boolean | undefined>;
	/**
	 * The certificate valid-from date.
	 */
	from?: pulumi.Input<string | undefined>;
	/**
	 * The key length in bits (1024, 2048, 4096).
	 */
	keyLength?: pulumi.Input<number | undefined>;
	/**
	 * The key type: RSA or EC.
	 */
	keyType?: pulumi.Input<string | undefined>;
	/**
	 * The certificate lifetime in days (1-36500).
	 */
	lifetime?: pulumi.Input<number | undefined>;
	/**
	 * The name of the certificate.
	 */
	name?: pulumi.Input<string | undefined>;
	/**
	 * The certificate organization (O).
	 */
	organization?: pulumi.Input<string | undefined>;
	/**
	 * The certificate organizational unit (OU).
	 */
	organizationalUnit?: pulumi.Input<string | undefined>;
	/**
	 * The PEM-encoded private key. Required for CERTIFICATE_CREATE_IMPORTED.
	 */
	privatekey?: pulumi.Input<string | undefined>;
	/**
	 * Subject alternative names.
	 */
	sans?: pulumi.Input<pulumi.Input<string>[] | undefined>;
	/**
	 * The certificate state/province (ST).
	 */
	state?: pulumi.Input<string | undefined>;
	timeouts?: pulumi.Input<inputs.CertificateTimeouts | undefined>;
	/**
	 * The certificate valid-until date.
	 */
	until?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Certificate resource.
 */
export interface CertificateArgs {
	/**
	 * The PEM-encoded certificate data. Required for CERTIFICATE_CREATE_IMPORTED.
	 */
	certificate?: pulumi.Input<string | undefined>;
	/**
	 * The certificate city/locality (L).
	 */
	city?: pulumi.Input<string | undefined>;
	/**
	 * The common name (CN) of the certificate.
	 */
	common?: pulumi.Input<string | undefined>;
	/**
	 * The certificate country (C). Two-letter ISO 3166 code.
	 */
	country?: pulumi.Input<string | undefined>;
	/**
	 * The certificate creation type: CERTIFICATE_CREATE_IMPORTED, CERTIFICATE_CREATE_CSR, CERTIFICATE_CREATE_IMPORTED_CSR, or CERTIFICATE_CREATE_ACME.
	 */
	createType: pulumi.Input<string>;
	/**
	 * The digest algorithm (e.g., SHA256, SHA384).
	 */
	digestAlgorithm?: pulumi.Input<string | undefined>;
	/**
	 * The certificate email address.
	 */
	email?: pulumi.Input<string | undefined>;
	/**
	 * The key length in bits (1024, 2048, 4096).
	 */
	keyLength?: pulumi.Input<number | undefined>;
	/**
	 * The key type: RSA or EC.
	 */
	keyType?: pulumi.Input<string | undefined>;
	/**
	 * The certificate lifetime in days (1-36500).
	 */
	lifetime?: pulumi.Input<number | undefined>;
	/**
	 * The name of the certificate.
	 */
	name?: pulumi.Input<string | undefined>;
	/**
	 * The certificate organization (O).
	 */
	organization?: pulumi.Input<string | undefined>;
	/**
	 * The certificate organizational unit (OU).
	 */
	organizationalUnit?: pulumi.Input<string | undefined>;
	/**
	 * The PEM-encoded private key. Required for CERTIFICATE_CREATE_IMPORTED.
	 */
	privatekey?: pulumi.Input<string | undefined>;
	/**
	 * Subject alternative names.
	 */
	sans?: pulumi.Input<pulumi.Input<string>[] | undefined>;
	/**
	 * The certificate state/province (ST).
	 */
	state?: pulumi.Input<string | undefined>;
	timeouts?: pulumi.Input<inputs.CertificateTimeouts | undefined>;
}
