// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class CloudSync extends pulumi.CustomResource {
	/**
	 * Get an existing CloudSync resource's state with the given name, ID, and optional extra
	 * properties used to qualify the lookup.
	 *
	 * @param name The _unique_ name of the resulting resource.
	 * @param id The _unique_ provider ID of the resource to lookup.
	 * @param state Any extra arguments used during the lookup.
	 * @param opts Optional settings to control the behavior of the CustomResource.
	 */
	public static get(
		name: string,
		id: pulumi.Input<pulumi.ID>,
		state?: CloudSyncState,
		opts?: pulumi.CustomResourceOptions,
	): CloudSync {
		return new CloudSync(name, <any>state, { ...opts, id: id });
	}

	/** @internal */
	public static readonly __pulumiType = "truenas:index/cloudSync:CloudSync";

	/**
	 * Returns true if the given object is an instance of CloudSync.  This is designed to work even
	 * when multiple copies of the Pulumi SDK have been loaded into the same process.
	 */
	public static isInstance(obj: any): obj is CloudSync {
		if (obj === undefined || obj === null) {
			return false;
		}
		return obj["__pulumiType"] === CloudSync.__pulumiType;
	}

	/**
	 * JSON-encoded provider-specific attributes (e.g. `{"bucket":"my-bucket","folder":"/backups"}`). Exact keys depend on the cloud credential type.
	 */
	public declare readonly attributesJson: pulumi.Output<string>;
	/**
	 * The ID of the cloud credential to use.
	 */
	public declare readonly credentials: pulumi.Output<number>;
	/**
	 * A description for the cloud sync task.
	 */
	public declare readonly description: pulumi.Output<string>;
	/**
	 * Sync direction: PUSH or PULL.
	 */
	public declare readonly direction: pulumi.Output<string>;
	/**
	 * Whether the cloud sync task is enabled.
	 */
	public declare readonly enabled: pulumi.Output<boolean>;
	/**
	 * The local path to sync (e.g., /mnt/tank/backup).
	 */
	public declare readonly path: pulumi.Output<string>;
	/**
	 * Cron schedule day-of-month field.
	 */
	public declare readonly scheduleDom: pulumi.Output<string>;
	/**
	 * Cron schedule day-of-week field.
	 */
	public declare readonly scheduleDow: pulumi.Output<string>;
	/**
	 * Cron schedule hour field.
	 */
	public declare readonly scheduleHour: pulumi.Output<string>;
	/**
	 * Cron schedule minute field.
	 */
	public declare readonly scheduleMinute: pulumi.Output<string>;
	/**
	 * Cron schedule month field.
	 */
	public declare readonly scheduleMonth: pulumi.Output<string>;
	public declare readonly timeouts: pulumi.Output<
		outputs.CloudSyncTimeouts | undefined
	>;
	/**
	 * Transfer mode: SYNC, COPY, or MOVE.
	 */
	public declare readonly transferMode: pulumi.Output<string>;

	/**
	 * Create a CloudSync resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 * @param opts A bag of options that control this resource's behavior.
	 */
	constructor(
		name: string,
		args: CloudSyncArgs,
		opts?: pulumi.CustomResourceOptions,
	);
	constructor(
		name: string,
		argsOrState?: CloudSyncArgs | CloudSyncState,
		opts?: pulumi.CustomResourceOptions,
	) {
		const resourceInputs: pulumi.Inputs = {};
		opts = opts || {};
		if (opts.id) {
			const state = argsOrState as CloudSyncState | undefined;
			resourceInputs["attributesJson"] = state?.attributesJson;
			resourceInputs["credentials"] = state?.credentials;
			resourceInputs["description"] = state?.description;
			resourceInputs["direction"] = state?.direction;
			resourceInputs["enabled"] = state?.enabled;
			resourceInputs["path"] = state?.path;
			resourceInputs["scheduleDom"] = state?.scheduleDom;
			resourceInputs["scheduleDow"] = state?.scheduleDow;
			resourceInputs["scheduleHour"] = state?.scheduleHour;
			resourceInputs["scheduleMinute"] = state?.scheduleMinute;
			resourceInputs["scheduleMonth"] = state?.scheduleMonth;
			resourceInputs["timeouts"] = state?.timeouts;
			resourceInputs["transferMode"] = state?.transferMode;
		} else {
			const args = argsOrState as CloudSyncArgs | undefined;
			if (args?.credentials === undefined && !opts.urn) {
				throw new Error("Missing required property 'credentials'");
			}
			if (args?.direction === undefined && !opts.urn) {
				throw new Error("Missing required property 'direction'");
			}
			if (args?.path === undefined && !opts.urn) {
				throw new Error("Missing required property 'path'");
			}
			if (args?.transferMode === undefined && !opts.urn) {
				throw new Error("Missing required property 'transferMode'");
			}
			resourceInputs["attributesJson"] = args?.attributesJson;
			resourceInputs["credentials"] = args?.credentials;
			resourceInputs["description"] = args?.description;
			resourceInputs["direction"] = args?.direction;
			resourceInputs["enabled"] = args?.enabled;
			resourceInputs["path"] = args?.path;
			resourceInputs["scheduleDom"] = args?.scheduleDom;
			resourceInputs["scheduleDow"] = args?.scheduleDow;
			resourceInputs["scheduleHour"] = args?.scheduleHour;
			resourceInputs["scheduleMinute"] = args?.scheduleMinute;
			resourceInputs["scheduleMonth"] = args?.scheduleMonth;
			resourceInputs["timeouts"] = args?.timeouts;
			resourceInputs["transferMode"] = args?.transferMode;
		}
		opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
		super(
			CloudSync.__pulumiType,
			name,
			resourceInputs,
			opts,
			false /*dependency*/,
			utilities.getPackage(),
		);
	}
}

/**
 * Input properties used for looking up and filtering CloudSync resources.
 */
export interface CloudSyncState {
	/**
	 * JSON-encoded provider-specific attributes (e.g. `{"bucket":"my-bucket","folder":"/backups"}`). Exact keys depend on the cloud credential type.
	 */
	attributesJson?: pulumi.Input<string | undefined>;
	/**
	 * The ID of the cloud credential to use.
	 */
	credentials?: pulumi.Input<number | undefined>;
	/**
	 * A description for the cloud sync task.
	 */
	description?: pulumi.Input<string | undefined>;
	/**
	 * Sync direction: PUSH or PULL.
	 */
	direction?: pulumi.Input<string | undefined>;
	/**
	 * Whether the cloud sync task is enabled.
	 */
	enabled?: pulumi.Input<boolean | undefined>;
	/**
	 * The local path to sync (e.g., /mnt/tank/backup).
	 */
	path?: pulumi.Input<string | undefined>;
	/**
	 * Cron schedule day-of-month field.
	 */
	scheduleDom?: pulumi.Input<string | undefined>;
	/**
	 * Cron schedule day-of-week field.
	 */
	scheduleDow?: pulumi.Input<string | undefined>;
	/**
	 * Cron schedule hour field.
	 */
	scheduleHour?: pulumi.Input<string | undefined>;
	/**
	 * Cron schedule minute field.
	 */
	scheduleMinute?: pulumi.Input<string | undefined>;
	/**
	 * Cron schedule month field.
	 */
	scheduleMonth?: pulumi.Input<string | undefined>;
	timeouts?: pulumi.Input<inputs.CloudSyncTimeouts | undefined>;
	/**
	 * Transfer mode: SYNC, COPY, or MOVE.
	 */
	transferMode?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a CloudSync resource.
 */
export interface CloudSyncArgs {
	/**
	 * JSON-encoded provider-specific attributes (e.g. `{"bucket":"my-bucket","folder":"/backups"}`). Exact keys depend on the cloud credential type.
	 */
	attributesJson?: pulumi.Input<string | undefined>;
	/**
	 * The ID of the cloud credential to use.
	 */
	credentials: pulumi.Input<number>;
	/**
	 * A description for the cloud sync task.
	 */
	description?: pulumi.Input<string | undefined>;
	/**
	 * Sync direction: PUSH or PULL.
	 */
	direction: pulumi.Input<string>;
	/**
	 * Whether the cloud sync task is enabled.
	 */
	enabled?: pulumi.Input<boolean | undefined>;
	/**
	 * The local path to sync (e.g., /mnt/tank/backup).
	 */
	path: pulumi.Input<string>;
	/**
	 * Cron schedule day-of-month field.
	 */
	scheduleDom?: pulumi.Input<string | undefined>;
	/**
	 * Cron schedule day-of-week field.
	 */
	scheduleDow?: pulumi.Input<string | undefined>;
	/**
	 * Cron schedule hour field.
	 */
	scheduleHour?: pulumi.Input<string | undefined>;
	/**
	 * Cron schedule minute field.
	 */
	scheduleMinute?: pulumi.Input<string | undefined>;
	/**
	 * Cron schedule month field.
	 */
	scheduleMonth?: pulumi.Input<string | undefined>;
	timeouts?: pulumi.Input<inputs.CloudSyncTimeouts | undefined>;
	/**
	 * Transfer mode: SYNC, COPY, or MOVE.
	 */
	transferMode: pulumi.Input<string>;
}
