// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class FilesystemAcl extends pulumi.CustomResource {
	/**
	 * Get an existing FilesystemAcl resource's state with the given name, ID, and optional extra
	 * properties used to qualify the lookup.
	 *
	 * @param name The _unique_ name of the resulting resource.
	 * @param id The _unique_ provider ID of the resource to lookup.
	 * @param state Any extra arguments used during the lookup.
	 * @param opts Optional settings to control the behavior of the CustomResource.
	 */
	public static get(
		name: string,
		id: pulumi.Input<pulumi.ID>,
		state?: FilesystemAclState,
		opts?: pulumi.CustomResourceOptions,
	): FilesystemAcl {
		return new FilesystemAcl(name, <any>state, { ...opts, id: id });
	}

	/** @internal */
	public static readonly __pulumiType =
		"truenas:index/filesystemAcl:FilesystemAcl";

	/**
	 * Returns true if the given object is an instance of FilesystemAcl.  This is designed to work even
	 * when multiple copies of the Pulumi SDK have been loaded into the same process.
	 */
	public static isInstance(obj: any): obj is FilesystemAcl {
		if (obj === undefined || obj === null) {
			return false;
		}
		return obj["__pulumiType"] === FilesystemAcl.__pulumiType;
	}

	/**
	 * The ACL type (POSIX1E or NFS4).
	 */
	public declare readonly acltype: pulumi.Output<string>;
	/**
	 * List of ACL entries.
	 */
	public declare readonly dacls: pulumi.Output<outputs.FilesystemAclDacl[]>;
	/**
	 * The owner GID.
	 */
	public declare readonly gid: pulumi.Output<number>;
	/**
	 * The filesystem path to manage ACLs on (e.g., /mnt/pool/dataset).
	 */
	public declare readonly path: pulumi.Output<string>;
	public declare readonly timeouts: pulumi.Output<
		outputs.FilesystemAclTimeouts | undefined
	>;
	/**
	 * The owner UID.
	 */
	public declare readonly uid: pulumi.Output<number>;

	/**
	 * Create a FilesystemAcl resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 * @param opts A bag of options that control this resource's behavior.
	 */
	constructor(
		name: string,
		args: FilesystemAclArgs,
		opts?: pulumi.CustomResourceOptions,
	);
	constructor(
		name: string,
		argsOrState?: FilesystemAclArgs | FilesystemAclState,
		opts?: pulumi.CustomResourceOptions,
	) {
		const resourceInputs: pulumi.Inputs = {};
		opts = opts || {};
		if (opts.id) {
			const state = argsOrState as FilesystemAclState | undefined;
			resourceInputs["acltype"] = state?.acltype;
			resourceInputs["dacls"] = state?.dacls;
			resourceInputs["gid"] = state?.gid;
			resourceInputs["path"] = state?.path;
			resourceInputs["timeouts"] = state?.timeouts;
			resourceInputs["uid"] = state?.uid;
		} else {
			const args = argsOrState as FilesystemAclArgs | undefined;
			if (args?.dacls === undefined && !opts.urn) {
				throw new Error("Missing required property 'dacls'");
			}
			if (args?.path === undefined && !opts.urn) {
				throw new Error("Missing required property 'path'");
			}
			resourceInputs["acltype"] = args?.acltype;
			resourceInputs["dacls"] = args?.dacls;
			resourceInputs["gid"] = args?.gid;
			resourceInputs["path"] = args?.path;
			resourceInputs["timeouts"] = args?.timeouts;
			resourceInputs["uid"] = args?.uid;
		}
		opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
		super(
			FilesystemAcl.__pulumiType,
			name,
			resourceInputs,
			opts,
			false /*dependency*/,
			utilities.getPackage(),
		);
	}
}

/**
 * Input properties used for looking up and filtering FilesystemAcl resources.
 */
export interface FilesystemAclState {
	/**
	 * The ACL type (POSIX1E or NFS4).
	 */
	acltype?: pulumi.Input<string | undefined>;
	/**
	 * List of ACL entries.
	 */
	dacls?: pulumi.Input<pulumi.Input<inputs.FilesystemAclDacl>[] | undefined>;
	/**
	 * The owner GID.
	 */
	gid?: pulumi.Input<number | undefined>;
	/**
	 * The filesystem path to manage ACLs on (e.g., /mnt/pool/dataset).
	 */
	path?: pulumi.Input<string | undefined>;
	timeouts?: pulumi.Input<inputs.FilesystemAclTimeouts | undefined>;
	/**
	 * The owner UID.
	 */
	uid?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a FilesystemAcl resource.
 */
export interface FilesystemAclArgs {
	/**
	 * The ACL type (POSIX1E or NFS4).
	 */
	acltype?: pulumi.Input<string | undefined>;
	/**
	 * List of ACL entries.
	 */
	dacls: pulumi.Input<pulumi.Input<inputs.FilesystemAclDacl>[]>;
	/**
	 * The owner GID.
	 */
	gid?: pulumi.Input<number | undefined>;
	/**
	 * The filesystem path to manage ACLs on (e.g., /mnt/pool/dataset).
	 */
	path: pulumi.Input<string>;
	timeouts?: pulumi.Input<inputs.FilesystemAclTimeouts | undefined>;
	/**
	 * The owner UID.
	 */
	uid?: pulumi.Input<number | undefined>;
}
