// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class FtpConfig extends pulumi.CustomResource {
	/**
	 * Get an existing FtpConfig resource's state with the given name, ID, and optional extra
	 * properties used to qualify the lookup.
	 *
	 * @param name The _unique_ name of the resulting resource.
	 * @param id The _unique_ provider ID of the resource to lookup.
	 * @param state Any extra arguments used during the lookup.
	 * @param opts Optional settings to control the behavior of the CustomResource.
	 */
	public static get(
		name: string,
		id: pulumi.Input<pulumi.ID>,
		state?: FtpConfigState,
		opts?: pulumi.CustomResourceOptions,
	): FtpConfig {
		return new FtpConfig(name, <any>state, { ...opts, id: id });
	}

	/** @internal */
	public static readonly __pulumiType = "truenas:index/ftpConfig:FtpConfig";

	/**
	 * Returns true if the given object is an instance of FtpConfig.  This is designed to work even
	 * when multiple copies of the Pulumi SDK have been loaded into the same process.
	 */
	public static isInstance(obj: any): obj is FtpConfig {
		if (obj === undefined || obj === null) {
			return false;
		}
		return obj["__pulumiType"] === FtpConfig.__pulumiType;
	}

	/**
	 * FTP banner message.
	 */
	public declare readonly banner: pulumi.Output<string>;
	/**
	 * Maximum number of simultaneous clients (1-10000).
	 */
	public declare readonly clients: pulumi.Output<number>;
	/**
	 * Chroot users to their home directory.
	 */
	public declare readonly defaultroot: pulumi.Output<boolean>;
	/**
	 * Directory creation mask (umask), octal (e.g. 022).
	 */
	public declare readonly dirmask: pulumi.Output<string>;
	/**
	 * File creation mask (umask), octal (e.g. 077).
	 */
	public declare readonly filemask: pulumi.Output<string>;
	/**
	 * Enable FXP (File eXchange Protocol).
	 */
	public declare readonly fxp: pulumi.Output<boolean>;
	/**
	 * Maximum connections per IP address (0 = unlimited, max 1000).
	 */
	public declare readonly ipconnections: pulumi.Output<number>;
	/**
	 * Maximum login attempts before disconnect (1-1000).
	 */
	public declare readonly loginattempt: pulumi.Output<number>;
	/**
	 * Allow only anonymous logins.
	 */
	public declare readonly onlyanonymous: pulumi.Output<boolean>;
	/**
	 * Allow only local user logins.
	 */
	public declare readonly onlylocal: pulumi.Output<boolean>;
	/**
	 * FTP port.
	 */
	public declare readonly port: pulumi.Output<number>;
	/**
	 * Allow transfer resume.
	 */
	public declare readonly resume: pulumi.Output<boolean>;
	/**
	 * Timeout in seconds for idle connections (1-10000).
	 */
	public declare readonly timeout: pulumi.Output<number>;
	public declare readonly timeouts: pulumi.Output<
		outputs.FtpConfigTimeouts | undefined
	>;
	/**
	 * Enable TLS for FTP connections.
	 */
	public declare readonly tls: pulumi.Output<boolean>;

	/**
	 * Create a FtpConfig resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 * @param opts A bag of options that control this resource's behavior.
	 */
	constructor(
		name: string,
		args?: FtpConfigArgs,
		opts?: pulumi.CustomResourceOptions,
	);
	constructor(
		name: string,
		argsOrState?: FtpConfigArgs | FtpConfigState,
		opts?: pulumi.CustomResourceOptions,
	) {
		const resourceInputs: pulumi.Inputs = {};
		opts = opts || {};
		if (opts.id) {
			const state = argsOrState as FtpConfigState | undefined;
			resourceInputs["banner"] = state?.banner;
			resourceInputs["clients"] = state?.clients;
			resourceInputs["defaultroot"] = state?.defaultroot;
			resourceInputs["dirmask"] = state?.dirmask;
			resourceInputs["filemask"] = state?.filemask;
			resourceInputs["fxp"] = state?.fxp;
			resourceInputs["ipconnections"] = state?.ipconnections;
			resourceInputs["loginattempt"] = state?.loginattempt;
			resourceInputs["onlyanonymous"] = state?.onlyanonymous;
			resourceInputs["onlylocal"] = state?.onlylocal;
			resourceInputs["port"] = state?.port;
			resourceInputs["resume"] = state?.resume;
			resourceInputs["timeout"] = state?.timeout;
			resourceInputs["timeouts"] = state?.timeouts;
			resourceInputs["tls"] = state?.tls;
		} else {
			const args = argsOrState as FtpConfigArgs | undefined;
			resourceInputs["banner"] = args?.banner;
			resourceInputs["clients"] = args?.clients;
			resourceInputs["defaultroot"] = args?.defaultroot;
			resourceInputs["dirmask"] = args?.dirmask;
			resourceInputs["filemask"] = args?.filemask;
			resourceInputs["fxp"] = args?.fxp;
			resourceInputs["ipconnections"] = args?.ipconnections;
			resourceInputs["loginattempt"] = args?.loginattempt;
			resourceInputs["onlyanonymous"] = args?.onlyanonymous;
			resourceInputs["onlylocal"] = args?.onlylocal;
			resourceInputs["port"] = args?.port;
			resourceInputs["resume"] = args?.resume;
			resourceInputs["timeout"] = args?.timeout;
			resourceInputs["timeouts"] = args?.timeouts;
			resourceInputs["tls"] = args?.tls;
		}
		opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
		super(
			FtpConfig.__pulumiType,
			name,
			resourceInputs,
			opts,
			false /*dependency*/,
			utilities.getPackage(),
		);
	}
}

/**
 * Input properties used for looking up and filtering FtpConfig resources.
 */
export interface FtpConfigState {
	/**
	 * FTP banner message.
	 */
	banner?: pulumi.Input<string | undefined>;
	/**
	 * Maximum number of simultaneous clients (1-10000).
	 */
	clients?: pulumi.Input<number | undefined>;
	/**
	 * Chroot users to their home directory.
	 */
	defaultroot?: pulumi.Input<boolean | undefined>;
	/**
	 * Directory creation mask (umask), octal (e.g. 022).
	 */
	dirmask?: pulumi.Input<string | undefined>;
	/**
	 * File creation mask (umask), octal (e.g. 077).
	 */
	filemask?: pulumi.Input<string | undefined>;
	/**
	 * Enable FXP (File eXchange Protocol).
	 */
	fxp?: pulumi.Input<boolean | undefined>;
	/**
	 * Maximum connections per IP address (0 = unlimited, max 1000).
	 */
	ipconnections?: pulumi.Input<number | undefined>;
	/**
	 * Maximum login attempts before disconnect (1-1000).
	 */
	loginattempt?: pulumi.Input<number | undefined>;
	/**
	 * Allow only anonymous logins.
	 */
	onlyanonymous?: pulumi.Input<boolean | undefined>;
	/**
	 * Allow only local user logins.
	 */
	onlylocal?: pulumi.Input<boolean | undefined>;
	/**
	 * FTP port.
	 */
	port?: pulumi.Input<number | undefined>;
	/**
	 * Allow transfer resume.
	 */
	resume?: pulumi.Input<boolean | undefined>;
	/**
	 * Timeout in seconds for idle connections (1-10000).
	 */
	timeout?: pulumi.Input<number | undefined>;
	timeouts?: pulumi.Input<inputs.FtpConfigTimeouts | undefined>;
	/**
	 * Enable TLS for FTP connections.
	 */
	tls?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a FtpConfig resource.
 */
export interface FtpConfigArgs {
	/**
	 * FTP banner message.
	 */
	banner?: pulumi.Input<string | undefined>;
	/**
	 * Maximum number of simultaneous clients (1-10000).
	 */
	clients?: pulumi.Input<number | undefined>;
	/**
	 * Chroot users to their home directory.
	 */
	defaultroot?: pulumi.Input<boolean | undefined>;
	/**
	 * Directory creation mask (umask), octal (e.g. 022).
	 */
	dirmask?: pulumi.Input<string | undefined>;
	/**
	 * File creation mask (umask), octal (e.g. 077).
	 */
	filemask?: pulumi.Input<string | undefined>;
	/**
	 * Enable FXP (File eXchange Protocol).
	 */
	fxp?: pulumi.Input<boolean | undefined>;
	/**
	 * Maximum connections per IP address (0 = unlimited, max 1000).
	 */
	ipconnections?: pulumi.Input<number | undefined>;
	/**
	 * Maximum login attempts before disconnect (1-1000).
	 */
	loginattempt?: pulumi.Input<number | undefined>;
	/**
	 * Allow only anonymous logins.
	 */
	onlyanonymous?: pulumi.Input<boolean | undefined>;
	/**
	 * Allow only local user logins.
	 */
	onlylocal?: pulumi.Input<boolean | undefined>;
	/**
	 * FTP port.
	 */
	port?: pulumi.Input<number | undefined>;
	/**
	 * Allow transfer resume.
	 */
	resume?: pulumi.Input<boolean | undefined>;
	/**
	 * Timeout in seconds for idle connections (1-10000).
	 */
	timeout?: pulumi.Input<number | undefined>;
	timeouts?: pulumi.Input<inputs.FtpConfigTimeouts | undefined>;
	/**
	 * Enable TLS for FTP connections.
	 */
	tls?: pulumi.Input<boolean | undefined>;
}
