// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getCertificate(
	args: GetCertificateArgs,
	opts?: pulumi.InvokeOptions,
): Promise<GetCertificateResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invoke(
		"truenas:index/getCertificate:getCertificate",
		{
			name: args.name,
		},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of arguments for invoking getCertificate.
 */
export interface GetCertificateArgs {
	name: string;
}

/**
 * A collection of values returned by getCertificate.
 */
export interface GetCertificateResult {
	readonly digestAlgorithm: string;
	readonly dn: string;
	readonly expired: boolean;
	readonly id: number;
	readonly issuer: string;
	readonly keyLength: number;
	readonly keyType: string;
	readonly name: string;
	readonly san: string;
	readonly validFrom: string;
	readonly validUntil: string;
}
export function getCertificateOutput(
	args: GetCertificateOutputArgs,
	opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetCertificateResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invokeOutput(
		"truenas:index/getCertificate:getCertificate",
		{
			name: args.name,
		},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of arguments for invoking getCertificate.
 */
export interface GetCertificateOutputArgs {
	name: pulumi.Input<string>;
}
