// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getCatalog(
	opts?: pulumi.InvokeOptions,
): Promise<GetCatalogResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invoke(
		"truenas:index/getCatalog:getCatalog",
		{},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of values returned by getCatalog.
 */
export interface GetCatalogResult {
	readonly id: string;
	readonly label: string;
	readonly location: string;
	readonly preferredTrains: string[];
}
export function getCatalogOutput(
	opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetCatalogResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invokeOutput(
		"truenas:index/getCatalog:getCatalog",
		{},
		opts,
		utilities.getPackage(),
	);
}
