// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getDatasets(
	args?: GetDatasetsArgs,
	opts?: pulumi.InvokeOptions,
): Promise<GetDatasetsResult> {
	args = args || {};
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invoke(
		"truenas:index/getDatasets:getDatasets",
		{
			parentDataset: args.parentDataset,
			pool: args.pool,
		},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of arguments for invoking getDatasets.
 */
export interface GetDatasetsArgs {
	parentDataset?: string;
	pool?: string;
}

/**
 * A collection of values returned by getDatasets.
 */
export interface GetDatasetsResult {
	readonly datasets: outputs.GetDatasetsDataset[];
	/**
	 * The provider-assigned unique ID for this managed resource.
	 */
	readonly id: string;
	readonly parentDataset?: string;
	readonly pool?: string;
}
export function getDatasetsOutput(
	args?: GetDatasetsOutputArgs,
	opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetDatasetsResult> {
	args = args || {};
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invokeOutput(
		"truenas:index/getDatasets:getDatasets",
		{
			parentDataset: args.parentDataset,
			pool: args.pool,
		},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of arguments for invoking getDatasets.
 */
export interface GetDatasetsOutputArgs {
	parentDataset?: pulumi.Input<string | undefined>;
	pool?: pulumi.Input<string | undefined>;
}
