// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getKerberosRealm(
	args: GetKerberosRealmArgs,
	opts?: pulumi.InvokeOptions,
): Promise<GetKerberosRealmResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invoke(
		"truenas:index/getKerberosRealm:getKerberosRealm",
		{
			id: args.id,
		},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of arguments for invoking getKerberosRealm.
 */
export interface GetKerberosRealmArgs {
	id: number;
}

/**
 * A collection of values returned by getKerberosRealm.
 */
export interface GetKerberosRealmResult {
	readonly adminServers: string[];
	readonly id: number;
	readonly kdcs: string[];
	readonly kpasswdServers: string[];
	readonly primaryKdc: string;
	readonly realm: string;
}
export function getKerberosRealmOutput(
	args: GetKerberosRealmOutputArgs,
	opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetKerberosRealmResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invokeOutput(
		"truenas:index/getKerberosRealm:getKerberosRealm",
		{
			id: args.id,
		},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of arguments for invoking getKerberosRealm.
 */
export interface GetKerberosRealmOutputArgs {
	id: pulumi.Input<number>;
}
