// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getNetworkConfig(
	opts?: pulumi.InvokeOptions,
): Promise<GetNetworkConfigResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invoke(
		"truenas:index/getNetworkConfig:getNetworkConfig",
		{},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of values returned by getNetworkConfig.
 */
export interface GetNetworkConfigResult {
	readonly domain: string;
	readonly hostname: string;
	readonly httpproxy: string;
	/**
	 * The provider-assigned unique ID for this managed resource.
	 */
	readonly id: string;
	readonly ipv4gateway: string;
	readonly nameserver1: string;
	readonly nameserver2: string;
	readonly nameserver3: string;
}
export function getNetworkConfigOutput(
	opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetNetworkConfigResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invokeOutput(
		"truenas:index/getNetworkConfig:getNetworkConfig",
		{},
		opts,
		utilities.getPackage(),
	);
}
