// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPool(
	args?: GetPoolArgs,
	opts?: pulumi.InvokeOptions,
): Promise<GetPoolResult> {
	args = args || {};
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invoke(
		"truenas:index/getPool:getPool",
		{
			id: args.id,
			name: args.name,
		},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of arguments for invoking getPool.
 */
export interface GetPoolArgs {
	id?: number;
	name?: string;
}

/**
 * A collection of values returned by getPool.
 */
export interface GetPoolResult {
	readonly guid: string;
	readonly healthy: boolean;
	readonly id?: number;
	readonly isDecrypted: boolean;
	readonly name: string;
	readonly path: string;
	readonly status: string;
}
export function getPoolOutput(
	args?: GetPoolOutputArgs,
	opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetPoolResult> {
	args = args || {};
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invokeOutput(
		"truenas:index/getPool:getPool",
		{
			id: args.id,
			name: args.name,
		},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of arguments for invoking getPool.
 */
export interface GetPoolOutputArgs {
	id?: pulumi.Input<number | undefined>;
	name?: pulumi.Input<string | undefined>;
}
