// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPrivilege(
	args: GetPrivilegeArgs,
	opts?: pulumi.InvokeOptions,
): Promise<GetPrivilegeResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invoke(
		"truenas:index/getPrivilege:getPrivilege",
		{
			id: args.id,
		},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of arguments for invoking getPrivilege.
 */
export interface GetPrivilegeArgs {
	id: number;
}

/**
 * A collection of values returned by getPrivilege.
 */
export interface GetPrivilegeResult {
	readonly builtinName: string;
	readonly dsGroups: string[];
	readonly id: number;
	readonly localGroups: number[];
	readonly name: string;
	readonly roles: string[];
	readonly webShell: boolean;
}
export function getPrivilegeOutput(
	args: GetPrivilegeOutputArgs,
	opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetPrivilegeResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invokeOutput(
		"truenas:index/getPrivilege:getPrivilege",
		{
			id: args.id,
		},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of arguments for invoking getPrivilege.
 */
export interface GetPrivilegeOutputArgs {
	id: pulumi.Input<number>;
}
