// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getShareSmb(
	args: GetShareSmbArgs,
	opts?: pulumi.InvokeOptions,
): Promise<GetShareSmbResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invoke(
		"truenas:index/getShareSmb:getShareSmb",
		{
			id: args.id,
		},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of arguments for invoking getShareSmb.
 */
export interface GetShareSmbArgs {
	id: number;
}

/**
 * A collection of values returned by getShareSmb.
 */
export interface GetShareSmbResult {
	readonly accessBasedShareEnumeration: boolean;
	readonly browsable: boolean;
	readonly comment: string;
	readonly enabled: boolean;
	readonly id: number;
	readonly name: string;
	readonly path: string;
	readonly purpose: string;
	readonly readOnly: boolean;
}
export function getShareSmbOutput(
	args: GetShareSmbOutputArgs,
	opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetShareSmbResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invokeOutput(
		"truenas:index/getShareSmb:getShareSmb",
		{
			id: args.id,
		},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of arguments for invoking getShareSmb.
 */
export interface GetShareSmbOutputArgs {
	id: pulumi.Input<number>;
}
