// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSystemdataset(
	opts?: pulumi.InvokeOptions,
): Promise<GetSystemdatasetResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invoke(
		"truenas:index/getSystemdataset:getSystemdataset",
		{},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of values returned by getSystemdataset.
 */
export interface GetSystemdatasetResult {
	readonly basename: string;
	readonly id: string;
	readonly path: string;
	readonly pool: string;
	readonly poolSet: boolean;
	readonly uuid: string;
}
export function getSystemdatasetOutput(
	opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetSystemdatasetResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invokeOutput(
		"truenas:index/getSystemdataset:getSystemdataset",
		{},
		opts,
		utilities.getPackage(),
	);
}
