// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getShareNfs(
	args: GetShareNfsArgs,
	opts?: pulumi.InvokeOptions,
): Promise<GetShareNfsResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invoke(
		"truenas:index/getShareNfs:getShareNfs",
		{
			id: args.id,
		},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of arguments for invoking getShareNfs.
 */
export interface GetShareNfsArgs {
	id: number;
}

/**
 * A collection of values returned by getShareNfs.
 */
export interface GetShareNfsResult {
	readonly aliases: string[];
	readonly comment: string;
	readonly enabled: boolean;
	readonly hosts: string[];
	readonly id: number;
	readonly mapallGroup: string;
	readonly mapallUser: string;
	readonly maprootGroup: string;
	readonly maprootUser: string;
	readonly networks: string[];
	readonly path: string;
	readonly readOnly: boolean;
	readonly securities: string[];
}
export function getShareNfsOutput(
	args: GetShareNfsOutputArgs,
	opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetShareNfsResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invokeOutput(
		"truenas:index/getShareNfs:getShareNfs",
		{
			id: args.id,
		},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of arguments for invoking getShareNfs.
 */
export interface GetShareNfsOutputArgs {
	id: pulumi.Input<number>;
}
