// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getVm(
	args: GetVmArgs,
	opts?: pulumi.InvokeOptions,
): Promise<GetVmResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invoke(
		"truenas:index/getVm:getVm",
		{
			id: args.id,
		},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of arguments for invoking getVm.
 */
export interface GetVmArgs {
	id: number;
}

/**
 * A collection of values returned by getVm.
 */
export interface GetVmResult {
	readonly autostart: boolean;
	readonly bootloader: string;
	readonly bootloaderOvmf: string;
	readonly cores: number;
	readonly cpuMode: string;
	readonly cpuModel: string;
	readonly description: string;
	readonly enableSecureBoot: boolean;
	readonly id: number;
	readonly memory: number;
	readonly minMemory: number;
	readonly name: string;
	readonly shutdownTimeout: number;
	readonly state: string;
	readonly threads: number;
	readonly time: string;
	readonly uuid: string;
	readonly vcpus: number;
}
export function getVmOutput(
	args: GetVmOutputArgs,
	opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetVmResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invokeOutput(
		"truenas:index/getVm:getVm",
		{
			id: args.id,
		},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of arguments for invoking getVm.
 */
export interface GetVmOutputArgs {
	id: pulumi.Input<number>;
}
