// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class IscsiTarget extends pulumi.CustomResource {
	/**
	 * Get an existing IscsiTarget resource's state with the given name, ID, and optional extra
	 * properties used to qualify the lookup.
	 *
	 * @param name The _unique_ name of the resulting resource.
	 * @param id The _unique_ provider ID of the resource to lookup.
	 * @param state Any extra arguments used during the lookup.
	 * @param opts Optional settings to control the behavior of the CustomResource.
	 */
	public static get(
		name: string,
		id: pulumi.Input<pulumi.ID>,
		state?: IscsiTargetState,
		opts?: pulumi.CustomResourceOptions,
	): IscsiTarget {
		return new IscsiTarget(name, <any>state, { ...opts, id: id });
	}

	/** @internal */
	public static readonly __pulumiType = "truenas:index/iscsiTarget:IscsiTarget";

	/**
	 * Returns true if the given object is an instance of IscsiTarget.  This is designed to work even
	 * when multiple copies of the Pulumi SDK have been loaded into the same process.
	 */
	public static isInstance(obj: any): obj is IscsiTarget {
		if (obj === undefined || obj === null) {
			return false;
		}
		return obj["__pulumiType"] === IscsiTarget.__pulumiType;
	}

	/**
	 * An optional alias for the target.
	 */
	public declare readonly alias: pulumi.Output<string>;
	/**
	 * Target groups linking portals and initiators.
	 */
	public declare readonly groups: pulumi.Output<
		outputs.IscsiTargetGroup[] | undefined
	>;
	/**
	 * The target mode (ISCSI, FC, BOTH).
	 */
	public declare readonly mode: pulumi.Output<string>;
	/**
	 * The iSCSI target name (IQN suffix). Lowercase alphanumeric with dots, hyphens, colons.
	 */
	public declare readonly name: pulumi.Output<string>;
	public declare readonly timeouts: pulumi.Output<
		outputs.IscsiTargetTimeouts | undefined
	>;

	/**
	 * Create a IscsiTarget resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 * @param opts A bag of options that control this resource's behavior.
	 */
	constructor(
		name: string,
		args?: IscsiTargetArgs,
		opts?: pulumi.CustomResourceOptions,
	);
	constructor(
		name: string,
		argsOrState?: IscsiTargetArgs | IscsiTargetState,
		opts?: pulumi.CustomResourceOptions,
	) {
		const resourceInputs: pulumi.Inputs = {};
		opts = opts || {};
		if (opts.id) {
			const state = argsOrState as IscsiTargetState | undefined;
			resourceInputs["alias"] = state?.alias;
			resourceInputs["groups"] = state?.groups;
			resourceInputs["mode"] = state?.mode;
			resourceInputs["name"] = state?.name;
			resourceInputs["timeouts"] = state?.timeouts;
		} else {
			const args = argsOrState as IscsiTargetArgs | undefined;
			resourceInputs["alias"] = args?.alias;
			resourceInputs["groups"] = args?.groups;
			resourceInputs["mode"] = args?.mode;
			resourceInputs["name"] = args?.name;
			resourceInputs["timeouts"] = args?.timeouts;
		}
		opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
		super(
			IscsiTarget.__pulumiType,
			name,
			resourceInputs,
			opts,
			false /*dependency*/,
			utilities.getPackage(),
		);
	}
}

/**
 * Input properties used for looking up and filtering IscsiTarget resources.
 */
export interface IscsiTargetState {
	/**
	 * An optional alias for the target.
	 */
	alias?: pulumi.Input<string | undefined>;
	/**
	 * Target groups linking portals and initiators.
	 */
	groups?: pulumi.Input<pulumi.Input<inputs.IscsiTargetGroup>[] | undefined>;
	/**
	 * The target mode (ISCSI, FC, BOTH).
	 */
	mode?: pulumi.Input<string | undefined>;
	/**
	 * The iSCSI target name (IQN suffix). Lowercase alphanumeric with dots, hyphens, colons.
	 */
	name?: pulumi.Input<string | undefined>;
	timeouts?: pulumi.Input<inputs.IscsiTargetTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a IscsiTarget resource.
 */
export interface IscsiTargetArgs {
	/**
	 * An optional alias for the target.
	 */
	alias?: pulumi.Input<string | undefined>;
	/**
	 * Target groups linking portals and initiators.
	 */
	groups?: pulumi.Input<pulumi.Input<inputs.IscsiTargetGroup>[] | undefined>;
	/**
	 * The target mode (ISCSI, FC, BOTH).
	 */
	mode?: pulumi.Input<string | undefined>;
	/**
	 * The iSCSI target name (IQN suffix). Lowercase alphanumeric with dots, hyphens, colons.
	 */
	name?: pulumi.Input<string | undefined>;
	timeouts?: pulumi.Input<inputs.IscsiTargetTimeouts | undefined>;
}
