// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class KerberosRealm extends pulumi.CustomResource {
	/**
	 * Get an existing KerberosRealm resource's state with the given name, ID, and optional extra
	 * properties used to qualify the lookup.
	 *
	 * @param name The _unique_ name of the resulting resource.
	 * @param id The _unique_ provider ID of the resource to lookup.
	 * @param state Any extra arguments used during the lookup.
	 * @param opts Optional settings to control the behavior of the CustomResource.
	 */
	public static get(
		name: string,
		id: pulumi.Input<pulumi.ID>,
		state?: KerberosRealmState,
		opts?: pulumi.CustomResourceOptions,
	): KerberosRealm {
		return new KerberosRealm(name, <any>state, { ...opts, id: id });
	}

	/** @internal */
	public static readonly __pulumiType =
		"truenas:index/kerberosRealm:KerberosRealm";

	/**
	 * Returns true if the given object is an instance of KerberosRealm.  This is designed to work even
	 * when multiple copies of the Pulumi SDK have been loaded into the same process.
	 */
	public static isInstance(obj: any): obj is KerberosRealm {
		if (obj === undefined || obj === null) {
			return false;
		}
		return obj["__pulumiType"] === KerberosRealm.__pulumiType;
	}

	/**
	 * List of Kerberos admin server hostnames.
	 */
	public declare readonly adminServers: pulumi.Output<string[]>;
	/**
	 * List of Kerberos KDC hostnames. If empty, libraries use DNS SRV lookups.
	 */
	public declare readonly kdcs: pulumi.Output<string[]>;
	/**
	 * List of Kerberos kpasswd server hostnames.
	 */
	public declare readonly kpasswdServers: pulumi.Output<string[]>;
	/**
	 * Optional primary/master KDC hostname. Used as a fallback when the machine password is invalid.
	 */
	public declare readonly primaryKdc: pulumi.Output<string | undefined>;
	/**
	 * Kerberos realm name (e.g. EXAMPLE.COM).
	 */
	public declare readonly realm: pulumi.Output<string>;
	public declare readonly timeouts: pulumi.Output<
		outputs.KerberosRealmTimeouts | undefined
	>;

	/**
	 * Create a KerberosRealm resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 * @param opts A bag of options that control this resource's behavior.
	 */
	constructor(
		name: string,
		args: KerberosRealmArgs,
		opts?: pulumi.CustomResourceOptions,
	);
	constructor(
		name: string,
		argsOrState?: KerberosRealmArgs | KerberosRealmState,
		opts?: pulumi.CustomResourceOptions,
	) {
		const resourceInputs: pulumi.Inputs = {};
		opts = opts || {};
		if (opts.id) {
			const state = argsOrState as KerberosRealmState | undefined;
			resourceInputs["adminServers"] = state?.adminServers;
			resourceInputs["kdcs"] = state?.kdcs;
			resourceInputs["kpasswdServers"] = state?.kpasswdServers;
			resourceInputs["primaryKdc"] = state?.primaryKdc;
			resourceInputs["realm"] = state?.realm;
			resourceInputs["timeouts"] = state?.timeouts;
		} else {
			const args = argsOrState as KerberosRealmArgs | undefined;
			if (args?.realm === undefined && !opts.urn) {
				throw new Error("Missing required property 'realm'");
			}
			resourceInputs["adminServers"] = args?.adminServers;
			resourceInputs["kdcs"] = args?.kdcs;
			resourceInputs["kpasswdServers"] = args?.kpasswdServers;
			resourceInputs["primaryKdc"] = args?.primaryKdc;
			resourceInputs["realm"] = args?.realm;
			resourceInputs["timeouts"] = args?.timeouts;
		}
		opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
		super(
			KerberosRealm.__pulumiType,
			name,
			resourceInputs,
			opts,
			false /*dependency*/,
			utilities.getPackage(),
		);
	}
}

/**
 * Input properties used for looking up and filtering KerberosRealm resources.
 */
export interface KerberosRealmState {
	/**
	 * List of Kerberos admin server hostnames.
	 */
	adminServers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
	/**
	 * List of Kerberos KDC hostnames. If empty, libraries use DNS SRV lookups.
	 */
	kdcs?: pulumi.Input<pulumi.Input<string>[] | undefined>;
	/**
	 * List of Kerberos kpasswd server hostnames.
	 */
	kpasswdServers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
	/**
	 * Optional primary/master KDC hostname. Used as a fallback when the machine password is invalid.
	 */
	primaryKdc?: pulumi.Input<string | undefined>;
	/**
	 * Kerberos realm name (e.g. EXAMPLE.COM).
	 */
	realm?: pulumi.Input<string | undefined>;
	timeouts?: pulumi.Input<inputs.KerberosRealmTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a KerberosRealm resource.
 */
export interface KerberosRealmArgs {
	/**
	 * List of Kerberos admin server hostnames.
	 */
	adminServers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
	/**
	 * List of Kerberos KDC hostnames. If empty, libraries use DNS SRV lookups.
	 */
	kdcs?: pulumi.Input<pulumi.Input<string>[] | undefined>;
	/**
	 * List of Kerberos kpasswd server hostnames.
	 */
	kpasswdServers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
	/**
	 * Optional primary/master KDC hostname. Used as a fallback when the machine password is invalid.
	 */
	primaryKdc?: pulumi.Input<string | undefined>;
	/**
	 * Kerberos realm name (e.g. EXAMPLE.COM).
	 */
	realm: pulumi.Input<string>;
	timeouts?: pulumi.Input<inputs.KerberosRealmTimeouts | undefined>;
}
