// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class KmipConfig extends pulumi.CustomResource {
	/**
	 * Get an existing KmipConfig resource's state with the given name, ID, and optional extra
	 * properties used to qualify the lookup.
	 *
	 * @param name The _unique_ name of the resulting resource.
	 * @param id The _unique_ provider ID of the resource to lookup.
	 * @param state Any extra arguments used during the lookup.
	 * @param opts Optional settings to control the behavior of the CustomResource.
	 */
	public static get(
		name: string,
		id: pulumi.Input<pulumi.ID>,
		state?: KmipConfigState,
		opts?: pulumi.CustomResourceOptions,
	): KmipConfig {
		return new KmipConfig(name, <any>state, { ...opts, id: id });
	}

	/** @internal */
	public static readonly __pulumiType = "truenas:index/kmipConfig:KmipConfig";

	/**
	 * Returns true if the given object is an instance of KmipConfig.  This is designed to work even
	 * when multiple copies of the Pulumi SDK have been loaded into the same process.
	 */
	public static isInstance(obj: any): obj is KmipConfig {
		if (obj === undefined || obj === null) {
			return false;
		}
		return obj["__pulumiType"] === KmipConfig.__pulumiType;
	}

	/**
	 * ID of the client certificate used for KMIP authentication (0 = none).
	 */
	public declare readonly certificate: pulumi.Output<number>;
	/**
	 * ID of the CA used to verify the KMIP server (0 = none).
	 */
	public declare readonly certificateAuthority: pulumi.Output<number>;
	/**
	 * Flag indicating the KMIP server endpoint is being changed.
	 */
	public declare readonly changeServer: pulumi.Output<boolean>;
	/**
	 * Whether KMIP functionality is enabled.
	 */
	public declare readonly enabled: pulumi.Output<boolean>;
	/**
	 * Force clear existing keys when disabling KMIP.
	 */
	public declare readonly forceClear: pulumi.Output<boolean>;
	/**
	 * Use KMIP to manage Self-Encrypting Drive keys.
	 */
	public declare readonly manageSedDisks: pulumi.Output<boolean>;
	/**
	 * Use KMIP to manage ZFS encryption keys.
	 */
	public declare readonly manageZfsKeys: pulumi.Output<boolean>;
	/**
	 * TCP port for the KMIP server connection.
	 */
	public declare readonly port: pulumi.Output<number>;
	/**
	 * Hostname or IP of the KMIP server. Empty string disables.
	 */
	public declare readonly server: pulumi.Output<string>;
	/**
	 * SSL/TLS protocol version. One of PROTOCOL_TLSv1, PROTOCOL_TLSv1_1, PROTOCOL_TLSv1_2.
	 */
	public declare readonly sslVersion: pulumi.Output<string>;
	public declare readonly timeouts: pulumi.Output<
		outputs.KmipConfigTimeouts | undefined
	>;
	/**
	 * Validate the KMIP server connection before saving.
	 */
	public declare readonly validate: pulumi.Output<boolean>;

	/**
	 * Create a KmipConfig resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 * @param opts A bag of options that control this resource's behavior.
	 */
	constructor(
		name: string,
		args?: KmipConfigArgs,
		opts?: pulumi.CustomResourceOptions,
	);
	constructor(
		name: string,
		argsOrState?: KmipConfigArgs | KmipConfigState,
		opts?: pulumi.CustomResourceOptions,
	) {
		const resourceInputs: pulumi.Inputs = {};
		opts = opts || {};
		if (opts.id) {
			const state = argsOrState as KmipConfigState | undefined;
			resourceInputs["certificate"] = state?.certificate;
			resourceInputs["certificateAuthority"] = state?.certificateAuthority;
			resourceInputs["changeServer"] = state?.changeServer;
			resourceInputs["enabled"] = state?.enabled;
			resourceInputs["forceClear"] = state?.forceClear;
			resourceInputs["manageSedDisks"] = state?.manageSedDisks;
			resourceInputs["manageZfsKeys"] = state?.manageZfsKeys;
			resourceInputs["port"] = state?.port;
			resourceInputs["server"] = state?.server;
			resourceInputs["sslVersion"] = state?.sslVersion;
			resourceInputs["timeouts"] = state?.timeouts;
			resourceInputs["validate"] = state?.validate;
		} else {
			const args = argsOrState as KmipConfigArgs | undefined;
			resourceInputs["certificate"] = args?.certificate;
			resourceInputs["certificateAuthority"] = args?.certificateAuthority;
			resourceInputs["changeServer"] = args?.changeServer;
			resourceInputs["enabled"] = args?.enabled;
			resourceInputs["forceClear"] = args?.forceClear;
			resourceInputs["manageSedDisks"] = args?.manageSedDisks;
			resourceInputs["manageZfsKeys"] = args?.manageZfsKeys;
			resourceInputs["port"] = args?.port;
			resourceInputs["server"] = args?.server;
			resourceInputs["sslVersion"] = args?.sslVersion;
			resourceInputs["timeouts"] = args?.timeouts;
			resourceInputs["validate"] = args?.validate;
		}
		opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
		super(
			KmipConfig.__pulumiType,
			name,
			resourceInputs,
			opts,
			false /*dependency*/,
			utilities.getPackage(),
		);
	}
}

/**
 * Input properties used for looking up and filtering KmipConfig resources.
 */
export interface KmipConfigState {
	/**
	 * ID of the client certificate used for KMIP authentication (0 = none).
	 */
	certificate?: pulumi.Input<number | undefined>;
	/**
	 * ID of the CA used to verify the KMIP server (0 = none).
	 */
	certificateAuthority?: pulumi.Input<number | undefined>;
	/**
	 * Flag indicating the KMIP server endpoint is being changed.
	 */
	changeServer?: pulumi.Input<boolean | undefined>;
	/**
	 * Whether KMIP functionality is enabled.
	 */
	enabled?: pulumi.Input<boolean | undefined>;
	/**
	 * Force clear existing keys when disabling KMIP.
	 */
	forceClear?: pulumi.Input<boolean | undefined>;
	/**
	 * Use KMIP to manage Self-Encrypting Drive keys.
	 */
	manageSedDisks?: pulumi.Input<boolean | undefined>;
	/**
	 * Use KMIP to manage ZFS encryption keys.
	 */
	manageZfsKeys?: pulumi.Input<boolean | undefined>;
	/**
	 * TCP port for the KMIP server connection.
	 */
	port?: pulumi.Input<number | undefined>;
	/**
	 * Hostname or IP of the KMIP server. Empty string disables.
	 */
	server?: pulumi.Input<string | undefined>;
	/**
	 * SSL/TLS protocol version. One of PROTOCOL_TLSv1, PROTOCOL_TLSv1_1, PROTOCOL_TLSv1_2.
	 */
	sslVersion?: pulumi.Input<string | undefined>;
	timeouts?: pulumi.Input<inputs.KmipConfigTimeouts | undefined>;
	/**
	 * Validate the KMIP server connection before saving.
	 */
	validate?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a KmipConfig resource.
 */
export interface KmipConfigArgs {
	/**
	 * ID of the client certificate used for KMIP authentication (0 = none).
	 */
	certificate?: pulumi.Input<number | undefined>;
	/**
	 * ID of the CA used to verify the KMIP server (0 = none).
	 */
	certificateAuthority?: pulumi.Input<number | undefined>;
	/**
	 * Flag indicating the KMIP server endpoint is being changed.
	 */
	changeServer?: pulumi.Input<boolean | undefined>;
	/**
	 * Whether KMIP functionality is enabled.
	 */
	enabled?: pulumi.Input<boolean | undefined>;
	/**
	 * Force clear existing keys when disabling KMIP.
	 */
	forceClear?: pulumi.Input<boolean | undefined>;
	/**
	 * Use KMIP to manage Self-Encrypting Drive keys.
	 */
	manageSedDisks?: pulumi.Input<boolean | undefined>;
	/**
	 * Use KMIP to manage ZFS encryption keys.
	 */
	manageZfsKeys?: pulumi.Input<boolean | undefined>;
	/**
	 * TCP port for the KMIP server connection.
	 */
	port?: pulumi.Input<number | undefined>;
	/**
	 * Hostname or IP of the KMIP server. Empty string disables.
	 */
	server?: pulumi.Input<string | undefined>;
	/**
	 * SSL/TLS protocol version. One of PROTOCOL_TLSv1, PROTOCOL_TLSv1_1, PROTOCOL_TLSv1_2.
	 */
	sslVersion?: pulumi.Input<string | undefined>;
	timeouts?: pulumi.Input<inputs.KmipConfigTimeouts | undefined>;
	/**
	 * Validate the KMIP server connection before saving.
	 */
	validate?: pulumi.Input<boolean | undefined>;
}
