// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class NetworkInterface extends pulumi.CustomResource {
	/**
	 * Get an existing NetworkInterface resource's state with the given name, ID, and optional extra
	 * properties used to qualify the lookup.
	 *
	 * @param name The _unique_ name of the resulting resource.
	 * @param id The _unique_ provider ID of the resource to lookup.
	 * @param state Any extra arguments used during the lookup.
	 * @param opts Optional settings to control the behavior of the CustomResource.
	 */
	public static get(
		name: string,
		id: pulumi.Input<pulumi.ID>,
		state?: NetworkInterfaceState,
		opts?: pulumi.CustomResourceOptions,
	): NetworkInterface {
		return new NetworkInterface(name, <any>state, { ...opts, id: id });
	}

	/** @internal */
	public static readonly __pulumiType =
		"truenas:index/networkInterface:NetworkInterface";

	/**
	 * Returns true if the given object is an instance of NetworkInterface.  This is designed to work even
	 * when multiple copies of the Pulumi SDK have been loaded into the same process.
	 */
	public static isInstance(obj: any): obj is NetworkInterface {
		if (obj === undefined || obj === null) {
			return false;
		}
		return obj["__pulumiType"] === NetworkInterface.__pulumiType;
	}

	/**
	 * List of IP address aliases to configure on the interface.
	 */
	public declare readonly aliases: pulumi.Output<
		outputs.NetworkInterfaceAlias[]
	>;
	/**
	 * List of interfaces to add as members of this bridge. Only valid for type=BRIDGE.
	 */
	public declare readonly bridgeMembers: pulumi.Output<string[]>;
	/**
	 * Human-readable description of the interface.
	 */
	public declare readonly description: pulumi.Output<string>;
	/**
	 * Enable IPv4 DHCP for automatic IP address assignment.
	 */
	public declare readonly ipv4Dhcp: pulumi.Output<boolean>;
	/**
	 * Enable IPv6 autoconfiguration.
	 */
	public declare readonly ipv6Auto: pulumi.Output<boolean>;
	/**
	 * List of interface names in the link aggregation group. Only valid for type=LINK_AGGREGATION.
	 */
	public declare readonly lagPorts: pulumi.Output<string[]>;
	/**
	 * Link aggregation protocol: LACP, FAILOVER, LOADBALANCE, ROUNDROBIN, NONE. Only valid for type=LINK_AGGREGATION.
	 */
	public declare readonly lagProtocol: pulumi.Output<string>;
	/**
	 * Maximum transmission unit (68-9216 bytes).
	 */
	public declare readonly mtu: pulumi.Output<number>;
	/**
	 * The interface name. If not provided, TrueNAS auto-generates one based on type (e.g. br0, bond1, vlan0).
	 */
	public declare readonly name: pulumi.Output<string>;
	/**
	 * Commit changes with a rollback safety window (defaults to true). TrueNAS reverts the change automatically unless it is checked in within 60 seconds; the provider sends the checkin immediately after a successful commit. When false, changes are applied immediately without a rollback timer. Disabling rollback is faster but riskier: a bad change that breaks networking may make the interface permanently unreachable via the management network.
	 */
	public declare readonly rollback: pulumi.Output<boolean>;
	public declare readonly timeouts: pulumi.Output<
		outputs.NetworkInterfaceTimeouts | undefined
	>;
	/**
	 * The interface type: PHYSICAL, BRIDGE, LINK_AGGREGATION, or VLAN. PHYSICAL adopts an existing hardware NIC (identified by name) instead of creating one.
	 */
	public declare readonly type: pulumi.Output<string>;
	/**
	 * Parent interface name for VLAN configuration. Only valid for type=VLAN.
	 */
	public declare readonly vlanParentInterface: pulumi.Output<string>;
	/**
	 * Priority Code Point for VLAN traffic (0-7). Only valid for type=VLAN.
	 */
	public declare readonly vlanPcp: pulumi.Output<number>;
	/**
	 * VLAN tag number (1-4094). Only valid for type=VLAN.
	 */
	public declare readonly vlanTag: pulumi.Output<number>;

	/**
	 * Create a NetworkInterface resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 * @param opts A bag of options that control this resource's behavior.
	 */
	constructor(
		name: string,
		args: NetworkInterfaceArgs,
		opts?: pulumi.CustomResourceOptions,
	);
	constructor(
		name: string,
		argsOrState?: NetworkInterfaceArgs | NetworkInterfaceState,
		opts?: pulumi.CustomResourceOptions,
	) {
		const resourceInputs: pulumi.Inputs = {};
		opts = opts || {};
		if (opts.id) {
			const state = argsOrState as NetworkInterfaceState | undefined;
			resourceInputs["aliases"] = state?.aliases;
			resourceInputs["bridgeMembers"] = state?.bridgeMembers;
			resourceInputs["description"] = state?.description;
			resourceInputs["ipv4Dhcp"] = state?.ipv4Dhcp;
			resourceInputs["ipv6Auto"] = state?.ipv6Auto;
			resourceInputs["lagPorts"] = state?.lagPorts;
			resourceInputs["lagProtocol"] = state?.lagProtocol;
			resourceInputs["mtu"] = state?.mtu;
			resourceInputs["name"] = state?.name;
			resourceInputs["rollback"] = state?.rollback;
			resourceInputs["timeouts"] = state?.timeouts;
			resourceInputs["type"] = state?.type;
			resourceInputs["vlanParentInterface"] = state?.vlanParentInterface;
			resourceInputs["vlanPcp"] = state?.vlanPcp;
			resourceInputs["vlanTag"] = state?.vlanTag;
		} else {
			const args = argsOrState as NetworkInterfaceArgs | undefined;
			if (args?.type === undefined && !opts.urn) {
				throw new Error("Missing required property 'type'");
			}
			resourceInputs["aliases"] = args?.aliases;
			resourceInputs["bridgeMembers"] = args?.bridgeMembers;
			resourceInputs["description"] = args?.description;
			resourceInputs["ipv4Dhcp"] = args?.ipv4Dhcp;
			resourceInputs["ipv6Auto"] = args?.ipv6Auto;
			resourceInputs["lagPorts"] = args?.lagPorts;
			resourceInputs["lagProtocol"] = args?.lagProtocol;
			resourceInputs["mtu"] = args?.mtu;
			resourceInputs["name"] = args?.name;
			resourceInputs["rollback"] = args?.rollback;
			resourceInputs["timeouts"] = args?.timeouts;
			resourceInputs["type"] = args?.type;
			resourceInputs["vlanParentInterface"] = args?.vlanParentInterface;
			resourceInputs["vlanPcp"] = args?.vlanPcp;
			resourceInputs["vlanTag"] = args?.vlanTag;
		}
		opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
		super(
			NetworkInterface.__pulumiType,
			name,
			resourceInputs,
			opts,
			false /*dependency*/,
			utilities.getPackage(),
		);
	}
}

/**
 * Input properties used for looking up and filtering NetworkInterface resources.
 */
export interface NetworkInterfaceState {
	/**
	 * List of IP address aliases to configure on the interface.
	 */
	aliases?: pulumi.Input<
		pulumi.Input<inputs.NetworkInterfaceAlias>[] | undefined
	>;
	/**
	 * List of interfaces to add as members of this bridge. Only valid for type=BRIDGE.
	 */
	bridgeMembers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
	/**
	 * Human-readable description of the interface.
	 */
	description?: pulumi.Input<string | undefined>;
	/**
	 * Enable IPv4 DHCP for automatic IP address assignment.
	 */
	ipv4Dhcp?: pulumi.Input<boolean | undefined>;
	/**
	 * Enable IPv6 autoconfiguration.
	 */
	ipv6Auto?: pulumi.Input<boolean | undefined>;
	/**
	 * List of interface names in the link aggregation group. Only valid for type=LINK_AGGREGATION.
	 */
	lagPorts?: pulumi.Input<pulumi.Input<string>[] | undefined>;
	/**
	 * Link aggregation protocol: LACP, FAILOVER, LOADBALANCE, ROUNDROBIN, NONE. Only valid for type=LINK_AGGREGATION.
	 */
	lagProtocol?: pulumi.Input<string | undefined>;
	/**
	 * Maximum transmission unit (68-9216 bytes).
	 */
	mtu?: pulumi.Input<number | undefined>;
	/**
	 * The interface name. If not provided, TrueNAS auto-generates one based on type (e.g. br0, bond1, vlan0).
	 */
	name?: pulumi.Input<string | undefined>;
	/**
	 * Commit changes with a rollback safety window (defaults to true). TrueNAS reverts the change automatically unless it is checked in within 60 seconds; the provider sends the checkin immediately after a successful commit. When false, changes are applied immediately without a rollback timer. Disabling rollback is faster but riskier: a bad change that breaks networking may make the interface permanently unreachable via the management network.
	 */
	rollback?: pulumi.Input<boolean | undefined>;
	timeouts?: pulumi.Input<inputs.NetworkInterfaceTimeouts | undefined>;
	/**
	 * The interface type: PHYSICAL, BRIDGE, LINK_AGGREGATION, or VLAN. PHYSICAL adopts an existing hardware NIC (identified by name) instead of creating one.
	 */
	type?: pulumi.Input<string | undefined>;
	/**
	 * Parent interface name for VLAN configuration. Only valid for type=VLAN.
	 */
	vlanParentInterface?: pulumi.Input<string | undefined>;
	/**
	 * Priority Code Point for VLAN traffic (0-7). Only valid for type=VLAN.
	 */
	vlanPcp?: pulumi.Input<number | undefined>;
	/**
	 * VLAN tag number (1-4094). Only valid for type=VLAN.
	 */
	vlanTag?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a NetworkInterface resource.
 */
export interface NetworkInterfaceArgs {
	/**
	 * List of IP address aliases to configure on the interface.
	 */
	aliases?: pulumi.Input<
		pulumi.Input<inputs.NetworkInterfaceAlias>[] | undefined
	>;
	/**
	 * List of interfaces to add as members of this bridge. Only valid for type=BRIDGE.
	 */
	bridgeMembers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
	/**
	 * Human-readable description of the interface.
	 */
	description?: pulumi.Input<string | undefined>;
	/**
	 * Enable IPv4 DHCP for automatic IP address assignment.
	 */
	ipv4Dhcp?: pulumi.Input<boolean | undefined>;
	/**
	 * Enable IPv6 autoconfiguration.
	 */
	ipv6Auto?: pulumi.Input<boolean | undefined>;
	/**
	 * List of interface names in the link aggregation group. Only valid for type=LINK_AGGREGATION.
	 */
	lagPorts?: pulumi.Input<pulumi.Input<string>[] | undefined>;
	/**
	 * Link aggregation protocol: LACP, FAILOVER, LOADBALANCE, ROUNDROBIN, NONE. Only valid for type=LINK_AGGREGATION.
	 */
	lagProtocol?: pulumi.Input<string | undefined>;
	/**
	 * Maximum transmission unit (68-9216 bytes).
	 */
	mtu?: pulumi.Input<number | undefined>;
	/**
	 * The interface name. If not provided, TrueNAS auto-generates one based on type (e.g. br0, bond1, vlan0).
	 */
	name?: pulumi.Input<string | undefined>;
	/**
	 * Commit changes with a rollback safety window (defaults to true). TrueNAS reverts the change automatically unless it is checked in within 60 seconds; the provider sends the checkin immediately after a successful commit. When false, changes are applied immediately without a rollback timer. Disabling rollback is faster but riskier: a bad change that breaks networking may make the interface permanently unreachable via the management network.
	 */
	rollback?: pulumi.Input<boolean | undefined>;
	timeouts?: pulumi.Input<inputs.NetworkInterfaceTimeouts | undefined>;
	/**
	 * The interface type: PHYSICAL, BRIDGE, LINK_AGGREGATION, or VLAN. PHYSICAL adopts an existing hardware NIC (identified by name) instead of creating one.
	 */
	type: pulumi.Input<string>;
	/**
	 * Parent interface name for VLAN configuration. Only valid for type=VLAN.
	 */
	vlanParentInterface?: pulumi.Input<string | undefined>;
	/**
	 * Priority Code Point for VLAN traffic (0-7). Only valid for type=VLAN.
	 */
	vlanPcp?: pulumi.Input<number | undefined>;
	/**
	 * VLAN tag number (1-4094). Only valid for type=VLAN.
	 */
	vlanTag?: pulumi.Input<number | undefined>;
}
