// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class NvmetPort extends pulumi.CustomResource {
	/**
	 * Get an existing NvmetPort resource's state with the given name, ID, and optional extra
	 * properties used to qualify the lookup.
	 *
	 * @param name The _unique_ name of the resulting resource.
	 * @param id The _unique_ provider ID of the resource to lookup.
	 * @param state Any extra arguments used during the lookup.
	 * @param opts Optional settings to control the behavior of the CustomResource.
	 */
	public static get(
		name: string,
		id: pulumi.Input<pulumi.ID>,
		state?: NvmetPortState,
		opts?: pulumi.CustomResourceOptions,
	): NvmetPort {
		return new NvmetPort(name, <any>state, { ...opts, id: id });
	}

	/** @internal */
	public static readonly __pulumiType = "truenas:index/nvmetPort:NvmetPort";

	/**
	 * Returns true if the given object is an instance of NvmetPort.  This is designed to work even
	 * when multiple copies of the Pulumi SDK have been loaded into the same process.
	 */
	public static isInstance(obj: any): obj is NvmetPort {
		if (obj === undefined || obj === null) {
			return false;
		}
		return obj["__pulumiType"] === NvmetPort.__pulumiType;
	}

	/**
	 * Transport address. For TCP/RDMA, an IPv4/IPv6 address. For FC, a fabric-specific address.
	 */
	public declare readonly addrTraddr: pulumi.Output<string>;
	/**
	 * Transport service ID. For TCP/RDMA, the port number (default 4420). Not used for FC.
	 */
	public declare readonly addrTrsvcid: pulumi.Output<number>;
	/**
	 * Fabric transport technology: TCP, RDMA, or FC.
	 */
	public declare readonly addrTrtype: pulumi.Output<string>;
	/**
	 * Whether the port is enabled.
	 */
	public declare readonly enabled: pulumi.Output<boolean>;
	/**
	 * Internal port index.
	 */
	public /*out*/ declare readonly index: pulumi.Output<number>;
	/**
	 * Maximum size for inline data transfers in bytes (0-1048576).
	 */
	public declare readonly inlineDataSize: pulumi.Output<number | undefined>;
	/**
	 * Maximum number of queue entries (1-65535).
	 */
	public declare readonly maxQueueSize: pulumi.Output<number | undefined>;
	/**
	 * Whether Protection Information (PI) is enabled.
	 */
	public declare readonly piEnable: pulumi.Output<boolean | undefined>;
	public declare readonly timeouts: pulumi.Output<
		outputs.NvmetPortTimeouts | undefined
	>;

	/**
	 * Create a NvmetPort resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 * @param opts A bag of options that control this resource's behavior.
	 */
	constructor(
		name: string,
		args: NvmetPortArgs,
		opts?: pulumi.CustomResourceOptions,
	);
	constructor(
		name: string,
		argsOrState?: NvmetPortArgs | NvmetPortState,
		opts?: pulumi.CustomResourceOptions,
	) {
		const resourceInputs: pulumi.Inputs = {};
		opts = opts || {};
		if (opts.id) {
			const state = argsOrState as NvmetPortState | undefined;
			resourceInputs["addrTraddr"] = state?.addrTraddr;
			resourceInputs["addrTrsvcid"] = state?.addrTrsvcid;
			resourceInputs["addrTrtype"] = state?.addrTrtype;
			resourceInputs["enabled"] = state?.enabled;
			resourceInputs["index"] = state?.index;
			resourceInputs["inlineDataSize"] = state?.inlineDataSize;
			resourceInputs["maxQueueSize"] = state?.maxQueueSize;
			resourceInputs["piEnable"] = state?.piEnable;
			resourceInputs["timeouts"] = state?.timeouts;
		} else {
			const args = argsOrState as NvmetPortArgs | undefined;
			if (args?.addrTraddr === undefined && !opts.urn) {
				throw new Error("Missing required property 'addrTraddr'");
			}
			if (args?.addrTrtype === undefined && !opts.urn) {
				throw new Error("Missing required property 'addrTrtype'");
			}
			resourceInputs["addrTraddr"] = args?.addrTraddr;
			resourceInputs["addrTrsvcid"] = args?.addrTrsvcid;
			resourceInputs["addrTrtype"] = args?.addrTrtype;
			resourceInputs["enabled"] = args?.enabled;
			resourceInputs["inlineDataSize"] = args?.inlineDataSize;
			resourceInputs["maxQueueSize"] = args?.maxQueueSize;
			resourceInputs["piEnable"] = args?.piEnable;
			resourceInputs["timeouts"] = args?.timeouts;
			resourceInputs["index"] = undefined /*out*/;
		}
		opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
		super(
			NvmetPort.__pulumiType,
			name,
			resourceInputs,
			opts,
			false /*dependency*/,
			utilities.getPackage(),
		);
	}
}

/**
 * Input properties used for looking up and filtering NvmetPort resources.
 */
export interface NvmetPortState {
	/**
	 * Transport address. For TCP/RDMA, an IPv4/IPv6 address. For FC, a fabric-specific address.
	 */
	addrTraddr?: pulumi.Input<string | undefined>;
	/**
	 * Transport service ID. For TCP/RDMA, the port number (default 4420). Not used for FC.
	 */
	addrTrsvcid?: pulumi.Input<number | undefined>;
	/**
	 * Fabric transport technology: TCP, RDMA, or FC.
	 */
	addrTrtype?: pulumi.Input<string | undefined>;
	/**
	 * Whether the port is enabled.
	 */
	enabled?: pulumi.Input<boolean | undefined>;
	/**
	 * Internal port index.
	 */
	index?: pulumi.Input<number | undefined>;
	/**
	 * Maximum size for inline data transfers in bytes (0-1048576).
	 */
	inlineDataSize?: pulumi.Input<number | undefined>;
	/**
	 * Maximum number of queue entries (1-65535).
	 */
	maxQueueSize?: pulumi.Input<number | undefined>;
	/**
	 * Whether Protection Information (PI) is enabled.
	 */
	piEnable?: pulumi.Input<boolean | undefined>;
	timeouts?: pulumi.Input<inputs.NvmetPortTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a NvmetPort resource.
 */
export interface NvmetPortArgs {
	/**
	 * Transport address. For TCP/RDMA, an IPv4/IPv6 address. For FC, a fabric-specific address.
	 */
	addrTraddr: pulumi.Input<string>;
	/**
	 * Transport service ID. For TCP/RDMA, the port number (default 4420). Not used for FC.
	 */
	addrTrsvcid?: pulumi.Input<number | undefined>;
	/**
	 * Fabric transport technology: TCP, RDMA, or FC.
	 */
	addrTrtype: pulumi.Input<string>;
	/**
	 * Whether the port is enabled.
	 */
	enabled?: pulumi.Input<boolean | undefined>;
	/**
	 * Maximum size for inline data transfers in bytes (0-1048576).
	 */
	inlineDataSize?: pulumi.Input<number | undefined>;
	/**
	 * Maximum number of queue entries (1-65535).
	 */
	maxQueueSize?: pulumi.Input<number | undefined>;
	/**
	 * Whether Protection Information (PI) is enabled.
	 */
	piEnable?: pulumi.Input<boolean | undefined>;
	timeouts?: pulumi.Input<inputs.NvmetPortTimeouts | undefined>;
}
