// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class NvmetGlobal extends pulumi.CustomResource {
	/**
	 * Get an existing NvmetGlobal resource's state with the given name, ID, and optional extra
	 * properties used to qualify the lookup.
	 *
	 * @param name The _unique_ name of the resulting resource.
	 * @param id The _unique_ provider ID of the resource to lookup.
	 * @param state Any extra arguments used during the lookup.
	 * @param opts Optional settings to control the behavior of the CustomResource.
	 */
	public static get(
		name: string,
		id: pulumi.Input<pulumi.ID>,
		state?: NvmetGlobalState,
		opts?: pulumi.CustomResourceOptions,
	): NvmetGlobal {
		return new NvmetGlobal(name, <any>state, { ...opts, id: id });
	}

	/** @internal */
	public static readonly __pulumiType = "truenas:index/nvmetGlobal:NvmetGlobal";

	/**
	 * Returns true if the given object is an instance of NvmetGlobal.  This is designed to work even
	 * when multiple copies of the Pulumi SDK have been loaded into the same process.
	 */
	public static isInstance(obj: any): obj is NvmetGlobal {
		if (obj === undefined || obj === null) {
			return false;
		}
		return obj["__pulumiType"] === NvmetGlobal.__pulumiType;
	}

	/**
	 * Enable Asymmetric Namespace Access (ANA).
	 */
	public declare readonly ana: pulumi.Output<boolean>;
	/**
	 * NQN used as the prefix when creating subsystems without an explicit subnqn.
	 */
	public declare readonly basenqn: pulumi.Output<string>;
	/**
	 * Use the kernel NVMe-oF backend.
	 */
	public declare readonly kernel: pulumi.Output<boolean>;
	/**
	 * Enable RDMA transport (Enterprise + RDMA-capable hardware only).
	 */
	public declare readonly rdma: pulumi.Output<boolean>;
	public declare readonly timeouts: pulumi.Output<
		outputs.NvmetGlobalTimeouts | undefined
	>;
	/**
	 * Generate cross-port referrals for ports on this TrueNAS.
	 */
	public declare readonly xportReferral: pulumi.Output<boolean>;

	/**
	 * Create a NvmetGlobal resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 * @param opts A bag of options that control this resource's behavior.
	 */
	constructor(
		name: string,
		args?: NvmetGlobalArgs,
		opts?: pulumi.CustomResourceOptions,
	);
	constructor(
		name: string,
		argsOrState?: NvmetGlobalArgs | NvmetGlobalState,
		opts?: pulumi.CustomResourceOptions,
	) {
		const resourceInputs: pulumi.Inputs = {};
		opts = opts || {};
		if (opts.id) {
			const state = argsOrState as NvmetGlobalState | undefined;
			resourceInputs["ana"] = state?.ana;
			resourceInputs["basenqn"] = state?.basenqn;
			resourceInputs["kernel"] = state?.kernel;
			resourceInputs["rdma"] = state?.rdma;
			resourceInputs["timeouts"] = state?.timeouts;
			resourceInputs["xportReferral"] = state?.xportReferral;
		} else {
			const args = argsOrState as NvmetGlobalArgs | undefined;
			resourceInputs["ana"] = args?.ana;
			resourceInputs["basenqn"] = args?.basenqn;
			resourceInputs["kernel"] = args?.kernel;
			resourceInputs["rdma"] = args?.rdma;
			resourceInputs["timeouts"] = args?.timeouts;
			resourceInputs["xportReferral"] = args?.xportReferral;
		}
		opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
		super(
			NvmetGlobal.__pulumiType,
			name,
			resourceInputs,
			opts,
			false /*dependency*/,
			utilities.getPackage(),
		);
	}
}

/**
 * Input properties used for looking up and filtering NvmetGlobal resources.
 */
export interface NvmetGlobalState {
	/**
	 * Enable Asymmetric Namespace Access (ANA).
	 */
	ana?: pulumi.Input<boolean | undefined>;
	/**
	 * NQN used as the prefix when creating subsystems without an explicit subnqn.
	 */
	basenqn?: pulumi.Input<string | undefined>;
	/**
	 * Use the kernel NVMe-oF backend.
	 */
	kernel?: pulumi.Input<boolean | undefined>;
	/**
	 * Enable RDMA transport (Enterprise + RDMA-capable hardware only).
	 */
	rdma?: pulumi.Input<boolean | undefined>;
	timeouts?: pulumi.Input<inputs.NvmetGlobalTimeouts | undefined>;
	/**
	 * Generate cross-port referrals for ports on this TrueNAS.
	 */
	xportReferral?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a NvmetGlobal resource.
 */
export interface NvmetGlobalArgs {
	/**
	 * Enable Asymmetric Namespace Access (ANA).
	 */
	ana?: pulumi.Input<boolean | undefined>;
	/**
	 * NQN used as the prefix when creating subsystems without an explicit subnqn.
	 */
	basenqn?: pulumi.Input<string | undefined>;
	/**
	 * Use the kernel NVMe-oF backend.
	 */
	kernel?: pulumi.Input<boolean | undefined>;
	/**
	 * Enable RDMA transport (Enterprise + RDMA-capable hardware only).
	 */
	rdma?: pulumi.Input<boolean | undefined>;
	timeouts?: pulumi.Input<inputs.NvmetGlobalTimeouts | undefined>;
	/**
	 * Generate cross-port referrals for ports on this TrueNAS.
	 */
	xportReferral?: pulumi.Input<boolean | undefined>;
}
