// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class NvmetPortSubsys extends pulumi.CustomResource {
	/**
	 * Get an existing NvmetPortSubsys resource's state with the given name, ID, and optional extra
	 * properties used to qualify the lookup.
	 *
	 * @param name The _unique_ name of the resulting resource.
	 * @param id The _unique_ provider ID of the resource to lookup.
	 * @param state Any extra arguments used during the lookup.
	 * @param opts Optional settings to control the behavior of the CustomResource.
	 */
	public static get(
		name: string,
		id: pulumi.Input<pulumi.ID>,
		state?: NvmetPortSubsysState,
		opts?: pulumi.CustomResourceOptions,
	): NvmetPortSubsys {
		return new NvmetPortSubsys(name, <any>state, { ...opts, id: id });
	}

	/** @internal */
	public static readonly __pulumiType =
		"truenas:index/nvmetPortSubsys:NvmetPortSubsys";

	/**
	 * Returns true if the given object is an instance of NvmetPortSubsys.  This is designed to work even
	 * when multiple copies of the Pulumi SDK have been loaded into the same process.
	 */
	public static isInstance(obj: any): obj is NvmetPortSubsys {
		if (obj === undefined || obj === null) {
			return false;
		}
		return obj["__pulumiType"] === NvmetPortSubsys.__pulumiType;
	}

	/**
	 * ID of the NVMe-oF port to associate.
	 */
	public declare readonly portId: pulumi.Output<number>;
	/**
	 * ID of the NVMe-oF subsystem to expose on the port.
	 */
	public declare readonly subsysId: pulumi.Output<number>;
	public declare readonly timeouts: pulumi.Output<
		outputs.NvmetPortSubsysTimeouts | undefined
	>;

	/**
	 * Create a NvmetPortSubsys resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 * @param opts A bag of options that control this resource's behavior.
	 */
	constructor(
		name: string,
		args: NvmetPortSubsysArgs,
		opts?: pulumi.CustomResourceOptions,
	);
	constructor(
		name: string,
		argsOrState?: NvmetPortSubsysArgs | NvmetPortSubsysState,
		opts?: pulumi.CustomResourceOptions,
	) {
		const resourceInputs: pulumi.Inputs = {};
		opts = opts || {};
		if (opts.id) {
			const state = argsOrState as NvmetPortSubsysState | undefined;
			resourceInputs["portId"] = state?.portId;
			resourceInputs["subsysId"] = state?.subsysId;
			resourceInputs["timeouts"] = state?.timeouts;
		} else {
			const args = argsOrState as NvmetPortSubsysArgs | undefined;
			if (args?.portId === undefined && !opts.urn) {
				throw new Error("Missing required property 'portId'");
			}
			if (args?.subsysId === undefined && !opts.urn) {
				throw new Error("Missing required property 'subsysId'");
			}
			resourceInputs["portId"] = args?.portId;
			resourceInputs["subsysId"] = args?.subsysId;
			resourceInputs["timeouts"] = args?.timeouts;
		}
		opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
		super(
			NvmetPortSubsys.__pulumiType,
			name,
			resourceInputs,
			opts,
			false /*dependency*/,
			utilities.getPackage(),
		);
	}
}

/**
 * Input properties used for looking up and filtering NvmetPortSubsys resources.
 */
export interface NvmetPortSubsysState {
	/**
	 * ID of the NVMe-oF port to associate.
	 */
	portId?: pulumi.Input<number | undefined>;
	/**
	 * ID of the NVMe-oF subsystem to expose on the port.
	 */
	subsysId?: pulumi.Input<number | undefined>;
	timeouts?: pulumi.Input<inputs.NvmetPortSubsysTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a NvmetPortSubsys resource.
 */
export interface NvmetPortSubsysArgs {
	/**
	 * ID of the NVMe-oF port to associate.
	 */
	portId: pulumi.Input<number>;
	/**
	 * ID of the NVMe-oF subsystem to expose on the port.
	 */
	subsysId: pulumi.Input<number>;
	timeouts?: pulumi.Input<inputs.NvmetPortSubsysTimeouts | undefined>;
}
