// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class NvmetNamespace extends pulumi.CustomResource {
	/**
	 * Get an existing NvmetNamespace resource's state with the given name, ID, and optional extra
	 * properties used to qualify the lookup.
	 *
	 * @param name The _unique_ name of the resulting resource.
	 * @param id The _unique_ provider ID of the resource to lookup.
	 * @param state Any extra arguments used during the lookup.
	 * @param opts Optional settings to control the behavior of the CustomResource.
	 */
	public static get(
		name: string,
		id: pulumi.Input<pulumi.ID>,
		state?: NvmetNamespaceState,
		opts?: pulumi.CustomResourceOptions,
	): NvmetNamespace {
		return new NvmetNamespace(name, <any>state, { ...opts, id: id });
	}

	/** @internal */
	public static readonly __pulumiType =
		"truenas:index/nvmetNamespace:NvmetNamespace";

	/**
	 * Returns true if the given object is an instance of NvmetNamespace.  This is designed to work even
	 * when multiple copies of the Pulumi SDK have been loaded into the same process.
	 */
	public static isInstance(obj: any): obj is NvmetNamespace {
		if (obj === undefined || obj === null) {
			return false;
		}
		return obj["__pulumiType"] === NvmetNamespace.__pulumiType;
	}

	/**
	 * Path to the device or file for the namespace.
	 */
	public declare readonly devicePath: pulumi.Output<string>;
	/**
	 * Type of device backing the namespace: ZVOL or FILE.
	 */
	public declare readonly deviceType: pulumi.Output<string>;
	/**
	 * If false, the namespace is not accessible.
	 */
	public declare readonly enabled: pulumi.Output<boolean>;
	/**
	 * Size of the backing file in bytes. Only used when<span pulumi-lang-nodejs=" deviceType " pulumi-lang-dotnet=" DeviceType " pulumi-lang-go=" deviceType " pulumi-lang-python=" device_type " pulumi-lang-yaml=" deviceType " pulumi-lang-java=" deviceType " pulumi-lang-hcl=" device_type "> deviceType </span>is FILE.
	 */
	public declare readonly filesize: pulumi.Output<number | undefined>;
	/**
	 * Namespace ID (NSID), unique within the subsystem. Auto-assigned if not provided.
	 */
	public declare readonly nsid: pulumi.Output<number>;
	/**
	 * ID of the NVMe-oF subsystem to contain this namespace.
	 */
	public declare readonly subsysId: pulumi.Output<number>;
	public declare readonly timeouts: pulumi.Output<
		outputs.NvmetNamespaceTimeouts | undefined
	>;

	/**
	 * Create a NvmetNamespace resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 * @param opts A bag of options that control this resource's behavior.
	 */
	constructor(
		name: string,
		args: NvmetNamespaceArgs,
		opts?: pulumi.CustomResourceOptions,
	);
	constructor(
		name: string,
		argsOrState?: NvmetNamespaceArgs | NvmetNamespaceState,
		opts?: pulumi.CustomResourceOptions,
	) {
		const resourceInputs: pulumi.Inputs = {};
		opts = opts || {};
		if (opts.id) {
			const state = argsOrState as NvmetNamespaceState | undefined;
			resourceInputs["devicePath"] = state?.devicePath;
			resourceInputs["deviceType"] = state?.deviceType;
			resourceInputs["enabled"] = state?.enabled;
			resourceInputs["filesize"] = state?.filesize;
			resourceInputs["nsid"] = state?.nsid;
			resourceInputs["subsysId"] = state?.subsysId;
			resourceInputs["timeouts"] = state?.timeouts;
		} else {
			const args = argsOrState as NvmetNamespaceArgs | undefined;
			if (args?.devicePath === undefined && !opts.urn) {
				throw new Error("Missing required property 'devicePath'");
			}
			if (args?.deviceType === undefined && !opts.urn) {
				throw new Error("Missing required property 'deviceType'");
			}
			if (args?.subsysId === undefined && !opts.urn) {
				throw new Error("Missing required property 'subsysId'");
			}
			resourceInputs["devicePath"] = args?.devicePath;
			resourceInputs["deviceType"] = args?.deviceType;
			resourceInputs["enabled"] = args?.enabled;
			resourceInputs["filesize"] = args?.filesize;
			resourceInputs["nsid"] = args?.nsid;
			resourceInputs["subsysId"] = args?.subsysId;
			resourceInputs["timeouts"] = args?.timeouts;
		}
		opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
		super(
			NvmetNamespace.__pulumiType,
			name,
			resourceInputs,
			opts,
			false /*dependency*/,
			utilities.getPackage(),
		);
	}
}

/**
 * Input properties used for looking up and filtering NvmetNamespace resources.
 */
export interface NvmetNamespaceState {
	/**
	 * Path to the device or file for the namespace.
	 */
	devicePath?: pulumi.Input<string | undefined>;
	/**
	 * Type of device backing the namespace: ZVOL or FILE.
	 */
	deviceType?: pulumi.Input<string | undefined>;
	/**
	 * If false, the namespace is not accessible.
	 */
	enabled?: pulumi.Input<boolean | undefined>;
	/**
	 * Size of the backing file in bytes. Only used when<span pulumi-lang-nodejs=" deviceType " pulumi-lang-dotnet=" DeviceType " pulumi-lang-go=" deviceType " pulumi-lang-python=" device_type " pulumi-lang-yaml=" deviceType " pulumi-lang-java=" deviceType " pulumi-lang-hcl=" device_type "> deviceType </span>is FILE.
	 */
	filesize?: pulumi.Input<number | undefined>;
	/**
	 * Namespace ID (NSID), unique within the subsystem. Auto-assigned if not provided.
	 */
	nsid?: pulumi.Input<number | undefined>;
	/**
	 * ID of the NVMe-oF subsystem to contain this namespace.
	 */
	subsysId?: pulumi.Input<number | undefined>;
	timeouts?: pulumi.Input<inputs.NvmetNamespaceTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a NvmetNamespace resource.
 */
export interface NvmetNamespaceArgs {
	/**
	 * Path to the device or file for the namespace.
	 */
	devicePath: pulumi.Input<string>;
	/**
	 * Type of device backing the namespace: ZVOL or FILE.
	 */
	deviceType: pulumi.Input<string>;
	/**
	 * If false, the namespace is not accessible.
	 */
	enabled?: pulumi.Input<boolean | undefined>;
	/**
	 * Size of the backing file in bytes. Only used when<span pulumi-lang-nodejs=" deviceType " pulumi-lang-dotnet=" DeviceType " pulumi-lang-go=" deviceType " pulumi-lang-python=" device_type " pulumi-lang-yaml=" deviceType " pulumi-lang-java=" deviceType " pulumi-lang-hcl=" device_type "> deviceType </span>is FILE.
	 */
	filesize?: pulumi.Input<number | undefined>;
	/**
	 * Namespace ID (NSID), unique within the subsystem. Auto-assigned if not provided.
	 */
	nsid?: pulumi.Input<number | undefined>;
	/**
	 * ID of the NVMe-oF subsystem to contain this namespace.
	 */
	subsysId: pulumi.Input<number>;
	timeouts?: pulumi.Input<inputs.NvmetNamespaceTimeouts | undefined>;
}
