// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class NvmetSubsys extends pulumi.CustomResource {
	/**
	 * Get an existing NvmetSubsys resource's state with the given name, ID, and optional extra
	 * properties used to qualify the lookup.
	 *
	 * @param name The _unique_ name of the resulting resource.
	 * @param id The _unique_ provider ID of the resource to lookup.
	 * @param state Any extra arguments used during the lookup.
	 * @param opts Optional settings to control the behavior of the CustomResource.
	 */
	public static get(
		name: string,
		id: pulumi.Input<pulumi.ID>,
		state?: NvmetSubsysState,
		opts?: pulumi.CustomResourceOptions,
	): NvmetSubsys {
		return new NvmetSubsys(name, <any>state, { ...opts, id: id });
	}

	/** @internal */
	public static readonly __pulumiType = "truenas:index/nvmetSubsys:NvmetSubsys";

	/**
	 * Returns true if the given object is an instance of NvmetSubsys.  This is designed to work even
	 * when multiple copies of the Pulumi SDK have been loaded into the same process.
	 */
	public static isInstance(obj: any): obj is NvmetSubsys {
		if (obj === undefined || obj === null) {
			return false;
		}
		return obj["__pulumiType"] === NvmetSubsys.__pulumiType;
	}

	/**
	 * Allow any host to access the storage in this subsystem (no access control).
	 */
	public declare readonly allowAnyHost: pulumi.Output<boolean>;
	/**
	 * Per-subsystem override of the global ANA setting. Leave unset to inherit global.
	 */
	public declare readonly ana: pulumi.Output<boolean | undefined>;
	/**
	 * IEEE Organizationally Unique Identifier for the subsystem (6 hex chars).
	 */
	public declare readonly ieeeOui: pulumi.Output<string | undefined>;
	/**
	 * Human-readable name for the subsystem. If subnqn is not provided, this name is appended to the global basenqn.
	 */
	public declare readonly name: pulumi.Output<string>;
	/**
	 * Enable Protection Information (PI) for data integrity checking.
	 */
	public declare readonly piEnable: pulumi.Output<boolean | undefined>;
	/**
	 * Maximum number of queue IDs allowed for this subsystem (1-65535).
	 */
	public declare readonly qidMax: pulumi.Output<number | undefined>;
	/**
	 * Serial number assigned to the subsystem (computed).
	 */
	public /*out*/ declare readonly serial: pulumi.Output<string>;
	/**
	 * NVMe Qualified Name (NQN) for the subsystem. Auto-generated if not provided.
	 */
	public declare readonly subnqn: pulumi.Output<string>;
	public declare readonly timeouts: pulumi.Output<
		outputs.NvmetSubsysTimeouts | undefined
	>;

	/**
	 * Create a NvmetSubsys resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 * @param opts A bag of options that control this resource's behavior.
	 */
	constructor(
		name: string,
		args?: NvmetSubsysArgs,
		opts?: pulumi.CustomResourceOptions,
	);
	constructor(
		name: string,
		argsOrState?: NvmetSubsysArgs | NvmetSubsysState,
		opts?: pulumi.CustomResourceOptions,
	) {
		const resourceInputs: pulumi.Inputs = {};
		opts = opts || {};
		if (opts.id) {
			const state = argsOrState as NvmetSubsysState | undefined;
			resourceInputs["allowAnyHost"] = state?.allowAnyHost;
			resourceInputs["ana"] = state?.ana;
			resourceInputs["ieeeOui"] = state?.ieeeOui;
			resourceInputs["name"] = state?.name;
			resourceInputs["piEnable"] = state?.piEnable;
			resourceInputs["qidMax"] = state?.qidMax;
			resourceInputs["serial"] = state?.serial;
			resourceInputs["subnqn"] = state?.subnqn;
			resourceInputs["timeouts"] = state?.timeouts;
		} else {
			const args = argsOrState as NvmetSubsysArgs | undefined;
			resourceInputs["allowAnyHost"] = args?.allowAnyHost;
			resourceInputs["ana"] = args?.ana;
			resourceInputs["ieeeOui"] = args?.ieeeOui;
			resourceInputs["name"] = args?.name;
			resourceInputs["piEnable"] = args?.piEnable;
			resourceInputs["qidMax"] = args?.qidMax;
			resourceInputs["subnqn"] = args?.subnqn;
			resourceInputs["timeouts"] = args?.timeouts;
			resourceInputs["serial"] = undefined /*out*/;
		}
		opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
		super(
			NvmetSubsys.__pulumiType,
			name,
			resourceInputs,
			opts,
			false /*dependency*/,
			utilities.getPackage(),
		);
	}
}

/**
 * Input properties used for looking up and filtering NvmetSubsys resources.
 */
export interface NvmetSubsysState {
	/**
	 * Allow any host to access the storage in this subsystem (no access control).
	 */
	allowAnyHost?: pulumi.Input<boolean | undefined>;
	/**
	 * Per-subsystem override of the global ANA setting. Leave unset to inherit global.
	 */
	ana?: pulumi.Input<boolean | undefined>;
	/**
	 * IEEE Organizationally Unique Identifier for the subsystem (6 hex chars).
	 */
	ieeeOui?: pulumi.Input<string | undefined>;
	/**
	 * Human-readable name for the subsystem. If subnqn is not provided, this name is appended to the global basenqn.
	 */
	name?: pulumi.Input<string | undefined>;
	/**
	 * Enable Protection Information (PI) for data integrity checking.
	 */
	piEnable?: pulumi.Input<boolean | undefined>;
	/**
	 * Maximum number of queue IDs allowed for this subsystem (1-65535).
	 */
	qidMax?: pulumi.Input<number | undefined>;
	/**
	 * Serial number assigned to the subsystem (computed).
	 */
	serial?: pulumi.Input<string | undefined>;
	/**
	 * NVMe Qualified Name (NQN) for the subsystem. Auto-generated if not provided.
	 */
	subnqn?: pulumi.Input<string | undefined>;
	timeouts?: pulumi.Input<inputs.NvmetSubsysTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a NvmetSubsys resource.
 */
export interface NvmetSubsysArgs {
	/**
	 * Allow any host to access the storage in this subsystem (no access control).
	 */
	allowAnyHost?: pulumi.Input<boolean | undefined>;
	/**
	 * Per-subsystem override of the global ANA setting. Leave unset to inherit global.
	 */
	ana?: pulumi.Input<boolean | undefined>;
	/**
	 * IEEE Organizationally Unique Identifier for the subsystem (6 hex chars).
	 */
	ieeeOui?: pulumi.Input<string | undefined>;
	/**
	 * Human-readable name for the subsystem. If subnqn is not provided, this name is appended to the global basenqn.
	 */
	name?: pulumi.Input<string | undefined>;
	/**
	 * Enable Protection Information (PI) for data integrity checking.
	 */
	piEnable?: pulumi.Input<boolean | undefined>;
	/**
	 * Maximum number of queue IDs allowed for this subsystem (1-65535).
	 */
	qidMax?: pulumi.Input<number | undefined>;
	/**
	 * NVMe Qualified Name (NQN) for the subsystem. Auto-generated if not provided.
	 */
	subnqn?: pulumi.Input<string | undefined>;
	timeouts?: pulumi.Input<inputs.NvmetSubsysTimeouts | undefined>;
}
