// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Pool extends pulumi.CustomResource {
	/**
	 * Get an existing Pool resource's state with the given name, ID, and optional extra
	 * properties used to qualify the lookup.
	 *
	 * @param name The _unique_ name of the resulting resource.
	 * @param id The _unique_ provider ID of the resource to lookup.
	 * @param state Any extra arguments used during the lookup.
	 * @param opts Optional settings to control the behavior of the CustomResource.
	 */
	public static get(
		name: string,
		id: pulumi.Input<pulumi.ID>,
		state?: PoolState,
		opts?: pulumi.CustomResourceOptions,
	): Pool {
		return new Pool(name, <any>state, { ...opts, id: id });
	}

	/** @internal */
	public static readonly __pulumiType = "truenas:index/pool:Pool";

	/**
	 * Returns true if the given object is an instance of Pool.  This is designed to work even
	 * when multiple copies of the Pulumi SDK have been loaded into the same process.
	 */
	public static isInstance(obj: any): obj is Pool {
		if (obj === undefined || obj === null) {
			return false;
		}
		return obj["__pulumiType"] === Pool.__pulumiType;
	}

	/**
	 * Whether to allow disks with duplicate serial numbers in this pool.
	 */
	public declare readonly allowDuplicateSerials: pulumi.Output<boolean>;
	/**
	 * Checksum algorithm: ON, OFF, FLETCHER2, FLETCHER4, SHA256, SHA512, SKEIN, EDONR, BLAKE3.
	 */
	public declare readonly checksum: pulumi.Output<string>;
	/**
	 * Deduplication mode: ON, VERIFY, OFF, or unset.
	 */
	public declare readonly deduplication: pulumi.Output<string>;
	/**
	 * Whether to create a ZFS-encrypted root dataset for this pool.
	 */
	public declare readonly encryption: pulumi.Output<boolean>;
	/**
	 * Optional encryption options as a raw JSON object (e.g. generate_key, algorithm, passphrase, key, pbkdf2iters).
	 */
	public declare readonly encryptionOptionsJson: pulumi.Output<
		string | undefined
	>;
	/**
	 * The ZFS GUID of the pool.
	 */
	public /*out*/ declare readonly guid: pulumi.Output<string>;
	/**
	 * Whether the pool is in a healthy state.
	 */
	public /*out*/ declare readonly healthy: pulumi.Output<boolean>;
	/**
	 * The name of the pool (1-50 characters).
	 */
	public declare readonly name: pulumi.Output<string>;
	/**
	 * The filesystem mount path of the pool.
	 */
	public /*out*/ declare readonly path: pulumi.Output<string>;
	/**
	 * The current status of the pool (ONLINE, DEGRADED, FAULTED, ...).
	 */
	public /*out*/ declare readonly status: pulumi.Output<string>;
	public declare readonly timeouts: pulumi.Output<
		outputs.PoolTimeouts | undefined
	>;
	/**
	 * The pool topology as a raw JSON object. Must contain at least a <span pulumi-lang-nodejs="`data`" pulumi-lang-dotnet="`Data`" pulumi-lang-go="`data`" pulumi-lang-python="`data`" pulumi-lang-yaml="`data`" pulumi-lang-java="`data`" pulumi-lang-hcl="`data`">`data`</span> key with a list of vdev definitions (e.g. {"data":[{"type":"MIRROR","disks":["sda","sdb"]}]}). May also contain cache, log, spares, special, and dedup keys. Required on create; ignored after import since the API does not round-trip the original request form.
	 */
	public declare readonly topologyJson: pulumi.Output<string>;

	/**
	 * Create a Pool resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 * @param opts A bag of options that control this resource's behavior.
	 */
	constructor(
		name: string,
		args?: PoolArgs,
		opts?: pulumi.CustomResourceOptions,
	);
	constructor(
		name: string,
		argsOrState?: PoolArgs | PoolState,
		opts?: pulumi.CustomResourceOptions,
	) {
		const resourceInputs: pulumi.Inputs = {};
		opts = opts || {};
		if (opts.id) {
			const state = argsOrState as PoolState | undefined;
			resourceInputs["allowDuplicateSerials"] = state?.allowDuplicateSerials;
			resourceInputs["checksum"] = state?.checksum;
			resourceInputs["deduplication"] = state?.deduplication;
			resourceInputs["encryption"] = state?.encryption;
			resourceInputs["encryptionOptionsJson"] = state?.encryptionOptionsJson;
			resourceInputs["guid"] = state?.guid;
			resourceInputs["healthy"] = state?.healthy;
			resourceInputs["name"] = state?.name;
			resourceInputs["path"] = state?.path;
			resourceInputs["status"] = state?.status;
			resourceInputs["timeouts"] = state?.timeouts;
			resourceInputs["topologyJson"] = state?.topologyJson;
		} else {
			const args = argsOrState as PoolArgs | undefined;
			resourceInputs["allowDuplicateSerials"] = args?.allowDuplicateSerials;
			resourceInputs["checksum"] = args?.checksum;
			resourceInputs["deduplication"] = args?.deduplication;
			resourceInputs["encryption"] = args?.encryption;
			resourceInputs["encryptionOptionsJson"] = args?.encryptionOptionsJson;
			resourceInputs["name"] = args?.name;
			resourceInputs["timeouts"] = args?.timeouts;
			resourceInputs["topologyJson"] = args?.topologyJson;
			resourceInputs["guid"] = undefined /*out*/;
			resourceInputs["healthy"] = undefined /*out*/;
			resourceInputs["path"] = undefined /*out*/;
			resourceInputs["status"] = undefined /*out*/;
		}
		opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
		super(
			Pool.__pulumiType,
			name,
			resourceInputs,
			opts,
			false /*dependency*/,
			utilities.getPackage(),
		);
	}
}

/**
 * Input properties used for looking up and filtering Pool resources.
 */
export interface PoolState {
	/**
	 * Whether to allow disks with duplicate serial numbers in this pool.
	 */
	allowDuplicateSerials?: pulumi.Input<boolean | undefined>;
	/**
	 * Checksum algorithm: ON, OFF, FLETCHER2, FLETCHER4, SHA256, SHA512, SKEIN, EDONR, BLAKE3.
	 */
	checksum?: pulumi.Input<string | undefined>;
	/**
	 * Deduplication mode: ON, VERIFY, OFF, or unset.
	 */
	deduplication?: pulumi.Input<string | undefined>;
	/**
	 * Whether to create a ZFS-encrypted root dataset for this pool.
	 */
	encryption?: pulumi.Input<boolean | undefined>;
	/**
	 * Optional encryption options as a raw JSON object (e.g. generate_key, algorithm, passphrase, key, pbkdf2iters).
	 */
	encryptionOptionsJson?: pulumi.Input<string | undefined>;
	/**
	 * The ZFS GUID of the pool.
	 */
	guid?: pulumi.Input<string | undefined>;
	/**
	 * Whether the pool is in a healthy state.
	 */
	healthy?: pulumi.Input<boolean | undefined>;
	/**
	 * The name of the pool (1-50 characters).
	 */
	name?: pulumi.Input<string | undefined>;
	/**
	 * The filesystem mount path of the pool.
	 */
	path?: pulumi.Input<string | undefined>;
	/**
	 * The current status of the pool (ONLINE, DEGRADED, FAULTED, ...).
	 */
	status?: pulumi.Input<string | undefined>;
	timeouts?: pulumi.Input<inputs.PoolTimeouts | undefined>;
	/**
	 * The pool topology as a raw JSON object. Must contain at least a <span pulumi-lang-nodejs="`data`" pulumi-lang-dotnet="`Data`" pulumi-lang-go="`data`" pulumi-lang-python="`data`" pulumi-lang-yaml="`data`" pulumi-lang-java="`data`" pulumi-lang-hcl="`data`">`data`</span> key with a list of vdev definitions (e.g. {"data":[{"type":"MIRROR","disks":["sda","sdb"]}]}). May also contain cache, log, spares, special, and dedup keys. Required on create; ignored after import since the API does not round-trip the original request form.
	 */
	topologyJson?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Pool resource.
 */
export interface PoolArgs {
	/**
	 * Whether to allow disks with duplicate serial numbers in this pool.
	 */
	allowDuplicateSerials?: pulumi.Input<boolean | undefined>;
	/**
	 * Checksum algorithm: ON, OFF, FLETCHER2, FLETCHER4, SHA256, SHA512, SKEIN, EDONR, BLAKE3.
	 */
	checksum?: pulumi.Input<string | undefined>;
	/**
	 * Deduplication mode: ON, VERIFY, OFF, or unset.
	 */
	deduplication?: pulumi.Input<string | undefined>;
	/**
	 * Whether to create a ZFS-encrypted root dataset for this pool.
	 */
	encryption?: pulumi.Input<boolean | undefined>;
	/**
	 * Optional encryption options as a raw JSON object (e.g. generate_key, algorithm, passphrase, key, pbkdf2iters).
	 */
	encryptionOptionsJson?: pulumi.Input<string | undefined>;
	/**
	 * The name of the pool (1-50 characters).
	 */
	name?: pulumi.Input<string | undefined>;
	timeouts?: pulumi.Input<inputs.PoolTimeouts | undefined>;
	/**
	 * The pool topology as a raw JSON object. Must contain at least a <span pulumi-lang-nodejs="`data`" pulumi-lang-dotnet="`Data`" pulumi-lang-go="`data`" pulumi-lang-python="`data`" pulumi-lang-yaml="`data`" pulumi-lang-java="`data`" pulumi-lang-hcl="`data`">`data`</span> key with a list of vdev definitions (e.g. {"data":[{"type":"MIRROR","disks":["sda","sdb"]}]}). May also contain cache, log, spares, special, and dedup keys. Required on create; ignored after import since the API does not round-trip the original request form.
	 */
	topologyJson?: pulumi.Input<string | undefined>;
}
