// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class SmbConfig extends pulumi.CustomResource {
	/**
	 * Get an existing SmbConfig resource's state with the given name, ID, and optional extra
	 * properties used to qualify the lookup.
	 *
	 * @param name The _unique_ name of the resulting resource.
	 * @param id The _unique_ provider ID of the resource to lookup.
	 * @param state Any extra arguments used during the lookup.
	 * @param opts Optional settings to control the behavior of the CustomResource.
	 */
	public static get(
		name: string,
		id: pulumi.Input<pulumi.ID>,
		state?: SmbConfigState,
		opts?: pulumi.CustomResourceOptions,
	): SmbConfig {
		return new SmbConfig(name, <any>state, { ...opts, id: id });
	}

	/** @internal */
	public static readonly __pulumiType = "truenas:index/smbConfig:SmbConfig";

	/**
	 * Returns true if the given object is an instance of SmbConfig.  This is designed to work even
	 * when multiple copies of the Pulumi SDK have been loaded into the same process.
	 */
	public static isInstance(obj: any): obj is SmbConfig {
		if (obj === undefined || obj === null) {
			return false;
		}
		return obj["__pulumiType"] === SmbConfig.__pulumiType;
	}

	/**
	 * Enable Apple SMB2/3 protocol extensions.
	 */
	public declare readonly aaplExtensions: pulumi.Output<boolean>;
	/**
	 * Server description.
	 */
	public declare readonly description: pulumi.Output<string>;
	/**
	 * Directory creation mask.
	 */
	public declare readonly dirmask: pulumi.Output<string>;
	/**
	 * Enable SMB1 protocol support.
	 */
	public declare readonly enableSmb1: pulumi.Output<boolean>;
	/**
	 * File creation mask.
	 */
	public declare readonly filemask: pulumi.Output<string>;
	/**
	 * Guest account for unauthenticated access.
	 */
	public declare readonly guest: pulumi.Output<string>;
	/**
	 * NetBIOS name of the server.
	 */
	public declare readonly netbiosname: pulumi.Output<string>;
	public declare readonly timeouts: pulumi.Output<
		outputs.SmbConfigTimeouts | undefined
	>;
	/**
	 * UNIX character set.
	 */
	public declare readonly unixcharset: pulumi.Output<string>;
	/**
	 * Windows workgroup name.
	 */
	public declare readonly workgroup: pulumi.Output<string>;

	/**
	 * Create a SmbConfig resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 * @param opts A bag of options that control this resource's behavior.
	 */
	constructor(
		name: string,
		args?: SmbConfigArgs,
		opts?: pulumi.CustomResourceOptions,
	);
	constructor(
		name: string,
		argsOrState?: SmbConfigArgs | SmbConfigState,
		opts?: pulumi.CustomResourceOptions,
	) {
		const resourceInputs: pulumi.Inputs = {};
		opts = opts || {};
		if (opts.id) {
			const state = argsOrState as SmbConfigState | undefined;
			resourceInputs["aaplExtensions"] = state?.aaplExtensions;
			resourceInputs["description"] = state?.description;
			resourceInputs["dirmask"] = state?.dirmask;
			resourceInputs["enableSmb1"] = state?.enableSmb1;
			resourceInputs["filemask"] = state?.filemask;
			resourceInputs["guest"] = state?.guest;
			resourceInputs["netbiosname"] = state?.netbiosname;
			resourceInputs["timeouts"] = state?.timeouts;
			resourceInputs["unixcharset"] = state?.unixcharset;
			resourceInputs["workgroup"] = state?.workgroup;
		} else {
			const args = argsOrState as SmbConfigArgs | undefined;
			resourceInputs["aaplExtensions"] = args?.aaplExtensions;
			resourceInputs["description"] = args?.description;
			resourceInputs["dirmask"] = args?.dirmask;
			resourceInputs["enableSmb1"] = args?.enableSmb1;
			resourceInputs["filemask"] = args?.filemask;
			resourceInputs["guest"] = args?.guest;
			resourceInputs["netbiosname"] = args?.netbiosname;
			resourceInputs["timeouts"] = args?.timeouts;
			resourceInputs["unixcharset"] = args?.unixcharset;
			resourceInputs["workgroup"] = args?.workgroup;
		}
		opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
		super(
			SmbConfig.__pulumiType,
			name,
			resourceInputs,
			opts,
			false /*dependency*/,
			utilities.getPackage(),
		);
	}
}

/**
 * Input properties used for looking up and filtering SmbConfig resources.
 */
export interface SmbConfigState {
	/**
	 * Enable Apple SMB2/3 protocol extensions.
	 */
	aaplExtensions?: pulumi.Input<boolean | undefined>;
	/**
	 * Server description.
	 */
	description?: pulumi.Input<string | undefined>;
	/**
	 * Directory creation mask.
	 */
	dirmask?: pulumi.Input<string | undefined>;
	/**
	 * Enable SMB1 protocol support.
	 */
	enableSmb1?: pulumi.Input<boolean | undefined>;
	/**
	 * File creation mask.
	 */
	filemask?: pulumi.Input<string | undefined>;
	/**
	 * Guest account for unauthenticated access.
	 */
	guest?: pulumi.Input<string | undefined>;
	/**
	 * NetBIOS name of the server.
	 */
	netbiosname?: pulumi.Input<string | undefined>;
	timeouts?: pulumi.Input<inputs.SmbConfigTimeouts | undefined>;
	/**
	 * UNIX character set.
	 */
	unixcharset?: pulumi.Input<string | undefined>;
	/**
	 * Windows workgroup name.
	 */
	workgroup?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a SmbConfig resource.
 */
export interface SmbConfigArgs {
	/**
	 * Enable Apple SMB2/3 protocol extensions.
	 */
	aaplExtensions?: pulumi.Input<boolean | undefined>;
	/**
	 * Server description.
	 */
	description?: pulumi.Input<string | undefined>;
	/**
	 * Directory creation mask.
	 */
	dirmask?: pulumi.Input<string | undefined>;
	/**
	 * Enable SMB1 protocol support.
	 */
	enableSmb1?: pulumi.Input<boolean | undefined>;
	/**
	 * File creation mask.
	 */
	filemask?: pulumi.Input<string | undefined>;
	/**
	 * Guest account for unauthenticated access.
	 */
	guest?: pulumi.Input<string | undefined>;
	/**
	 * NetBIOS name of the server.
	 */
	netbiosname?: pulumi.Input<string | undefined>;
	timeouts?: pulumi.Input<inputs.SmbConfigTimeouts | undefined>;
	/**
	 * UNIX character set.
	 */
	unixcharset?: pulumi.Input<string | undefined>;
	/**
	 * Windows workgroup name.
	 */
	workgroup?: pulumi.Input<string | undefined>;
}
