// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class SnmpConfig extends pulumi.CustomResource {
	/**
	 * Get an existing SnmpConfig resource's state with the given name, ID, and optional extra
	 * properties used to qualify the lookup.
	 *
	 * @param name The _unique_ name of the resulting resource.
	 * @param id The _unique_ provider ID of the resource to lookup.
	 * @param state Any extra arguments used during the lookup.
	 * @param opts Optional settings to control the behavior of the CustomResource.
	 */
	public static get(
		name: string,
		id: pulumi.Input<pulumi.ID>,
		state?: SnmpConfigState,
		opts?: pulumi.CustomResourceOptions,
	): SnmpConfig {
		return new SnmpConfig(name, <any>state, { ...opts, id: id });
	}

	/** @internal */
	public static readonly __pulumiType = "truenas:index/snmpConfig:SnmpConfig";

	/**
	 * Returns true if the given object is an instance of SnmpConfig.  This is designed to work even
	 * when multiple copies of the Pulumi SDK have been loaded into the same process.
	 */
	public static isInstance(obj: any): obj is SnmpConfig {
		if (obj === undefined || obj === null) {
			return false;
		}
		return obj["__pulumiType"] === SnmpConfig.__pulumiType;
	}

	/**
	 * SNMP community string.
	 */
	public declare readonly community: pulumi.Output<string>;
	/**
	 * SNMP contact information.
	 */
	public declare readonly contact: pulumi.Output<string>;
	/**
	 * SNMP system location.
	 */
	public declare readonly location: pulumi.Output<string>;
	public declare readonly timeouts: pulumi.Output<
		outputs.SnmpConfigTimeouts | undefined
	>;
	/**
	 * Enable SNMPv3 support.
	 */
	public declare readonly v3: pulumi.Output<boolean>;
	/**
	 * SNMPv3 authentication type (SHA, MD5).
	 */
	public declare readonly v3Authtype: pulumi.Output<string>;
	/**
	 * SNMPv3 authentication password.
	 */
	public declare readonly v3Password: pulumi.Output<string>;
	/**
	 * SNMPv3 privacy passphrase (8+ chars or empty).
	 */
	public declare readonly v3Privpassphrase: pulumi.Output<string>;
	/**
	 * SNMPv3 privacy protocol (AES, DES).
	 */
	public declare readonly v3Privproto: pulumi.Output<string>;
	/**
	 * SNMPv3 username.
	 */
	public declare readonly v3Username: pulumi.Output<string>;

	/**
	 * Create a SnmpConfig resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 * @param opts A bag of options that control this resource's behavior.
	 */
	constructor(
		name: string,
		args?: SnmpConfigArgs,
		opts?: pulumi.CustomResourceOptions,
	);
	constructor(
		name: string,
		argsOrState?: SnmpConfigArgs | SnmpConfigState,
		opts?: pulumi.CustomResourceOptions,
	) {
		const resourceInputs: pulumi.Inputs = {};
		opts = opts || {};
		if (opts.id) {
			const state = argsOrState as SnmpConfigState | undefined;
			resourceInputs["community"] = state?.community;
			resourceInputs["contact"] = state?.contact;
			resourceInputs["location"] = state?.location;
			resourceInputs["timeouts"] = state?.timeouts;
			resourceInputs["v3"] = state?.v3;
			resourceInputs["v3Authtype"] = state?.v3Authtype;
			resourceInputs["v3Password"] = state?.v3Password;
			resourceInputs["v3Privpassphrase"] = state?.v3Privpassphrase;
			resourceInputs["v3Privproto"] = state?.v3Privproto;
			resourceInputs["v3Username"] = state?.v3Username;
		} else {
			const args = argsOrState as SnmpConfigArgs | undefined;
			resourceInputs["community"] = args?.community;
			resourceInputs["contact"] = args?.contact;
			resourceInputs["location"] = args?.location;
			resourceInputs["timeouts"] = args?.timeouts;
			resourceInputs["v3"] = args?.v3;
			resourceInputs["v3Authtype"] = args?.v3Authtype;
			resourceInputs["v3Password"] = args?.v3Password
				? pulumi.secret(args.v3Password)
				: undefined;
			resourceInputs["v3Privpassphrase"] = args?.v3Privpassphrase
				? pulumi.secret(args.v3Privpassphrase)
				: undefined;
			resourceInputs["v3Privproto"] = args?.v3Privproto;
			resourceInputs["v3Username"] = args?.v3Username;
		}
		opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
		const secretOpts = {
			additionalSecretOutputs: ["v3Password", "v3Privpassphrase"],
		};
		opts = pulumi.mergeOptions(opts, secretOpts);
		super(
			SnmpConfig.__pulumiType,
			name,
			resourceInputs,
			opts,
			false /*dependency*/,
			utilities.getPackage(),
		);
	}
}

/**
 * Input properties used for looking up and filtering SnmpConfig resources.
 */
export interface SnmpConfigState {
	/**
	 * SNMP community string.
	 */
	community?: pulumi.Input<string | undefined>;
	/**
	 * SNMP contact information.
	 */
	contact?: pulumi.Input<string | undefined>;
	/**
	 * SNMP system location.
	 */
	location?: pulumi.Input<string | undefined>;
	timeouts?: pulumi.Input<inputs.SnmpConfigTimeouts | undefined>;
	/**
	 * Enable SNMPv3 support.
	 */
	v3?: pulumi.Input<boolean | undefined>;
	/**
	 * SNMPv3 authentication type (SHA, MD5).
	 */
	v3Authtype?: pulumi.Input<string | undefined>;
	/**
	 * SNMPv3 authentication password.
	 */
	v3Password?: pulumi.Input<string | undefined>;
	/**
	 * SNMPv3 privacy passphrase (8+ chars or empty).
	 */
	v3Privpassphrase?: pulumi.Input<string | undefined>;
	/**
	 * SNMPv3 privacy protocol (AES, DES).
	 */
	v3Privproto?: pulumi.Input<string | undefined>;
	/**
	 * SNMPv3 username.
	 */
	v3Username?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a SnmpConfig resource.
 */
export interface SnmpConfigArgs {
	/**
	 * SNMP community string.
	 */
	community?: pulumi.Input<string | undefined>;
	/**
	 * SNMP contact information.
	 */
	contact?: pulumi.Input<string | undefined>;
	/**
	 * SNMP system location.
	 */
	location?: pulumi.Input<string | undefined>;
	timeouts?: pulumi.Input<inputs.SnmpConfigTimeouts | undefined>;
	/**
	 * Enable SNMPv3 support.
	 */
	v3?: pulumi.Input<boolean | undefined>;
	/**
	 * SNMPv3 authentication type (SHA, MD5).
	 */
	v3Authtype?: pulumi.Input<string | undefined>;
	/**
	 * SNMPv3 authentication password.
	 */
	v3Password?: pulumi.Input<string | undefined>;
	/**
	 * SNMPv3 privacy passphrase (8+ chars or empty).
	 */
	v3Privpassphrase?: pulumi.Input<string | undefined>;
	/**
	 * SNMPv3 privacy protocol (AES, DES).
	 */
	v3Privproto?: pulumi.Input<string | undefined>;
	/**
	 * SNMPv3 username.
	 */
	v3Username?: pulumi.Input<string | undefined>;
}
