// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import type * as inputs from "./types/input";
import type * as outputs from "./types/output";
import * as utilities from "./utilities";

export class UpsConfig extends pulumi.CustomResource {
	/**
	 * Get an existing UpsConfig resource's state with the given name, ID, and optional extra
	 * properties used to qualify the lookup.
	 *
	 * @param name The _unique_ name of the resulting resource.
	 * @param id The _unique_ provider ID of the resource to lookup.
	 * @param state Any extra arguments used during the lookup.
	 * @param opts Optional settings to control the behavior of the CustomResource.
	 */
	public static get(
		name: string,
		id: pulumi.Input<pulumi.ID>,
		state?: UpsConfigState,
		opts?: pulumi.CustomResourceOptions,
	): UpsConfig {
		return new UpsConfig(name, <any>state, { ...opts, id: id });
	}

	/** @internal */
	public static readonly __pulumiType = "truenas:index/upsConfig:UpsConfig";

	/**
	 * Returns true if the given object is an instance of UpsConfig.  This is designed to work even
	 * when multiple copies of the Pulumi SDK have been loaded into the same process.
	 */
	public static isInstance(obj: any): obj is UpsConfig {
		if (obj === undefined || obj === null) {
			return false;
		}
		return obj["__pulumiType"] === UpsConfig.__pulumiType;
	}

	/**
	 * UPS description.
	 */
	public declare readonly description: pulumi.Output<string>;
	/**
	 * UPS driver name.
	 */
	public declare readonly driver: pulumi.Output<string>;
	/**
	 * UPS identifier name.
	 */
	public declare readonly identifier: pulumi.Output<string>;
	/**
	 * UPS mode (MASTER or SLAVE).
	 */
	public declare readonly mode: pulumi.Output<string>;
	/**
	 * UPS port or device path.
	 */
	public declare readonly port: pulumi.Output<string>;
	/**
	 * Remote UPS host (for SLAVE mode).
	 */
	public declare readonly remotehost: pulumi.Output<string>;
	/**
	 * Remote UPS port.
	 */
	public declare readonly remoteport: pulumi.Output<number>;
	/**
	 * Shutdown mode (BATT or LOWBATT).
	 */
	public declare readonly shutdown: pulumi.Output<string>;
	/**
	 * Shutdown timer in seconds (0-3600).
	 */
	public declare readonly shutdowntimer: pulumi.Output<number>;
	public declare readonly timeouts: pulumi.Output<
		outputs.UpsConfigTimeouts | undefined
	>;

	/**
	 * Create a UpsConfig resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 * @param opts A bag of options that control this resource's behavior.
	 */
	constructor(
		name: string,
		args?: UpsConfigArgs,
		opts?: pulumi.CustomResourceOptions,
	);
	constructor(
		name: string,
		argsOrState?: UpsConfigArgs | UpsConfigState,
		opts?: pulumi.CustomResourceOptions,
	) {
		const resourceInputs: pulumi.Inputs = {};
		opts = opts || {};
		if (opts.id) {
			const state = argsOrState as UpsConfigState | undefined;
			resourceInputs["description"] = state?.description;
			resourceInputs["driver"] = state?.driver;
			resourceInputs["identifier"] = state?.identifier;
			resourceInputs["mode"] = state?.mode;
			resourceInputs["port"] = state?.port;
			resourceInputs["remotehost"] = state?.remotehost;
			resourceInputs["remoteport"] = state?.remoteport;
			resourceInputs["shutdown"] = state?.shutdown;
			resourceInputs["shutdowntimer"] = state?.shutdowntimer;
			resourceInputs["timeouts"] = state?.timeouts;
		} else {
			const args = argsOrState as UpsConfigArgs | undefined;
			resourceInputs["description"] = args?.description;
			resourceInputs["driver"] = args?.driver;
			resourceInputs["identifier"] = args?.identifier;
			resourceInputs["mode"] = args?.mode;
			resourceInputs["port"] = args?.port;
			resourceInputs["remotehost"] = args?.remotehost;
			resourceInputs["remoteport"] = args?.remoteport;
			resourceInputs["shutdown"] = args?.shutdown;
			resourceInputs["shutdowntimer"] = args?.shutdowntimer;
			resourceInputs["timeouts"] = args?.timeouts;
		}
		opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
		super(
			UpsConfig.__pulumiType,
			name,
			resourceInputs,
			opts,
			false /*dependency*/,
			utilities.getPackage(),
		);
	}
}

/**
 * Input properties used for looking up and filtering UpsConfig resources.
 */
export interface UpsConfigState {
	/**
	 * UPS description.
	 */
	description?: pulumi.Input<string | undefined>;
	/**
	 * UPS driver name.
	 */
	driver?: pulumi.Input<string | undefined>;
	/**
	 * UPS identifier name.
	 */
	identifier?: pulumi.Input<string | undefined>;
	/**
	 * UPS mode (MASTER or SLAVE).
	 */
	mode?: pulumi.Input<string | undefined>;
	/**
	 * UPS port or device path.
	 */
	port?: pulumi.Input<string | undefined>;
	/**
	 * Remote UPS host (for SLAVE mode).
	 */
	remotehost?: pulumi.Input<string | undefined>;
	/**
	 * Remote UPS port.
	 */
	remoteport?: pulumi.Input<number | undefined>;
	/**
	 * Shutdown mode (BATT or LOWBATT).
	 */
	shutdown?: pulumi.Input<string | undefined>;
	/**
	 * Shutdown timer in seconds (0-3600).
	 */
	shutdowntimer?: pulumi.Input<number | undefined>;
	timeouts?: pulumi.Input<inputs.UpsConfigTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a UpsConfig resource.
 */
export interface UpsConfigArgs {
	/**
	 * UPS description.
	 */
	description?: pulumi.Input<string | undefined>;
	/**
	 * UPS driver name.
	 */
	driver?: pulumi.Input<string | undefined>;
	/**
	 * UPS identifier name.
	 */
	identifier?: pulumi.Input<string | undefined>;
	/**
	 * UPS mode (MASTER or SLAVE).
	 */
	mode?: pulumi.Input<string | undefined>;
	/**
	 * UPS port or device path.
	 */
	port?: pulumi.Input<string | undefined>;
	/**
	 * Remote UPS host (for SLAVE mode).
	 */
	remotehost?: pulumi.Input<string | undefined>;
	/**
	 * Remote UPS port.
	 */
	remoteport?: pulumi.Input<number | undefined>;
	/**
	 * Shutdown mode (BATT or LOWBATT).
	 */
	shutdown?: pulumi.Input<string | undefined>;
	/**
	 * Shutdown timer in seconds (0-3600).
	 */
	shutdowntimer?: pulumi.Input<number | undefined>;
	timeouts?: pulumi.Input<inputs.UpsConfigTimeouts | undefined>;
}
