---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newt-system

resources:
  - newt.externalsecret.yaml

  # Include security policies
  - security/

helmCharts:
  - name: newt
    repo: https://charts.fossorial.io
    version: 1.3.0
    releaseName: newt
    namespace: newt-system
    valuesInline:
      newtInstances:
        - name: "main-tunnel"
          auth:
            existingSecretName: "newt-credentials"
            keys:
              endpointKey: "PANGOLIN_ENDPOINT"
              idKey: "NEWT_ID"
              secretKey: "NEWT_SECRET"
          enabled: true

labels:
  - pairs:
      app.kubernetes.io/name: newt
    includeTemplates: true
    includeSelectors: true

images:
  # renovate: datasource=docker depName=docker.io/fosrl/newt
  - name: docker.io/fosrl/newt
    newTag: 1.12.2@sha256:b1af30d7031e3019fda2b3861944704d9f41639aa796f58eeb7074c2b5f0f166
