---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newt-system

resources:
  - newt.externalsecret.yaml

  # Include security policies
  - security/

helmCharts:
  - repo: https://charts.fossorial.io
    name: newt
    version: 1.5.0

    releaseName: newt
    namespace: newt-system

    valuesInline:
      newtInstances:
        - name: "main-tunnel"
          auth:
            existingSecretName: "newt-credentials"
            keys:
              endpointKey: "PANGOLIN_ENDPOINT"
              idKey: "NEWT_ID"
              secretKey: "NEWT_SECRET"
          enabled: true

labels:
  - pairs:
      app.kubernetes.io/name: newt
    includeTemplates: true
    includeSelectors: true

images:
  # renovate: datasource=docker depName=docker.io/fosrl/newt
  - name: docker.io/fosrl/newt
    newName: oci.chezmoi.sh/docker.io/fosrl/newt
    newTag: 1.12.5@sha256:3c009663332145cae39b940b07857469038d5e9d71aacb1497e78795ba4e3b9b
