---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newt-system

resources:
  - newt.externalsecret.yaml

  # Include security policies
  - security/

helmCharts:
  - name: newt
    repo: https://charts.fossorial.io
    version: 1.3.0
    releaseName: newt
    namespace: newt-system
    valuesInline:
      newtInstances:
        - name: "main-tunnel"
          auth:
            existingSecretName: "newt-credentials"
            keys:
              endpointKey: "PANGOLIN_ENDPOINT"
              idKey: "NEWT_ID"
              secretKey: "NEWT_SECRET"
          enabled: true

labels:
  - pairs:
      app.kubernetes.io/name: newt
    includeTemplates: true
    includeSelectors: true

images:
  # renovate: datasource=docker depName=docker.io/fosrl/newt
  - name: docker.io/fosrl/newt
    newTag: 1.11.0@sha256:ea9e2bc53850d4a8b2c6019d97172a2b3e3cb1a15412babb4a0f4adc522f4a79
