# ─────────────────────────────────────────────────────────────────────────────
# Omni Infrastructure Provider for Proxmox — NixOS service module
# ─────────────────────────────────────────────────────────────────────────────
# Runs omni-infra-provider-proxmox, enabling Omni to provision Talos VMs
# directly on Proxmox via its REST API.
#
# The provider authenticates with two parties:
#   • Proxmox — username/password against the Proxmox API
#   • Omni    — an "infrastructure provider key" generated by Omni on first
#               registration (Settings → Infrastructure Providers → New)
#
# Both secrets are forwarded from flake.nix via _module.args at build time:
#   proxmoxPassword          → baked into /etc/infra-provider/provider.yaml
#   omniServiceAccountKey    → written to /etc/infra-provider/secrets as
#                              OMNI_SERVICE_ACCOUNT_KEY and loaded at runtime
#                              via EnvironmentFile
#
# First-time setup (two-phase deployment):
#   Phase 1 — Proxmox creds only:
#     Fill secrets/proxmox.sops.env (PROXMOX_PASSWORD), rebuild + deploy.
#     The service starts but cannot register until phase 2.
#   Phase 2 — Omni key:
#     In Omni UI: Settings → Infrastructure Providers → Create.
#     Copy the generated key. Run `mise run lxc:secrets:omni`, rebuild + deploy.
#
# Build arg forwarded from flake.nix via _module.args:
#   proxmoxPassword       — Proxmox API password (proxmox.sops.env)
#   omniServiceAccountKey — Omni infra provider key (omni.sops.env)
# ─────────────────────────────────────────────────────────────────────────────
{ config, lib, pkgs, proxmoxPassword ? "", omniServiceAccountKey ? "", ... }:

let
  cfg = config.services.omniInfraProviderProxmox;
  inherit (lib)
    mkEnableOption mkOption mkIf mkDefault mkForce types
    literalExpression getExe escapeShellArg boolToString;
in
{
  options.services.omniInfraProviderProxmox = {
    enable = mkEnableOption "Omni Infrastructure Provider for Proxmox";

    # ── Binary ──────────────────────────────────────────────────────────────
    # renovate: datasource=github-releases depName=siderolabs/omni-infra-provider-proxmox
    version = mkOption {
      type = types.str;
      default = "v0.1.0";
      description = "Release version to fetch from GitHub.";
    };

    hashes = mkOption {
      type = types.attrsOf types.str;
      description = "SRI hashes keyed by system. Bump alongside version.";
      default = {
        "x86_64-linux" = "sha256-8FLlc+oBgC1vGuGNaHnvLQYLzIS6HO8M5bzboNbzr0k=";
        "aarch64-linux" = "sha256-rGhsjR4OjhkPd4vrxgKjC+03U/5Cyd6KP9iFxwfcm/M=";
      };
    };

    package = mkOption {
      type = types.package;
      defaultText = literalExpression "derived from version + hashes";
    };

    # ── Provider identity ────────────────────────────────────────────────────
    id = mkOption {
      type = types.str;
      default = "proxmox";
      description = "Infrastructure provider ID as registered in Omni (--id flag). Must match the ID used when creating the provider in Omni UI.";
    };

    # ── Omni connection ──────────────────────────────────────────────────────
    omniApiEndpoint = mkOption {
      type = types.str;
      example = "https://omni.example.com/";
      description = "Omni API endpoint URL (trailing slash required).";
    };

    # ── Proxmox connection ───────────────────────────────────────────────────
    proxmox = {
      url = mkOption {
        type = types.str;
        example = "https://pve.lan:8006/api2/json";
        description = "Proxmox REST API URL.";
      };

      username = mkOption {
        type = types.str;
        default = "root";
        description = ''
          Proxmox API username WITHOUT the realm suffix — the realm is sent
          separately via proxmox.realm. Appending @realm here (e.g. "omni@pve"
          with realm = "pve") produces username=omni@pve&realm=pve, which
          Proxmox rejects as a double-realm authentication failure.
        '';
      };

      realm = mkOption {
        type = types.str;
        default = "pam";
        description = "Proxmox authentication realm (sent as a separate field, not as a username suffix).";
      };

      insecureSkipVerify = mkOption {
        type = types.bool;
        default = false;
        description = "Skip TLS verification for the Proxmox API (use only with self-signed certs).";
      };
    };
  };

  config = mkIf cfg.enable {

    # ── Package default ────────────────────────────────────────────────────
    services.omniInfraProviderProxmox.package = mkDefault (
      let
        system = pkgs.stdenv.hostPlatform.system;
        archMap = { "x86_64-linux" = "amd64"; "aarch64-linux" = "arm64"; };
        arch = archMap.${system}
          or (throw "omni-infra-provider-proxmox: unsupported system ${system}");
        hash = cfg.hashes.${system}
          or (throw "omni-infra-provider-proxmox: no hash for ${system}");
      in
      pkgs.stdenvNoCC.mkDerivation {
        pname = "omni-infra-provider-proxmox";
        version = cfg.version;

        src = pkgs.fetchurl {
          url = "https://github.com/siderolabs/omni-infra-provider-proxmox/releases/download/${cfg.version}/omni-infra-provider-proxmox-linux-${arch}";
          inherit hash;
        };

        dontUnpack = true;
        dontConfigure = true;
        dontBuild = true;

        installPhase = ''
          runHook preInstall
          install -Dm755 "$src" "$out/bin/omni-infra-provider-proxmox"
          runHook postInstall
        '';

        meta = with lib; {
          description = "Omni infrastructure provider for Proxmox (upstream binary)";
          homepage = "https://github.com/siderolabs/omni-infra-provider-proxmox";
          changelog = "https://github.com/siderolabs/omni-infra-provider-proxmox/releases/tag/${cfg.version}";
          license = licenses.bsl11;
          platforms = [ "x86_64-linux" "aarch64-linux" ];
          mainProgram = "omni-infra-provider-proxmox";
          sourceProvenance = [ sourceTypes.binaryNativeCode ];
        };
      }
    );

    # ── Service user ────────────────────────────────────────────────────────
    users.users.infra-provider = {
      isSystemUser = true;
      group = "infra-provider";
      description = "Omni infra provider for Proxmox service account";
    };
    users.groups.infra-provider = { };

    # ── Proxmox YAML config ─────────────────────────────────────────────────
    # The password is baked at Nix eval time from _module.args (same pattern
    # as dex.nix). When proxmoxPassword is empty (pure build), the provider
    # starts but fails to authenticate — expected for a secrets-less build.
    environment.etc."infra-provider/provider.yaml" = {
      text = ''
        proxmox:
          url: ${cfg.proxmox.url}
          username: ${cfg.proxmox.username}
          password: ${proxmoxPassword}
          realm: ${cfg.proxmox.realm}
          insecureSkipVerify: ${boolToString cfg.proxmox.insecureSkipVerify}
      '';
      mode = "0400";
      user = "infra-provider";
      group = "infra-provider";
    };

    # ── Systemd service ─────────────────────────────────────────────────────
    # OMNI_SERVICE_ACCOUNT_KEY comes from EnvironmentFile (/etc/infra-provider/secrets,
    # written by modules/secrets.nix). When the file is absent, the service starts
    # but fails to connect to Omni — expected during phase-1 deployment.
    systemd.services.omni-infra-provider-proxmox =
      let
        startScript = pkgs.writeShellScript "infra-provider-start" ''
          exec ${getExe cfg.package} \
            --id=${escapeShellArg cfg.id} \
            --omni-api-endpoint=${escapeShellArg cfg.omniApiEndpoint} \
            --omni-service-account-key="''${OMNI_SERVICE_ACCOUNT_KEY:-}" \
            --config-file=/etc/infra-provider/provider.yaml
        '';
      in
      {
        description = "Omni Infrastructure Provider for Proxmox";
        documentation = [ "https://github.com/siderolabs/omni-infra-provider-proxmox" ];
        wantedBy = [ "multi-user.target" ];
        after = [ "network-online.target" ];
        wants = [ "network-online.target" ];

        serviceConfig = {
          ExecStart = startScript;
          User = "infra-provider";
          Group = "infra-provider";
          Type = "simple";
          Restart = "on-failure";
          RestartSec = "10s";

          # Secrets file written by modules/secrets.nix. The `-` prefix makes
          # systemd tolerate the missing file (phase-1 deploy without Omni key).
          EnvironmentFile = "-/etc/infra-provider/secrets";

          NoNewPrivileges = true;
          RestrictSUIDSGID = true;
          RestrictRealtime = true;
          LockPersonality = true;
          SystemCallArchitectures = "native";
        };
      };

    # No inbound ports — the provider connects out to Omni and Proxmox only.
    networking.firewall.enable = mkDefault true;
  };
}
