// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ResourceHeader {
    /**
     * Header name.
     */
    name: pulumi.Input<string>;
    /**
     * Header value.
     */
    value: pulumi.Input<string>;
}

export interface TargetHcHeader {
    /**
     * Header name.
     */
    name: pulumi.Input<string>;
    /**
     * Header value.
     */
    value: pulumi.Input<string>;
}
