---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-database-url
spec:
  data:
    - secretKey: postgresql_username
      remoteRef:
        key: lungmen.akn/open-webui/database/postgresql
        property: username
    - secretKey: postgresql_password
      remoteRef:
        key: lungmen.akn/open-webui/database/postgresql
        property: password
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    template:
      data:
        username: open-webui
        password: "{{ .postgresql_password }}"
        database_url: "postgresql://open-webui:{{ .postgresql_password }}@postgres-apps-secured-rw.databases:5432/open-webui"
