#!/bin/env bash
# Copyright (C) 2024 Alexandre Nicolaie (xunleii@users.noreply.github.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------
# mise alias="init"
# mise description="Install the development environment required to work on the project."

# -- Install all required tools
set -x
mise use --global nodejs@lts rust@latest
{ set +x; } 2>/dev/null

command -v npm &>/dev/null || (echo >&2 'Node.js runtime is required to build the project (mise seems not properly configured on your device)' && exit 1)
command -v cargo &>/dev/null || (echo >&2 'Rust runtime is required to build the project (mise seems not properly configured on your device)' && exit 1)

mise install
