---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-database-credentials
spec:
  dataFrom:
    - extract:
        key: lungmen.akn/n8n/database/postgresql
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    template:
      engineVersion: v2
      data:
        # n8n expects these variables or a connection string
        username: n8n
        password: "{{ .password }}"
        # For convenience, also provide the connection URI
        uri: "postgres://n8n:{{ .password }}@postgres-apps-rw.databases.svc:5432/n8n"
