---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-mcp-auth
  namespace: n8n
spec:
  data:
    - secretKey: token
      remoteRef:
        key: lungmen.akn/n8n/mcp/auth
        property: access_token
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    name: n8n-mcp-auth
    template:
      engineVersion: v2
      data:
        token: "Bearer {{ .token }}"
