---
# Ansible inventory for Kazimierz.AKN VPS
# Host: kazimierz-pangolin (OCI Always Free, eu-paris-1)

all:
  hosts:
    kazimierz:
      ansible_host: localhost
      ansible_connection: local
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3
      ara_api_server: http://localhost:8000
