oauth2_proxy_env: ENC[AES256_GCM,data:gabzgz8iWhOlwnta6Qjdmx0XZhWb6/8b2i+h15uh5NI2eyIg/7kK91Vk+0jRwIcamJb6+TmXv4m18HcenEDvRF4Ge2+7Tx7HF4Z4Oim+82Inp6g8zxc0GzzilxfHm1fum2j2l4xn41qUxZEe0fRbk1AHZjlkh1nuhJwySoTMwgfPGvv0,iv:+zw+nDENl/f6gxdnVgxcLOznrRXP6274n/sZjl3XvNs=,tag:S+ZjgZaUGQLJWRhqfyR8xw==,type:str]
restic_password: ENC[AES256_GCM,data:c22izS+UZWzxcHB0VepC1qZa6ZGtcA8vPsInnKh7PoCmc4lV0RpOCzuaSBw=,iv:FyYIeWe28qwfQnMmwUTFRHQmHIEJxBKuzZd/T5lxB9o=,tag:jNdWSrwulW9l+RlfYICvzA==,type:str]
restic_b2_env: ENC[AES256_GCM,data:uSYwR/2ag4AlhjFb4UR0F6pqMgeYX1ovgoACfyZm7TVRby3siN4ctDc/mgvqvMEyYFm5WGdKeTo9rH2EoQAylZWJxuC7NtAIR5/EmagRc9XN3HJkhmYQ9BEvJZE3C0AcS8A=,iv:AeD4bZ45EYhuR5Wqjyr2ZONOGlr6RWQBOHAnCVEdfXQ=,tag:aJsS+J+6L+Q6HmBXNreEmQ==,type:str]
tailscale_authkey: ENC[AES256_GCM,data:ILOEAjw5ybH0ChzSh3x5JDkr18Y2lWjrCJ5Ge2vRnKr1nrkx1D5IliCSXADobHgMEBlVZIVsWR1M6/GQEA==,iv:xuuwNwJVt4XrIK7yYdnGLE33ZXqxbUwSHm6ujpYDxv0=,tag:uaOstmbWF1RijG/TP5o9JQ==,type:str]
#ENC[AES256_GCM,data:JiROVwVe5/W5JZVpm/oopGRE4MsJ/cGjQIdljfjUWPV+afuXxQyTCOTmUEP7KFE2mDxLjsxDHjccre9uNlXpWDTsChfE7Pc=,iv:/ISMn2HkzkGR9M3bBoPIQZH5PLm6UBuOdlps7J36GvQ=,tag:ykTySAdpWnmCpHCbqWUnKg==,type:comment]
wings_uuid: ENC[AES256_GCM,data:GckxXas6+sRk1B24snkbp7Q+Xe3vp+tFdC01SdXcNmrEOHx3,iv:gF/TfE8IF9gF2IH35wWw64epx0QP6gYuGZn3dtuOMq8=,tag:UN9nkUGP33liB14CqDCVLw==,type:str]
wings_token_id: ENC[AES256_GCM,data:G6VjpKWj4K3gSYUdFrYVoQ==,iv:gq+EuGPRKUpUPddQCIWUunueCRDQXRHrAaJsluHGzpg=,tag:tf4Xz4VT+QvLw30eyw3iQw==,type:str]
wings_token: ENC[AES256_GCM,data:lqHXhFnXX3sEdUmDAvIAPCMEjZ5phmQVbFmkEm6Wu1u/0vzvsbgR1a35FEhFNW5PidsNr830aW9Rbb4v5U+sLw==,iv:fBeJjAz0/+pxp3JehVmyMxGCuyCLqo2Rg/3rMkb+mHI=,tag:cKaCytHHNyO0Nix+OYwTiA==,type:str]
#ENC[AES256_GCM,data:hP9eKorISJKVV2Di8M9Wl+U0rLlUR/DeAbj5+HIXmLBgOf4ZmCO8qs01kFggALD8QBl3/26IyXQY1sJR8wp3odYmYVJgwkUy4wotP6sF0A==,iv:ly02TjykXhyHLOWH/Y0IqQzaYNe8ThRhns5i7vKmHTc=,tag:NPVoefNlusF5ytgKB23qjA==,type:comment]
oauth_pocketid_client_id: ENC[AES256_GCM,data:VYZPBbcVYy1Z9PetT8o1LidtanpLRKojB9pG0FtwnqEuHHMc,iv:1TbDt6GGikdUIDN3ePjGrqqrffLLjGLq+7M+2hNTTSQ=,tag:BU09bMLRcX6EjEVZqHFugw==,type:str]
oauth_pocketid_client_secret: ENC[AES256_GCM,data:aWPKDkPYPw60PHzucU4LTeU2n5Ax/Wbq6zX5Q0caTDo=,iv:cXkDj2/CHRBBUruV2t8s2cFuQsWHuOoTLchkxuDUwzk=,tag:TfSJ+9g1u31ry4l1hOeMlg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRG5oMzFiTG5KbVppNVpC
            TDdQakx0S01JK2w3QTJPdGlHdUVlQW4rWUNzCnhuem0wZnpBL1Rxc1U3Ly9naDYv
            OWVhMUJ2aE9MQWs0cXdxK2RLVFlUSWMKLS0tIGg0LytrVXNMWS9IRTZHZkVVQUxI
            d0FMT2xOR283N2QrSGVtWmIzWHYyOEEK4rwjOC7R7Qp/+PC7Upc2StNp4cGybLtB
            LvxoPCFWzXZ/SrO2ICZI0s6vKmdw2VzoMrSz+N1sjkuCqYv3tMhZ7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fj0yj3na3n5udfjmnxfwrlkp80tvj49w80wh699x33dh48clnvnshtjxe9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSk5zdldScHh0L1ArcUhO
            OFJvc3B5OGczSjNla2FReVBKNHhCRlJxc2dFCm9BdVpSay9KUjBJcXg3M1Rtc3Jm
            c25zTWJlWjdTSnZOUU9JNzhONVRvdEUKLS0tIGljT084b0F0Wjl2ZmROSm0rSVBY
            ZUZ1YjViLzFRRXdKdGFEMTBEQXBmWTQKMhU9GlbW1CScDtGBM2rBFbtwI9fWKuVg
            IR45Qefcf4+V92deLjxgrZLFnU2Vw13Rh99vjGgNT9GBH5eDi/C4ig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cpyfsxgl6eer583rhnralx54h60xjjpr3up7hgcd4wc4d44xjcaqdklwxp
    lastmodified: "2026-10-05T10:42:18Z"
    mac: ENC[AES256_GCM,data:erTdqvicAjIZe7RhJCQdPpzM/kvPXWG2X2XFsH2hCfDjL9VLVtm7LbSSNqjApxUDlo/FY+TsHNrUYgWpKv4mV+hAbTig5SIUujoEj8hE+xdOX4DC/yLZHM2RXCMiIGAQvStIkMQcFrsIj+RIE9T8aC9xDpe9SIpJGPPFgKVTmhw=,iv:OMnMWm3WCsfqCeYl5VtXYAF6Jt2MJXACdXjg3GeXGAQ=,tag:vEUuxrRAgiUXKipIecqNPQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
