apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: letsencrypt-issuer-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    name: letsencrypt-issuer-credentials
  data:
    - secretKey: api-token # trunk-ignore(checkov/CKV_SECRET_6): false positive; this is a reference key name, not a secret value.
      remoteRef:
        key: shared/third-parties/cloudflare/iam/rhodes.akn/cert-manager-rw
        property: api_token
    - secretKey: email
      remoteRef:
        key: shared/certificates/certificate-authorities/letsencrypt/account
        property: email
