apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - open-terminal.deployment.yaml
  - open-webui.configuration.configmap.yaml
  - open-webui.configuration.externalsecret.yaml
  - open-webui.deployment.yaml
  - open-webui.httproute.yaml
  - open-webui.ingress.yaml
  - open-webui.storage.yaml
  - pipelines.deployment.yaml
  - playwright.deployment.yaml
  - tika.deployment.yaml

images:
  # renovate: datasource=docker depName=ghcr.io/open-webui/open-webui
  - name: ghcr.io/open-webui/open-webui
    newTag: v0.8.8@sha256:b478adc66210c1effe147d3e4a0d8845c0418b136ca14c314b9d83a087ad1c1f
  # renovate: datasource=docker depName=ghcr.io/open-webui/pipelines
  - name: ghcr.io/open-webui/pipelines
    newTag: main@sha256:b48e9bc338ce2be0acfbeff01810db72408a12f07739f9e3879c1f2b00952d6e
  # renovate: datasource=docker depName=apache/tika
  - name: apache/tika
    newTag: 3.2.3.0-full@sha256:21d8052de04e491ccf66e8680ade4da6f3d453a56d59f740b4167e54167219b7

  # renovate: datasource=docker depName=ghcr.io/open-webui/open-terminal
  - name: ghcr.io/open-webui/open-terminal
    newTag: latest
