apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  # OpenWebUI official Helm chart
  - name: open-webui
    releaseName: open-webui
    repo: https://helm.openwebui.com
    version: 12.8.1
    valuesFile: open-webui.helmvalues/default.yaml

resources:
  - open-webui.configuration.externalsecret.yaml
  - open-webui.httproute.yaml
  - open-webui.ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: open-webui
    includeTemplates: true
    includeSelectors: true

images:
  # renovate: datasource=docker depName=ghcr.io/open-webui/open-webui
  - name: ghcr.io/open-webui/open-webui
    newTag: v0.8.8@sha256:b478adc66210c1effe147d3e4a0d8845c0418b136ca14c314b9d83a087ad1c1f
