apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pipelines
  labels:
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/name: pipelines
    app.kubernetes.io/component: pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
