apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-webui-pipelines
  labels:
    app.kubernetes.io/component: pipelines
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/name: pipelines
    app.kubernetes.io/version: alpha
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-webui-sa
  labels:
    app.kubernetes.io/component: open-webui
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/version: 0.8.8
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-webui-tika
  labels:
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/name: tika
    app.kubernetes.io/version: 3.2.3.0-full
