apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: searxng-secret-generator
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/component: searxng
spec:
  length: 32
  digits: 10
  symbols: 0
  symbolCharacters: ""
  noUpper: false
  allowRepeat: true
