---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: pocket-id-database
  name: pocket-id-20260530
spec:
  bootstrap:
    recovery:
      source: 2026-01-11T10:37:12.165Z
  description: PostgreSQL database dedicated to pocket-id
  enablePDB: false
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: default
    major: 18
  instances: 2
  managed:
    roles:
      - name: pocket_id
        connectionLimit: -1
        comment: PostgreSQL role for pocket_id
        ensure: present
        inherit: true
        login: true
        passwordSecret:
          name: pocket-id-database-pocket-id
  plugins:
    - enabled: true
      isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: selfhosted
        serverName: 01KSWFKGPZMJVTX8CNTEK8CYXT # 2026-05-30T13:01:34.815Z
  postgresql:
    parameters:
      # Limit WAL retention to avoid DB crash due to storage bloat
      max_slot_wal_keep_size: 900MB
      max_wal_size: 100MB
  storage:
    size: 250Mi
  walStorage:
    size: 1Gi

  externalClusters:
    - name: 2026-01-11T10:37:12.165Z
      plugin:
        enabled: true
        isWALArchiver: false
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: selfhosted
          serverName: 01KEPA38352GYQHNKTFYPA4HE1 # 2026-01-11T10:37:12.165Z
