// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { OidcClientsArgs } from "./oidcClients";
export type OidcClients = import("./oidcClients").OidcClients;
export const OidcClients: typeof import("./oidcClients").OidcClients = null as any;
utilities.lazyLoad(exports, ["OidcClients"], () => require("./oidcClients"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "pocket-id-api:oidc:OidcClients":
                return new OidcClients(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("pocket-id-api", "oidc", _module)
