apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - network-policy.default-hardened.yaml
  - network-policy.allow-operator-to-kubernetes-api.yaml
  - network-policy.allow-operator-to-cnpg-clusters.yaml
  - network-policy.allow-webhook-from-kubernetes-api.yaml
