apiVersion: v1
kind: Secret
metadata:
  annotations:
    cnpg.io/description: CNPG S3 credentials
    security.chezmoi.sh/description: |
      Because this application is a critical brick for the entire infrastructure, we
      needs to store somewhere all credentials safely without depending on the Vault
      application being up and running. Thus we store these credentials in an encrypted
      Kubernetes Secret managed by SOPS and KSOPS.
  name: cnpg-backup-credentials
type: Opaque
stringData:
  access_key_id: ENC[AES256_GCM,data:c1gSmwdyE46MwvDi9FMca56kHIM62E5K64E=,iv:lCWmWs1CcpSyJzlow/87d+rRHpgooAkn+YBJh9X1Dok=,tag:QQv5UapLiMzNMN6RtxxIvQ==,type:str]
  access_secret_key: ENC[AES256_GCM,data:PxF9FpYe0UAbSUMELOfMhsznS8PY6VoYIKKGMEJHvocjDNI+/oBeuw9wI4PqGRClIASvKMJTGdCozxfighGJHg==,iv:/3uSQkpclnJwXReLhdzd/I0eUShksXXgcz0ck0AtqDg=,tag:r4R1trEPxYyg+lbsAcrzeQ==,type:str]
  endpoint_url: ENC[AES256_GCM,data:iMGK5yeKUriGbm2xQrKhcHTVFy15,iv:/blj02mUKEEjYa/V0ywlGjlXY0e8tVNLrGc278kH6WU=,tag:sHI5ws303MZowWtBEq+MLw==,type:str]
  region: ENC[AES256_GCM,data:hCmCQagwyk0=,iv:nDUSR2tnYArL4lQtEqOvnhxeHuIhgJ8F6pKMRF8KQR0=,tag:2Gq8ooP0P4Wg3Z7fBJ4vZg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZXc4c0M4bVphOVNxZnpN
        OGRPRlFaMm41MzF5K2xEU3ZoSDNidnFjL0NzClZFeHlQOXAzTy9DcHphUnlXMTdD
        dEhJa1VKckdpZXcxNHFNT2xxaEhmNXcKLS0tIEdscWpsTjl3VFpEMkVQK05RTGR6
        YjMxQzIvUVRqMVFxY2ZXdWFPd2dybzAKuC7xgYmD1tVwVjNcOyWIkY/w3tWM6X2T
        jriqih3N8EWbds4eenCHEGonTqfEx6nmeVXlqKpeBMbXxMEQxMJWiw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fj0yj3na3n5udfjmnxfwrlkp80tvj49w80wh699x33dh48clnvnshtjxe9
  encrypted_regex: ^(stringData|data)$
  lastmodified: "2026-07-16T20:34:35Z"
  mac: ENC[AES256_GCM,data:Veso/7rhlwb2grYeuebrhGCYAjr5xDOFUp8kB0Ekija9kitrzuF8/zS08nArFgyx9cY/SOZBrUyVaiim3lauxLpRzFYro+i+T8EPWB/scfbiqlicQeWPwwadZsg2DiFDcb6mElhvDFSmouZFR3iQbIdWNLsBfJz+PTBZI1FhGrs=,iv:V1QtmCy1dw1djVP2FZJoDtw/aCjtxPr1PaMQA3tDGwY=,tag:3DSgApd9s+3ZvYIOdwkplw==,type:str]
  version: 3.11.0
