---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-database-immich
spec:
  dataFrom:
    - extract:
        key: lungmen.akn/immich/database/postgresql
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    name: immich-database-immich
    template:
      data:
        username: immich
        password: "{{ .password }}"
