---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoriametrics
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: https://data.o11y.chezmoi.sh/metrics
    isDefault: true
    editable: false
