---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newt-system

resources:
  - network-policy.allow-intra-namespace.yaml
  - network-policy.allow-newt-to-pangolin.yaml
  - network-policy.allow-newt-to-pocket-id.yaml
