---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  annotations:
    policy.networking.k8s.io/description: |
      Permits intra-namespace communication in the proxmox-system namespace. Access to the
      Kubernetes API and the Proxmox VE API is granted by the other policies in this directory,
      not here.
  name: allow-intra-namespace
  namespace: proxmox-system
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: proxmox-system
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: proxmox-system
