apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  annotations:
    policy.networking.k8s.io/description: |
      Allows all mutualized PostgreSQL clusters to connect to
      S3-compatible storage for backups via CloudNative-PG.
  name: allow-cnpg-databases-to-s3-backup
  namespace: databases
spec:
  endpointSelector:
    - matchExpressions:
        - key: cnpg.io/cluster
          operator: Exists
  egress:
    - toFQDNs:
        - matchName: s3.chezmoi.sh
      toPorts:
        - ports:
            - port: "9000"
              protocol: TCP
