module.exports = {
	plugins: [
		"removeDoctype",
		"removeXMLProcInst",
		"removeComments",
		"removeDeprecatedAttrs",
		"removeMetadata",
		"removeEditorsNSData",
		"cleanupAttrs",
		"mergeStyles",
		"inlineStyles",
		"minifyStyles",
		"cleanupIds",
		"removeUselessDefs",
		"cleanupNumericValues",
		"convertColors",
		// "removeUnknownsAndDefaults",
		"removeNonInheritableGroupAttrs",
		"removeUselessStrokeAndFill",
		"cleanupEnableBackground",
		// "removeHiddenElems",
		"removeEmptyText",
		"convertShapeToPath",
		"convertEllipseToCircle",
		"moveElemsAttrsToGroup",
		"moveGroupAttrsToElems",
		// "collapseGroups",
		// "convertPathData",
		"convertTransform",
		"removeEmptyAttrs",
		// "removeEmptyContainers",
		// "mergePaths",
		"removeUnusedNS",
		"sortAttrs",
		"sortDefsChildren",
		"removeDesc",
	],
};
