---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - network-policy.allow-spoolman-from-cilium-gateway.yaml
  - network-policy.allow-spoolman-to-internet.yaml
  - network-policy.allow-spoolman-to-databases.yaml
  - network-policy.default-hardened.yaml
