{ config, lib, pkgs, ... }:
{
  system.stateVersion = "26.05";
  networking.hostName = "kazimierz-akn";
  networking.domain = "chezmoi.sh";
  time.timeZone = "UTC";

  # Boot loader, disk layout and console live in platforms/ (selected by the flake output).

  # 6 GB RAM: compressed swap as a safety net.
  zramSwap.enable = true;

  # --- Network -----------------------------------------------------------------
  networking.useDHCP = true;

  # Resolvers independent of the cloud provider's own DNS (same intent as the old `system_setup` role). glibc only
  # honours the first three entries.
  networking.nameservers = [ "9.9.9.9" "149.112.112.112" "1.1.1.1" ];
  networking.dhcpcd.extraConfig = "nohook resolv.conf";

  networking.firewall = {
    enable = true;
    allowedTCPPorts = [ 80 443 ];
    # Gerbil: WireGuard site tunnels (Newt) and client tunnels. Same ports in the OCI NSG (Pulumi stack).
    allowedUDPPorts = [ 51820 21820 ];
  };

  services.openssh = {
    enable = true;
    # Port 22 is open in the host firewall; who can reach it is decided by the OCI NSG (closed by default, see the
    # `unsecure` Pulumi toggle), so SSH goes through Tailscale unless that toggle is on.
    openFirewall = true;
    settings = {
      PasswordAuthentication = false;
      KbdInteractiveAuthentication = false;
      PermitRootLogin = "prohibit-password";
      X11Forwarding = false;
      AllowTcpForwarding = false;
      MaxAuthTries = 3;
      ClientAliveInterval = 300;
      ClientAliveCountMax = 2;
    };
  };
  # Same key as the `ssh_authorized_keys` Pulumi config (nixos-anywhere + deploys).
  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPH7IEv+Q6s6WSPlWVva6UlCbkhePQdZYbN1TbI7rCDx"
  ];

  # Local, host-scoped bans only (no shared threat-intel: it blacklisted legitimate guests, see roles/pangolin docs).
  services.fail2ban = {
    enable = true;
    bantime = "1h";
    maxretry = 5;
    jails.sshd.settings = {
      enabled = true;
      findtime = "10m";
      backend = "systemd";
    };
  };

  boot.kernel.sysctl = {
    "net.ipv4.conf.all.accept_redirects" = 0;
    "net.ipv4.conf.default.accept_redirects" = 0;
    "net.ipv4.conf.all.secure_redirects" = 0;
    "net.ipv4.conf.all.send_redirects" = 0;
    "net.ipv4.conf.all.accept_source_route" = 0;
    "net.ipv4.conf.all.rp_filter" = 1;
    "net.ipv4.conf.default.rp_filter" = 1;
    "net.ipv4.icmp_echo_ignore_broadcasts" = 1;
    "net.ipv4.icmp_ignore_bogus_error_responses" = 1;
    "net.ipv4.tcp_syncookies" = 1;
    "net.ipv4.conf.all.log_martians" = 1;
    "net.ipv6.conf.all.accept_redirects" = 0;
    "net.ipv6.conf.default.accept_redirects" = 0;
    "net.ipv6.conf.all.accept_source_route" = 0;
    "net.ipv6.conf.default.accept_source_route" = 0;
    "kernel.dmesg_restrict" = 1;
    "kernel.kptr_restrict" = 2;
    "fs.suid_dumpable" = 0;
  };

  # Joins the tailnet under the same name as before (`kazimierz-akn`): the Integration API URL used by the Pulumi
  # stacks (`pangolin:url`) is derived from it. Delete the old node from the tailnet before the first boot, or this
  # one comes up as `kazimierz-akn-1`.
  services.tailscale = {
    enable = true;
    authKeyFile = config.sops.secrets.tailscale_authkey.path;
    extraUpFlags = [ "--advertise-tags=tag:svc-pangolin" "--ssh" ];
  };

  # --- Secrets (sops-nix, age) -------------------------------------------------
  # Host key = the SSH ed25519 host key, converted by sops-nix. See docs/MIGRATION_NIXOS.md.
  sops.defaultSopsFile = ./secrets/kazimierz.sops.yaml;
  sops.age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];
  # Pre-authorized key generated by Pulumi (`tailscaleAuthKey` output, 7 days, single use): only consumed on first boot.
  sops.secrets.tailscale_authkey = { };

  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store = true;
  };
  nix.gc = {
    automatic = true;
    options = "--delete-older-than 14d";
  };

  environment.systemPackages = with pkgs; [ htop tmux ];
}
