// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class StorageCifs extends pulumi.CustomResource {
    /**
     * Get an existing StorageCifs resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: StorageCifsState, opts?: pulumi.CustomResourceOptions): StorageCifs {
        return new StorageCifs(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'proxmox:index/storageCifs:StorageCifs';

    /**
     * Returns true if the given object is an instance of StorageCifs.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StorageCifs {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StorageCifs.__pulumiType;
    }

    /**
     * Configure backup retention settings for the storage type.
     */
    declare public readonly backups: pulumi.Output<outputs.StorageCifsBackups | undefined>;
    /**
     * The content types that can be stored on this storage. Valid values: <span pulumi-lang-nodejs="`backup`" pulumi-lang-dotnet="`Backup`" pulumi-lang-go="`backup`" pulumi-lang-python="`backup`" pulumi-lang-yaml="`backup`" pulumi-lang-java="`backup`" pulumi-lang-hcl="`backup`">`backup`</span> (VM backups), <span pulumi-lang-nodejs="`images`" pulumi-lang-dotnet="`Images`" pulumi-lang-go="`images`" pulumi-lang-python="`images`" pulumi-lang-yaml="`images`" pulumi-lang-java="`images`" pulumi-lang-hcl="`images`">`images`</span> (VM disk images), <span pulumi-lang-nodejs="`import`" pulumi-lang-dotnet="`Import`" pulumi-lang-go="`import`" pulumi-lang-python="`import`" pulumi-lang-yaml="`import`" pulumi-lang-java="`import`" pulumi-lang-hcl="`import`">`import`</span> (VM disk images for import), <span pulumi-lang-nodejs="`iso`" pulumi-lang-dotnet="`Iso`" pulumi-lang-go="`iso`" pulumi-lang-python="`iso`" pulumi-lang-yaml="`iso`" pulumi-lang-java="`iso`" pulumi-lang-hcl="`iso`">`iso`</span> (ISO images), <span pulumi-lang-nodejs="`rootdir`" pulumi-lang-dotnet="`Rootdir`" pulumi-lang-go="`rootdir`" pulumi-lang-python="`rootdir`" pulumi-lang-yaml="`rootdir`" pulumi-lang-java="`rootdir`" pulumi-lang-hcl="`rootdir`">`rootdir`</span> (container root directories), <span pulumi-lang-nodejs="`snippets`" pulumi-lang-dotnet="`Snippets`" pulumi-lang-go="`snippets`" pulumi-lang-python="`snippets`" pulumi-lang-yaml="`snippets`" pulumi-lang-java="`snippets`" pulumi-lang-hcl="`snippets`">`snippets`</span> (cloud-init, hook scripts, etc.), <span pulumi-lang-nodejs="`vztmpl`" pulumi-lang-dotnet="`Vztmpl`" pulumi-lang-go="`vztmpl`" pulumi-lang-python="`vztmpl`" pulumi-lang-yaml="`vztmpl`" pulumi-lang-java="`vztmpl`" pulumi-lang-hcl="`vztmpl`">`vztmpl`</span> (container templates).
     */
    declare public readonly contents: pulumi.Output<string[]>;
    /**
     * Create the base directory if it doesn't exist.
     */
    declare public readonly createBasePath: pulumi.Output<boolean>;
    /**
     * Populate the directory with the default structure.
     */
    declare public readonly createSubdirs: pulumi.Output<boolean>;
    /**
     * Whether the storage is disabled.
     */
    declare public readonly disable: pulumi.Output<boolean>;
    /**
     * The SMB/CIFS domain.
     */
    declare public readonly domain: pulumi.Output<string | undefined>;
    /**
     * A list of nodes where this storage is available.
     */
    declare public readonly nodes: pulumi.Output<string[]>;
    /**
     * The mount options for the SMB/CIFS share (see 'man mount.cifs').
     */
    declare public readonly options: pulumi.Output<string | undefined>;
    /**
     * The password for authenticating with the SMB/CIFS server.
     */
    declare public readonly password: pulumi.Output<string>;
    /**
     * The preallocation mode for raw and qcow2 images.
     */
    declare public readonly preallocation: pulumi.Output<string | undefined>;
    /**
     * The IP address or DNS name of the SMB/CIFS server.
     */
    declare public readonly server: pulumi.Output<string>;
    /**
     * The name of the SMB/CIFS share.
     */
    declare public readonly share: pulumi.Output<string>;
    /**
     * Whether the storage is shared across all nodes.
     */
    declare public /*out*/ readonly shared: pulumi.Output<boolean>;
    /**
     * Enable support for creating snapshots through volume backing-chains.
     */
    declare public readonly snapshotAsVolumeChain: pulumi.Output<boolean | undefined>;
    /**
     * The unique identifier of the storage.
     */
    declare public readonly storageCifsId: pulumi.Output<string>;
    /**
     * A subdirectory to mount within the share.
     */
    declare public readonly subdirectory: pulumi.Output<string | undefined>;
    /**
     * The username for authenticating with the SMB/CIFS server.
     */
    declare public readonly username: pulumi.Output<string>;

    /**
     * Create a StorageCifs resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: StorageCifsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: StorageCifsArgs | StorageCifsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as StorageCifsState | undefined;
            resourceInputs["backups"] = state?.backups;
            resourceInputs["contents"] = state?.contents;
            resourceInputs["createBasePath"] = state?.createBasePath;
            resourceInputs["createSubdirs"] = state?.createSubdirs;
            resourceInputs["disable"] = state?.disable;
            resourceInputs["domain"] = state?.domain;
            resourceInputs["nodes"] = state?.nodes;
            resourceInputs["options"] = state?.options;
            resourceInputs["password"] = state?.password;
            resourceInputs["preallocation"] = state?.preallocation;
            resourceInputs["server"] = state?.server;
            resourceInputs["share"] = state?.share;
            resourceInputs["shared"] = state?.shared;
            resourceInputs["snapshotAsVolumeChain"] = state?.snapshotAsVolumeChain;
            resourceInputs["storageCifsId"] = state?.storageCifsId;
            resourceInputs["subdirectory"] = state?.subdirectory;
            resourceInputs["username"] = state?.username;
        } else {
            const args = argsOrState as StorageCifsArgs | undefined;
            if (args?.password === undefined && !opts.urn) {
                throw new Error("Missing required property 'password'");
            }
            if (args?.server === undefined && !opts.urn) {
                throw new Error("Missing required property 'server'");
            }
            if (args?.share === undefined && !opts.urn) {
                throw new Error("Missing required property 'share'");
            }
            if (args?.storageCifsId === undefined && !opts.urn) {
                throw new Error("Missing required property 'storageCifsId'");
            }
            if (args?.username === undefined && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["backups"] = args?.backups;
            resourceInputs["contents"] = args?.contents;
            resourceInputs["createBasePath"] = args?.createBasePath;
            resourceInputs["createSubdirs"] = args?.createSubdirs;
            resourceInputs["disable"] = args?.disable;
            resourceInputs["domain"] = args?.domain;
            resourceInputs["nodes"] = args?.nodes;
            resourceInputs["options"] = args?.options;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["preallocation"] = args?.preallocation;
            resourceInputs["server"] = args?.server;
            resourceInputs["share"] = args?.share;
            resourceInputs["snapshotAsVolumeChain"] = args?.snapshotAsVolumeChain;
            resourceInputs["storageCifsId"] = args?.storageCifsId;
            resourceInputs["subdirectory"] = args?.subdirectory;
            resourceInputs["username"] = args?.username;
            resourceInputs["shared"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(StorageCifs.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering StorageCifs resources.
 */
export interface StorageCifsState {
    /**
     * Configure backup retention settings for the storage type.
     */
    backups?: pulumi.Input<inputs.StorageCifsBackups | undefined>;
    /**
     * The content types that can be stored on this storage. Valid values: <span pulumi-lang-nodejs="`backup`" pulumi-lang-dotnet="`Backup`" pulumi-lang-go="`backup`" pulumi-lang-python="`backup`" pulumi-lang-yaml="`backup`" pulumi-lang-java="`backup`" pulumi-lang-hcl="`backup`">`backup`</span> (VM backups), <span pulumi-lang-nodejs="`images`" pulumi-lang-dotnet="`Images`" pulumi-lang-go="`images`" pulumi-lang-python="`images`" pulumi-lang-yaml="`images`" pulumi-lang-java="`images`" pulumi-lang-hcl="`images`">`images`</span> (VM disk images), <span pulumi-lang-nodejs="`import`" pulumi-lang-dotnet="`Import`" pulumi-lang-go="`import`" pulumi-lang-python="`import`" pulumi-lang-yaml="`import`" pulumi-lang-java="`import`" pulumi-lang-hcl="`import`">`import`</span> (VM disk images for import), <span pulumi-lang-nodejs="`iso`" pulumi-lang-dotnet="`Iso`" pulumi-lang-go="`iso`" pulumi-lang-python="`iso`" pulumi-lang-yaml="`iso`" pulumi-lang-java="`iso`" pulumi-lang-hcl="`iso`">`iso`</span> (ISO images), <span pulumi-lang-nodejs="`rootdir`" pulumi-lang-dotnet="`Rootdir`" pulumi-lang-go="`rootdir`" pulumi-lang-python="`rootdir`" pulumi-lang-yaml="`rootdir`" pulumi-lang-java="`rootdir`" pulumi-lang-hcl="`rootdir`">`rootdir`</span> (container root directories), <span pulumi-lang-nodejs="`snippets`" pulumi-lang-dotnet="`Snippets`" pulumi-lang-go="`snippets`" pulumi-lang-python="`snippets`" pulumi-lang-yaml="`snippets`" pulumi-lang-java="`snippets`" pulumi-lang-hcl="`snippets`">`snippets`</span> (cloud-init, hook scripts, etc.), <span pulumi-lang-nodejs="`vztmpl`" pulumi-lang-dotnet="`Vztmpl`" pulumi-lang-go="`vztmpl`" pulumi-lang-python="`vztmpl`" pulumi-lang-yaml="`vztmpl`" pulumi-lang-java="`vztmpl`" pulumi-lang-hcl="`vztmpl`">`vztmpl`</span> (container templates).
     */
    contents?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Create the base directory if it doesn't exist.
     */
    createBasePath?: pulumi.Input<boolean | undefined>;
    /**
     * Populate the directory with the default structure.
     */
    createSubdirs?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the storage is disabled.
     */
    disable?: pulumi.Input<boolean | undefined>;
    /**
     * The SMB/CIFS domain.
     */
    domain?: pulumi.Input<string | undefined>;
    /**
     * A list of nodes where this storage is available.
     */
    nodes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The mount options for the SMB/CIFS share (see 'man mount.cifs').
     */
    options?: pulumi.Input<string | undefined>;
    /**
     * The password for authenticating with the SMB/CIFS server.
     */
    password?: pulumi.Input<string | undefined>;
    /**
     * The preallocation mode for raw and qcow2 images.
     */
    preallocation?: pulumi.Input<string | undefined>;
    /**
     * The IP address or DNS name of the SMB/CIFS server.
     */
    server?: pulumi.Input<string | undefined>;
    /**
     * The name of the SMB/CIFS share.
     */
    share?: pulumi.Input<string | undefined>;
    /**
     * Whether the storage is shared across all nodes.
     */
    shared?: pulumi.Input<boolean | undefined>;
    /**
     * Enable support for creating snapshots through volume backing-chains.
     */
    snapshotAsVolumeChain?: pulumi.Input<boolean | undefined>;
    /**
     * The unique identifier of the storage.
     */
    storageCifsId?: pulumi.Input<string | undefined>;
    /**
     * A subdirectory to mount within the share.
     */
    subdirectory?: pulumi.Input<string | undefined>;
    /**
     * The username for authenticating with the SMB/CIFS server.
     */
    username?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a StorageCifs resource.
 */
export interface StorageCifsArgs {
    /**
     * Configure backup retention settings for the storage type.
     */
    backups?: pulumi.Input<inputs.StorageCifsBackups | undefined>;
    /**
     * The content types that can be stored on this storage. Valid values: <span pulumi-lang-nodejs="`backup`" pulumi-lang-dotnet="`Backup`" pulumi-lang-go="`backup`" pulumi-lang-python="`backup`" pulumi-lang-yaml="`backup`" pulumi-lang-java="`backup`" pulumi-lang-hcl="`backup`">`backup`</span> (VM backups), <span pulumi-lang-nodejs="`images`" pulumi-lang-dotnet="`Images`" pulumi-lang-go="`images`" pulumi-lang-python="`images`" pulumi-lang-yaml="`images`" pulumi-lang-java="`images`" pulumi-lang-hcl="`images`">`images`</span> (VM disk images), <span pulumi-lang-nodejs="`import`" pulumi-lang-dotnet="`Import`" pulumi-lang-go="`import`" pulumi-lang-python="`import`" pulumi-lang-yaml="`import`" pulumi-lang-java="`import`" pulumi-lang-hcl="`import`">`import`</span> (VM disk images for import), <span pulumi-lang-nodejs="`iso`" pulumi-lang-dotnet="`Iso`" pulumi-lang-go="`iso`" pulumi-lang-python="`iso`" pulumi-lang-yaml="`iso`" pulumi-lang-java="`iso`" pulumi-lang-hcl="`iso`">`iso`</span> (ISO images), <span pulumi-lang-nodejs="`rootdir`" pulumi-lang-dotnet="`Rootdir`" pulumi-lang-go="`rootdir`" pulumi-lang-python="`rootdir`" pulumi-lang-yaml="`rootdir`" pulumi-lang-java="`rootdir`" pulumi-lang-hcl="`rootdir`">`rootdir`</span> (container root directories), <span pulumi-lang-nodejs="`snippets`" pulumi-lang-dotnet="`Snippets`" pulumi-lang-go="`snippets`" pulumi-lang-python="`snippets`" pulumi-lang-yaml="`snippets`" pulumi-lang-java="`snippets`" pulumi-lang-hcl="`snippets`">`snippets`</span> (cloud-init, hook scripts, etc.), <span pulumi-lang-nodejs="`vztmpl`" pulumi-lang-dotnet="`Vztmpl`" pulumi-lang-go="`vztmpl`" pulumi-lang-python="`vztmpl`" pulumi-lang-yaml="`vztmpl`" pulumi-lang-java="`vztmpl`" pulumi-lang-hcl="`vztmpl`">`vztmpl`</span> (container templates).
     */
    contents?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Create the base directory if it doesn't exist.
     */
    createBasePath?: pulumi.Input<boolean | undefined>;
    /**
     * Populate the directory with the default structure.
     */
    createSubdirs?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the storage is disabled.
     */
    disable?: pulumi.Input<boolean | undefined>;
    /**
     * The SMB/CIFS domain.
     */
    domain?: pulumi.Input<string | undefined>;
    /**
     * A list of nodes where this storage is available.
     */
    nodes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The mount options for the SMB/CIFS share (see 'man mount.cifs').
     */
    options?: pulumi.Input<string | undefined>;
    /**
     * The password for authenticating with the SMB/CIFS server.
     */
    password: pulumi.Input<string>;
    /**
     * The preallocation mode for raw and qcow2 images.
     */
    preallocation?: pulumi.Input<string | undefined>;
    /**
     * The IP address or DNS name of the SMB/CIFS server.
     */
    server: pulumi.Input<string>;
    /**
     * The name of the SMB/CIFS share.
     */
    share: pulumi.Input<string>;
    /**
     * Enable support for creating snapshots through volume backing-chains.
     */
    snapshotAsVolumeChain?: pulumi.Input<boolean | undefined>;
    /**
     * The unique identifier of the storage.
     */
    storageCifsId: pulumi.Input<string>;
    /**
     * A subdirectory to mount within the share.
     */
    subdirectory?: pulumi.Input<string | undefined>;
    /**
     * The username for authenticating with the SMB/CIFS server.
     */
    username: pulumi.Input<string>;
}
