// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class StorageLvm extends pulumi.CustomResource {
    /**
     * Get an existing StorageLvm resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: StorageLvmState, opts?: pulumi.CustomResourceOptions): StorageLvm {
        return new StorageLvm(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'proxmox:index/storageLvm:StorageLvm';

    /**
     * Returns true if the given object is an instance of StorageLvm.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StorageLvm {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StorageLvm.__pulumiType;
    }

    /**
     * The content types that can be stored on this storage. Valid values: <span pulumi-lang-nodejs="`backup`" pulumi-lang-dotnet="`Backup`" pulumi-lang-go="`backup`" pulumi-lang-python="`backup`" pulumi-lang-yaml="`backup`" pulumi-lang-java="`backup`" pulumi-lang-hcl="`backup`">`backup`</span> (VM backups), <span pulumi-lang-nodejs="`images`" pulumi-lang-dotnet="`Images`" pulumi-lang-go="`images`" pulumi-lang-python="`images`" pulumi-lang-yaml="`images`" pulumi-lang-java="`images`" pulumi-lang-hcl="`images`">`images`</span> (VM disk images), <span pulumi-lang-nodejs="`import`" pulumi-lang-dotnet="`Import`" pulumi-lang-go="`import`" pulumi-lang-python="`import`" pulumi-lang-yaml="`import`" pulumi-lang-java="`import`" pulumi-lang-hcl="`import`">`import`</span> (VM disk images for import), <span pulumi-lang-nodejs="`iso`" pulumi-lang-dotnet="`Iso`" pulumi-lang-go="`iso`" pulumi-lang-python="`iso`" pulumi-lang-yaml="`iso`" pulumi-lang-java="`iso`" pulumi-lang-hcl="`iso`">`iso`</span> (ISO images), <span pulumi-lang-nodejs="`rootdir`" pulumi-lang-dotnet="`Rootdir`" pulumi-lang-go="`rootdir`" pulumi-lang-python="`rootdir`" pulumi-lang-yaml="`rootdir`" pulumi-lang-java="`rootdir`" pulumi-lang-hcl="`rootdir`">`rootdir`</span> (container root directories), <span pulumi-lang-nodejs="`snippets`" pulumi-lang-dotnet="`Snippets`" pulumi-lang-go="`snippets`" pulumi-lang-python="`snippets`" pulumi-lang-yaml="`snippets`" pulumi-lang-java="`snippets`" pulumi-lang-hcl="`snippets`">`snippets`</span> (cloud-init, hook scripts, etc.), <span pulumi-lang-nodejs="`vztmpl`" pulumi-lang-dotnet="`Vztmpl`" pulumi-lang-go="`vztmpl`" pulumi-lang-python="`vztmpl`" pulumi-lang-yaml="`vztmpl`" pulumi-lang-java="`vztmpl`" pulumi-lang-hcl="`vztmpl`">`vztmpl`</span> (container templates).
     */
    declare public readonly contents: pulumi.Output<string[]>;
    /**
     * Whether the storage is disabled.
     */
    declare public readonly disable: pulumi.Output<boolean>;
    /**
     * A list of nodes where this storage is available.
     */
    declare public readonly nodes: pulumi.Output<string[]>;
    /**
     * Whether the storage is shared across all nodes.
     */
    declare public readonly shared: pulumi.Output<boolean>;
    /**
     * The unique identifier of the storage.
     */
    declare public readonly storageLvmId: pulumi.Output<string>;
    /**
     * The name of the volume group to use.
     */
    declare public readonly volumeGroup: pulumi.Output<string>;
    /**
     * Whether to zero-out data when removing LVMs.
     */
    declare public readonly wipeRemovedVolumes: pulumi.Output<boolean>;

    /**
     * Create a StorageLvm resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: StorageLvmArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: StorageLvmArgs | StorageLvmState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as StorageLvmState | undefined;
            resourceInputs["contents"] = state?.contents;
            resourceInputs["disable"] = state?.disable;
            resourceInputs["nodes"] = state?.nodes;
            resourceInputs["shared"] = state?.shared;
            resourceInputs["storageLvmId"] = state?.storageLvmId;
            resourceInputs["volumeGroup"] = state?.volumeGroup;
            resourceInputs["wipeRemovedVolumes"] = state?.wipeRemovedVolumes;
        } else {
            const args = argsOrState as StorageLvmArgs | undefined;
            if (args?.storageLvmId === undefined && !opts.urn) {
                throw new Error("Missing required property 'storageLvmId'");
            }
            if (args?.volumeGroup === undefined && !opts.urn) {
                throw new Error("Missing required property 'volumeGroup'");
            }
            resourceInputs["contents"] = args?.contents;
            resourceInputs["disable"] = args?.disable;
            resourceInputs["nodes"] = args?.nodes;
            resourceInputs["shared"] = args?.shared;
            resourceInputs["storageLvmId"] = args?.storageLvmId;
            resourceInputs["volumeGroup"] = args?.volumeGroup;
            resourceInputs["wipeRemovedVolumes"] = args?.wipeRemovedVolumes;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StorageLvm.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering StorageLvm resources.
 */
export interface StorageLvmState {
    /**
     * The content types that can be stored on this storage. Valid values: <span pulumi-lang-nodejs="`backup`" pulumi-lang-dotnet="`Backup`" pulumi-lang-go="`backup`" pulumi-lang-python="`backup`" pulumi-lang-yaml="`backup`" pulumi-lang-java="`backup`" pulumi-lang-hcl="`backup`">`backup`</span> (VM backups), <span pulumi-lang-nodejs="`images`" pulumi-lang-dotnet="`Images`" pulumi-lang-go="`images`" pulumi-lang-python="`images`" pulumi-lang-yaml="`images`" pulumi-lang-java="`images`" pulumi-lang-hcl="`images`">`images`</span> (VM disk images), <span pulumi-lang-nodejs="`import`" pulumi-lang-dotnet="`Import`" pulumi-lang-go="`import`" pulumi-lang-python="`import`" pulumi-lang-yaml="`import`" pulumi-lang-java="`import`" pulumi-lang-hcl="`import`">`import`</span> (VM disk images for import), <span pulumi-lang-nodejs="`iso`" pulumi-lang-dotnet="`Iso`" pulumi-lang-go="`iso`" pulumi-lang-python="`iso`" pulumi-lang-yaml="`iso`" pulumi-lang-java="`iso`" pulumi-lang-hcl="`iso`">`iso`</span> (ISO images), <span pulumi-lang-nodejs="`rootdir`" pulumi-lang-dotnet="`Rootdir`" pulumi-lang-go="`rootdir`" pulumi-lang-python="`rootdir`" pulumi-lang-yaml="`rootdir`" pulumi-lang-java="`rootdir`" pulumi-lang-hcl="`rootdir`">`rootdir`</span> (container root directories), <span pulumi-lang-nodejs="`snippets`" pulumi-lang-dotnet="`Snippets`" pulumi-lang-go="`snippets`" pulumi-lang-python="`snippets`" pulumi-lang-yaml="`snippets`" pulumi-lang-java="`snippets`" pulumi-lang-hcl="`snippets`">`snippets`</span> (cloud-init, hook scripts, etc.), <span pulumi-lang-nodejs="`vztmpl`" pulumi-lang-dotnet="`Vztmpl`" pulumi-lang-go="`vztmpl`" pulumi-lang-python="`vztmpl`" pulumi-lang-yaml="`vztmpl`" pulumi-lang-java="`vztmpl`" pulumi-lang-hcl="`vztmpl`">`vztmpl`</span> (container templates).
     */
    contents?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether the storage is disabled.
     */
    disable?: pulumi.Input<boolean | undefined>;
    /**
     * A list of nodes where this storage is available.
     */
    nodes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether the storage is shared across all nodes.
     */
    shared?: pulumi.Input<boolean | undefined>;
    /**
     * The unique identifier of the storage.
     */
    storageLvmId?: pulumi.Input<string | undefined>;
    /**
     * The name of the volume group to use.
     */
    volumeGroup?: pulumi.Input<string | undefined>;
    /**
     * Whether to zero-out data when removing LVMs.
     */
    wipeRemovedVolumes?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a StorageLvm resource.
 */
export interface StorageLvmArgs {
    /**
     * The content types that can be stored on this storage. Valid values: <span pulumi-lang-nodejs="`backup`" pulumi-lang-dotnet="`Backup`" pulumi-lang-go="`backup`" pulumi-lang-python="`backup`" pulumi-lang-yaml="`backup`" pulumi-lang-java="`backup`" pulumi-lang-hcl="`backup`">`backup`</span> (VM backups), <span pulumi-lang-nodejs="`images`" pulumi-lang-dotnet="`Images`" pulumi-lang-go="`images`" pulumi-lang-python="`images`" pulumi-lang-yaml="`images`" pulumi-lang-java="`images`" pulumi-lang-hcl="`images`">`images`</span> (VM disk images), <span pulumi-lang-nodejs="`import`" pulumi-lang-dotnet="`Import`" pulumi-lang-go="`import`" pulumi-lang-python="`import`" pulumi-lang-yaml="`import`" pulumi-lang-java="`import`" pulumi-lang-hcl="`import`">`import`</span> (VM disk images for import), <span pulumi-lang-nodejs="`iso`" pulumi-lang-dotnet="`Iso`" pulumi-lang-go="`iso`" pulumi-lang-python="`iso`" pulumi-lang-yaml="`iso`" pulumi-lang-java="`iso`" pulumi-lang-hcl="`iso`">`iso`</span> (ISO images), <span pulumi-lang-nodejs="`rootdir`" pulumi-lang-dotnet="`Rootdir`" pulumi-lang-go="`rootdir`" pulumi-lang-python="`rootdir`" pulumi-lang-yaml="`rootdir`" pulumi-lang-java="`rootdir`" pulumi-lang-hcl="`rootdir`">`rootdir`</span> (container root directories), <span pulumi-lang-nodejs="`snippets`" pulumi-lang-dotnet="`Snippets`" pulumi-lang-go="`snippets`" pulumi-lang-python="`snippets`" pulumi-lang-yaml="`snippets`" pulumi-lang-java="`snippets`" pulumi-lang-hcl="`snippets`">`snippets`</span> (cloud-init, hook scripts, etc.), <span pulumi-lang-nodejs="`vztmpl`" pulumi-lang-dotnet="`Vztmpl`" pulumi-lang-go="`vztmpl`" pulumi-lang-python="`vztmpl`" pulumi-lang-yaml="`vztmpl`" pulumi-lang-java="`vztmpl`" pulumi-lang-hcl="`vztmpl`">`vztmpl`</span> (container templates).
     */
    contents?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether the storage is disabled.
     */
    disable?: pulumi.Input<boolean | undefined>;
    /**
     * A list of nodes where this storage is available.
     */
    nodes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether the storage is shared across all nodes.
     */
    shared?: pulumi.Input<boolean | undefined>;
    /**
     * The unique identifier of the storage.
     */
    storageLvmId: pulumi.Input<string>;
    /**
     * The name of the volume group to use.
     */
    volumeGroup: pulumi.Input<string>;
    /**
     * Whether to zero-out data when removing LVMs.
     */
    wipeRemovedVolumes?: pulumi.Input<boolean | undefined>;
}
