// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class VirtualEnvironmentStorageZfspool extends pulumi.CustomResource {
    /**
     * Get an existing VirtualEnvironmentStorageZfspool resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VirtualEnvironmentStorageZfspoolState, opts?: pulumi.CustomResourceOptions): VirtualEnvironmentStorageZfspool {
        return new VirtualEnvironmentStorageZfspool(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'proxmox:index/virtualEnvironmentStorageZfspool:VirtualEnvironmentStorageZfspool';

    /**
     * Returns true if the given object is an instance of VirtualEnvironmentStorageZfspool.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VirtualEnvironmentStorageZfspool {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VirtualEnvironmentStorageZfspool.__pulumiType;
    }

    /**
     * Block size for newly created volumes (e.g. <span pulumi-lang-nodejs="`4k`" pulumi-lang-dotnet="`4k`" pulumi-lang-go="`4k`" pulumi-lang-python="`4k`" pulumi-lang-yaml="`4k`" pulumi-lang-java="`4k`" pulumi-lang-hcl="`4k`">`4k`</span>, <span pulumi-lang-nodejs="`8k`" pulumi-lang-dotnet="`8k`" pulumi-lang-go="`8k`" pulumi-lang-python="`8k`" pulumi-lang-yaml="`8k`" pulumi-lang-java="`8k`" pulumi-lang-hcl="`8k`">`8k`</span>, <span pulumi-lang-nodejs="`16k`" pulumi-lang-dotnet="`16k`" pulumi-lang-go="`16k`" pulumi-lang-python="`16k`" pulumi-lang-yaml="`16k`" pulumi-lang-java="`16k`" pulumi-lang-hcl="`16k`">`16k`</span>). Larger values may improve throughput for large I/O, while smaller values optimize space efficiency.
     */
    declare public readonly blocksize: pulumi.Output<string | undefined>;
    /**
     * The content types that can be stored on this storage. Valid values: <span pulumi-lang-nodejs="`backup`" pulumi-lang-dotnet="`Backup`" pulumi-lang-go="`backup`" pulumi-lang-python="`backup`" pulumi-lang-yaml="`backup`" pulumi-lang-java="`backup`" pulumi-lang-hcl="`backup`">`backup`</span> (VM backups), <span pulumi-lang-nodejs="`images`" pulumi-lang-dotnet="`Images`" pulumi-lang-go="`images`" pulumi-lang-python="`images`" pulumi-lang-yaml="`images`" pulumi-lang-java="`images`" pulumi-lang-hcl="`images`">`images`</span> (VM disk images), <span pulumi-lang-nodejs="`import`" pulumi-lang-dotnet="`Import`" pulumi-lang-go="`import`" pulumi-lang-python="`import`" pulumi-lang-yaml="`import`" pulumi-lang-java="`import`" pulumi-lang-hcl="`import`">`import`</span> (VM disk images for import), <span pulumi-lang-nodejs="`iso`" pulumi-lang-dotnet="`Iso`" pulumi-lang-go="`iso`" pulumi-lang-python="`iso`" pulumi-lang-yaml="`iso`" pulumi-lang-java="`iso`" pulumi-lang-hcl="`iso`">`iso`</span> (ISO images), <span pulumi-lang-nodejs="`rootdir`" pulumi-lang-dotnet="`Rootdir`" pulumi-lang-go="`rootdir`" pulumi-lang-python="`rootdir`" pulumi-lang-yaml="`rootdir`" pulumi-lang-java="`rootdir`" pulumi-lang-hcl="`rootdir`">`rootdir`</span> (container root directories), <span pulumi-lang-nodejs="`snippets`" pulumi-lang-dotnet="`Snippets`" pulumi-lang-go="`snippets`" pulumi-lang-python="`snippets`" pulumi-lang-yaml="`snippets`" pulumi-lang-java="`snippets`" pulumi-lang-hcl="`snippets`">`snippets`</span> (cloud-init, hook scripts, etc.), <span pulumi-lang-nodejs="`vztmpl`" pulumi-lang-dotnet="`Vztmpl`" pulumi-lang-go="`vztmpl`" pulumi-lang-python="`vztmpl`" pulumi-lang-yaml="`vztmpl`" pulumi-lang-java="`vztmpl`" pulumi-lang-hcl="`vztmpl`">`vztmpl`</span> (container templates).
     */
    declare public readonly contents: pulumi.Output<string[]>;
    /**
     * Whether the storage is disabled.
     */
    declare public readonly disable: pulumi.Output<boolean>;
    /**
     * A list of nodes where this storage is available.
     */
    declare public readonly nodes: pulumi.Output<string[]>;
    /**
     * Whether the storage is shared across all nodes.
     */
    declare public /*out*/ readonly shared: pulumi.Output<boolean>;
    /**
     * Whether to enable thin provisioning (<span pulumi-lang-nodejs="`on`" pulumi-lang-dotnet="`On`" pulumi-lang-go="`on`" pulumi-lang-python="`on`" pulumi-lang-yaml="`on`" pulumi-lang-java="`on`" pulumi-lang-hcl="`on`">`on`</span> or <span pulumi-lang-nodejs="`off`" pulumi-lang-dotnet="`Off`" pulumi-lang-go="`off`" pulumi-lang-python="`off`" pulumi-lang-yaml="`off`" pulumi-lang-java="`off`" pulumi-lang-hcl="`off`">`off`</span>). Thin provisioning allows flexible disk allocation without pre-allocating full space.
     */
    declare public readonly thinProvision: pulumi.Output<boolean | undefined>;
    /**
     * The unique identifier of the storage.
     */
    declare public readonly virtualEnvironmentStorageZfspoolId: pulumi.Output<string>;
    /**
     * The name of the ZFS storage pool to use (e.g. <span pulumi-lang-nodejs="`tank`" pulumi-lang-dotnet="`Tank`" pulumi-lang-go="`tank`" pulumi-lang-python="`tank`" pulumi-lang-yaml="`tank`" pulumi-lang-java="`tank`" pulumi-lang-hcl="`tank`">`tank`</span>, `rpool/data`).
     */
    declare public readonly zfsPool: pulumi.Output<string>;

    /**
     * Create a VirtualEnvironmentStorageZfspool resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VirtualEnvironmentStorageZfspoolArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VirtualEnvironmentStorageZfspoolArgs | VirtualEnvironmentStorageZfspoolState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VirtualEnvironmentStorageZfspoolState | undefined;
            resourceInputs["blocksize"] = state?.blocksize;
            resourceInputs["contents"] = state?.contents;
            resourceInputs["disable"] = state?.disable;
            resourceInputs["nodes"] = state?.nodes;
            resourceInputs["shared"] = state?.shared;
            resourceInputs["thinProvision"] = state?.thinProvision;
            resourceInputs["virtualEnvironmentStorageZfspoolId"] = state?.virtualEnvironmentStorageZfspoolId;
            resourceInputs["zfsPool"] = state?.zfsPool;
        } else {
            const args = argsOrState as VirtualEnvironmentStorageZfspoolArgs | undefined;
            if (args?.virtualEnvironmentStorageZfspoolId === undefined && !opts.urn) {
                throw new Error("Missing required property 'virtualEnvironmentStorageZfspoolId'");
            }
            if (args?.zfsPool === undefined && !opts.urn) {
                throw new Error("Missing required property 'zfsPool'");
            }
            resourceInputs["blocksize"] = args?.blocksize;
            resourceInputs["contents"] = args?.contents;
            resourceInputs["disable"] = args?.disable;
            resourceInputs["nodes"] = args?.nodes;
            resourceInputs["thinProvision"] = args?.thinProvision;
            resourceInputs["virtualEnvironmentStorageZfspoolId"] = args?.virtualEnvironmentStorageZfspoolId;
            resourceInputs["zfsPool"] = args?.zfsPool;
            resourceInputs["shared"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VirtualEnvironmentStorageZfspool.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering VirtualEnvironmentStorageZfspool resources.
 */
export interface VirtualEnvironmentStorageZfspoolState {
    /**
     * Block size for newly created volumes (e.g. <span pulumi-lang-nodejs="`4k`" pulumi-lang-dotnet="`4k`" pulumi-lang-go="`4k`" pulumi-lang-python="`4k`" pulumi-lang-yaml="`4k`" pulumi-lang-java="`4k`" pulumi-lang-hcl="`4k`">`4k`</span>, <span pulumi-lang-nodejs="`8k`" pulumi-lang-dotnet="`8k`" pulumi-lang-go="`8k`" pulumi-lang-python="`8k`" pulumi-lang-yaml="`8k`" pulumi-lang-java="`8k`" pulumi-lang-hcl="`8k`">`8k`</span>, <span pulumi-lang-nodejs="`16k`" pulumi-lang-dotnet="`16k`" pulumi-lang-go="`16k`" pulumi-lang-python="`16k`" pulumi-lang-yaml="`16k`" pulumi-lang-java="`16k`" pulumi-lang-hcl="`16k`">`16k`</span>). Larger values may improve throughput for large I/O, while smaller values optimize space efficiency.
     */
    blocksize?: pulumi.Input<string | undefined>;
    /**
     * The content types that can be stored on this storage. Valid values: <span pulumi-lang-nodejs="`backup`" pulumi-lang-dotnet="`Backup`" pulumi-lang-go="`backup`" pulumi-lang-python="`backup`" pulumi-lang-yaml="`backup`" pulumi-lang-java="`backup`" pulumi-lang-hcl="`backup`">`backup`</span> (VM backups), <span pulumi-lang-nodejs="`images`" pulumi-lang-dotnet="`Images`" pulumi-lang-go="`images`" pulumi-lang-python="`images`" pulumi-lang-yaml="`images`" pulumi-lang-java="`images`" pulumi-lang-hcl="`images`">`images`</span> (VM disk images), <span pulumi-lang-nodejs="`import`" pulumi-lang-dotnet="`Import`" pulumi-lang-go="`import`" pulumi-lang-python="`import`" pulumi-lang-yaml="`import`" pulumi-lang-java="`import`" pulumi-lang-hcl="`import`">`import`</span> (VM disk images for import), <span pulumi-lang-nodejs="`iso`" pulumi-lang-dotnet="`Iso`" pulumi-lang-go="`iso`" pulumi-lang-python="`iso`" pulumi-lang-yaml="`iso`" pulumi-lang-java="`iso`" pulumi-lang-hcl="`iso`">`iso`</span> (ISO images), <span pulumi-lang-nodejs="`rootdir`" pulumi-lang-dotnet="`Rootdir`" pulumi-lang-go="`rootdir`" pulumi-lang-python="`rootdir`" pulumi-lang-yaml="`rootdir`" pulumi-lang-java="`rootdir`" pulumi-lang-hcl="`rootdir`">`rootdir`</span> (container root directories), <span pulumi-lang-nodejs="`snippets`" pulumi-lang-dotnet="`Snippets`" pulumi-lang-go="`snippets`" pulumi-lang-python="`snippets`" pulumi-lang-yaml="`snippets`" pulumi-lang-java="`snippets`" pulumi-lang-hcl="`snippets`">`snippets`</span> (cloud-init, hook scripts, etc.), <span pulumi-lang-nodejs="`vztmpl`" pulumi-lang-dotnet="`Vztmpl`" pulumi-lang-go="`vztmpl`" pulumi-lang-python="`vztmpl`" pulumi-lang-yaml="`vztmpl`" pulumi-lang-java="`vztmpl`" pulumi-lang-hcl="`vztmpl`">`vztmpl`</span> (container templates).
     */
    contents?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether the storage is disabled.
     */
    disable?: pulumi.Input<boolean | undefined>;
    /**
     * A list of nodes where this storage is available.
     */
    nodes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether the storage is shared across all nodes.
     */
    shared?: pulumi.Input<boolean | undefined>;
    /**
     * Whether to enable thin provisioning (<span pulumi-lang-nodejs="`on`" pulumi-lang-dotnet="`On`" pulumi-lang-go="`on`" pulumi-lang-python="`on`" pulumi-lang-yaml="`on`" pulumi-lang-java="`on`" pulumi-lang-hcl="`on`">`on`</span> or <span pulumi-lang-nodejs="`off`" pulumi-lang-dotnet="`Off`" pulumi-lang-go="`off`" pulumi-lang-python="`off`" pulumi-lang-yaml="`off`" pulumi-lang-java="`off`" pulumi-lang-hcl="`off`">`off`</span>). Thin provisioning allows flexible disk allocation without pre-allocating full space.
     */
    thinProvision?: pulumi.Input<boolean | undefined>;
    /**
     * The unique identifier of the storage.
     */
    virtualEnvironmentStorageZfspoolId?: pulumi.Input<string | undefined>;
    /**
     * The name of the ZFS storage pool to use (e.g. <span pulumi-lang-nodejs="`tank`" pulumi-lang-dotnet="`Tank`" pulumi-lang-go="`tank`" pulumi-lang-python="`tank`" pulumi-lang-yaml="`tank`" pulumi-lang-java="`tank`" pulumi-lang-hcl="`tank`">`tank`</span>, `rpool/data`).
     */
    zfsPool?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a VirtualEnvironmentStorageZfspool resource.
 */
export interface VirtualEnvironmentStorageZfspoolArgs {
    /**
     * Block size for newly created volumes (e.g. <span pulumi-lang-nodejs="`4k`" pulumi-lang-dotnet="`4k`" pulumi-lang-go="`4k`" pulumi-lang-python="`4k`" pulumi-lang-yaml="`4k`" pulumi-lang-java="`4k`" pulumi-lang-hcl="`4k`">`4k`</span>, <span pulumi-lang-nodejs="`8k`" pulumi-lang-dotnet="`8k`" pulumi-lang-go="`8k`" pulumi-lang-python="`8k`" pulumi-lang-yaml="`8k`" pulumi-lang-java="`8k`" pulumi-lang-hcl="`8k`">`8k`</span>, <span pulumi-lang-nodejs="`16k`" pulumi-lang-dotnet="`16k`" pulumi-lang-go="`16k`" pulumi-lang-python="`16k`" pulumi-lang-yaml="`16k`" pulumi-lang-java="`16k`" pulumi-lang-hcl="`16k`">`16k`</span>). Larger values may improve throughput for large I/O, while smaller values optimize space efficiency.
     */
    blocksize?: pulumi.Input<string | undefined>;
    /**
     * The content types that can be stored on this storage. Valid values: <span pulumi-lang-nodejs="`backup`" pulumi-lang-dotnet="`Backup`" pulumi-lang-go="`backup`" pulumi-lang-python="`backup`" pulumi-lang-yaml="`backup`" pulumi-lang-java="`backup`" pulumi-lang-hcl="`backup`">`backup`</span> (VM backups), <span pulumi-lang-nodejs="`images`" pulumi-lang-dotnet="`Images`" pulumi-lang-go="`images`" pulumi-lang-python="`images`" pulumi-lang-yaml="`images`" pulumi-lang-java="`images`" pulumi-lang-hcl="`images`">`images`</span> (VM disk images), <span pulumi-lang-nodejs="`import`" pulumi-lang-dotnet="`Import`" pulumi-lang-go="`import`" pulumi-lang-python="`import`" pulumi-lang-yaml="`import`" pulumi-lang-java="`import`" pulumi-lang-hcl="`import`">`import`</span> (VM disk images for import), <span pulumi-lang-nodejs="`iso`" pulumi-lang-dotnet="`Iso`" pulumi-lang-go="`iso`" pulumi-lang-python="`iso`" pulumi-lang-yaml="`iso`" pulumi-lang-java="`iso`" pulumi-lang-hcl="`iso`">`iso`</span> (ISO images), <span pulumi-lang-nodejs="`rootdir`" pulumi-lang-dotnet="`Rootdir`" pulumi-lang-go="`rootdir`" pulumi-lang-python="`rootdir`" pulumi-lang-yaml="`rootdir`" pulumi-lang-java="`rootdir`" pulumi-lang-hcl="`rootdir`">`rootdir`</span> (container root directories), <span pulumi-lang-nodejs="`snippets`" pulumi-lang-dotnet="`Snippets`" pulumi-lang-go="`snippets`" pulumi-lang-python="`snippets`" pulumi-lang-yaml="`snippets`" pulumi-lang-java="`snippets`" pulumi-lang-hcl="`snippets`">`snippets`</span> (cloud-init, hook scripts, etc.), <span pulumi-lang-nodejs="`vztmpl`" pulumi-lang-dotnet="`Vztmpl`" pulumi-lang-go="`vztmpl`" pulumi-lang-python="`vztmpl`" pulumi-lang-yaml="`vztmpl`" pulumi-lang-java="`vztmpl`" pulumi-lang-hcl="`vztmpl`">`vztmpl`</span> (container templates).
     */
    contents?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether the storage is disabled.
     */
    disable?: pulumi.Input<boolean | undefined>;
    /**
     * A list of nodes where this storage is available.
     */
    nodes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether to enable thin provisioning (<span pulumi-lang-nodejs="`on`" pulumi-lang-dotnet="`On`" pulumi-lang-go="`on`" pulumi-lang-python="`on`" pulumi-lang-yaml="`on`" pulumi-lang-java="`on`" pulumi-lang-hcl="`on`">`on`</span> or <span pulumi-lang-nodejs="`off`" pulumi-lang-dotnet="`Off`" pulumi-lang-go="`off`" pulumi-lang-python="`off`" pulumi-lang-yaml="`off`" pulumi-lang-java="`off`" pulumi-lang-hcl="`off`">`off`</span>). Thin provisioning allows flexible disk allocation without pre-allocating full space.
     */
    thinProvision?: pulumi.Input<boolean | undefined>;
    /**
     * The unique identifier of the storage.
     */
    virtualEnvironmentStorageZfspoolId: pulumi.Input<string>;
    /**
     * The name of the ZFS storage pool to use (e.g. <span pulumi-lang-nodejs="`tank`" pulumi-lang-dotnet="`Tank`" pulumi-lang-go="`tank`" pulumi-lang-python="`tank`" pulumi-lang-yaml="`tank`" pulumi-lang-java="`tank`" pulumi-lang-hcl="`tank`">`tank`</span>, `rpool/data`).
     */
    zfsPool: pulumi.Input<string>;
}
