// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Vm extends pulumi.CustomResource {
    /**
     * Get an existing Vm resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VmState, opts?: pulumi.CustomResourceOptions): Vm {
        return new Vm(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'proxmox:index/vm:Vm';

    /**
     * Returns true if the given object is an instance of Vm.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Vm {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Vm.__pulumiType;
    }

    /**
     * The CD-ROM configuration. The key is the interface of the CD-ROM, could be one of `ideN`, `sataN`, `scsiN`, where N is the index of the interface. Note that <span pulumi-lang-nodejs="`q35`" pulumi-lang-dotnet="`Q35`" pulumi-lang-go="`q35`" pulumi-lang-python="`q35`" pulumi-lang-yaml="`q35`" pulumi-lang-java="`q35`" pulumi-lang-hcl="`q35`">`q35`</span> machine type only supports <span pulumi-lang-nodejs="`ide0`" pulumi-lang-dotnet="`Ide0`" pulumi-lang-go="`ide0`" pulumi-lang-python="`ide0`" pulumi-lang-yaml="`ide0`" pulumi-lang-java="`ide0`" pulumi-lang-hcl="`ide0`">`ide0`</span> and <span pulumi-lang-nodejs="`ide2`" pulumi-lang-dotnet="`Ide2`" pulumi-lang-go="`ide2`" pulumi-lang-python="`ide2`" pulumi-lang-yaml="`ide2`" pulumi-lang-java="`ide2`" pulumi-lang-hcl="`ide2`">`ide2`</span> of IDE interfaces.
     */
    declare public readonly cdrom: pulumi.Output<{[key: string]: outputs.VmCdrom} | undefined>;
    /**
     * The CPU configuration.
     */
    declare public readonly cpu: pulumi.Output<outputs.VmCpu | undefined>;
    /**
     * Set to true to delete unreferenced disks on destroy (defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>).
     */
    declare public readonly deleteUnreferencedDisksOnDestroy: pulumi.Output<boolean>;
    /**
     * The description of the VM.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The name of the VM. Doesn't have to be unique.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The name of the node where the VM is provisioned.
     */
    declare public readonly nodeName: pulumi.Output<string>;
    /**
     * Set to true to purge the VM from backup configurations on destroy (defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>).
     */
    declare public readonly purgeOnDestroy: pulumi.Output<boolean>;
    /**
     * Configure the RNG (Random Number Generator) device. The RNG device provides entropy to guests to ensure good quality random numbers for guest applications that require them. Can only be set by `root@pam.` See the [Proxmox documentation](https://pve.proxmox.com/pve-docs/pve-admin-guide.html#qm_virtual_machines_settings) for more information.
     */
    declare public readonly rng: pulumi.Output<outputs.VmRng | undefined>;
    /**
     * Set to true to stop (rather than shutdown) the VM on destroy (defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>).
     */
    declare public readonly stopOnDestroy: pulumi.Output<boolean>;
    /**
     * The tags assigned to the VM.
     */
    declare public readonly tags: pulumi.Output<string[]>;
    /**
     * Set to true to create a VM template.
     */
    declare public readonly template: pulumi.Output<boolean | undefined>;
    declare public readonly timeouts: pulumi.Output<outputs.VmTimeouts | undefined>;
    /**
     * Configure the VGA Hardware. If you want to use high resolution modes (>= 1280x1024x16) you may need to increase the vga memory option. Since QEMU 2.9 the default VGA display type is <span pulumi-lang-nodejs="`std`" pulumi-lang-dotnet="`Std`" pulumi-lang-go="`std`" pulumi-lang-python="`std`" pulumi-lang-yaml="`std`" pulumi-lang-java="`std`" pulumi-lang-hcl="`std`">`std`</span> for all OS types besides some Windows versions (XP and older) which use <span pulumi-lang-nodejs="`cirrus`" pulumi-lang-dotnet="`Cirrus`" pulumi-lang-go="`cirrus`" pulumi-lang-python="`cirrus`" pulumi-lang-yaml="`cirrus`" pulumi-lang-java="`cirrus`" pulumi-lang-hcl="`cirrus`">`cirrus`</span>. The <span pulumi-lang-nodejs="`qxl`" pulumi-lang-dotnet="`Qxl`" pulumi-lang-go="`qxl`" pulumi-lang-python="`qxl`" pulumi-lang-yaml="`qxl`" pulumi-lang-java="`qxl`" pulumi-lang-hcl="`qxl`">`qxl`</span> option enables the SPICE display server. For win* OS you can select how many independent displays you want, Linux guests can add displays themself. You can also run without any graphic card, using a serial device as terminal. See the [Proxmox documentation](https://pve.proxmox.com/pve-docs/pve-admin-guide.html#qm_virtual_machines_settings) section 10.2.8 for more information and available configuration parameters.
     */
    declare public readonly vga: pulumi.Output<outputs.VmVga | undefined>;
    /**
     * The unique identifier of the VM in the Proxmox cluster.
     */
    declare public readonly vmId: pulumi.Output<number>;

    /**
     * Create a Vm resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VmArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VmArgs | VmState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VmState | undefined;
            resourceInputs["cdrom"] = state?.cdrom;
            resourceInputs["cpu"] = state?.cpu;
            resourceInputs["deleteUnreferencedDisksOnDestroy"] = state?.deleteUnreferencedDisksOnDestroy;
            resourceInputs["description"] = state?.description;
            resourceInputs["name"] = state?.name;
            resourceInputs["nodeName"] = state?.nodeName;
            resourceInputs["purgeOnDestroy"] = state?.purgeOnDestroy;
            resourceInputs["rng"] = state?.rng;
            resourceInputs["stopOnDestroy"] = state?.stopOnDestroy;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["template"] = state?.template;
            resourceInputs["timeouts"] = state?.timeouts;
            resourceInputs["vga"] = state?.vga;
            resourceInputs["vmId"] = state?.vmId;
        } else {
            const args = argsOrState as VmArgs | undefined;
            if (args?.nodeName === undefined && !opts.urn) {
                throw new Error("Missing required property 'nodeName'");
            }
            resourceInputs["cdrom"] = args?.cdrom;
            resourceInputs["cpu"] = args?.cpu;
            resourceInputs["deleteUnreferencedDisksOnDestroy"] = args?.deleteUnreferencedDisksOnDestroy;
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
            resourceInputs["nodeName"] = args?.nodeName;
            resourceInputs["purgeOnDestroy"] = args?.purgeOnDestroy;
            resourceInputs["rng"] = args?.rng;
            resourceInputs["stopOnDestroy"] = args?.stopOnDestroy;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["template"] = args?.template;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["vga"] = args?.vga;
            resourceInputs["vmId"] = args?.vmId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Vm.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Vm resources.
 */
export interface VmState {
    /**
     * The CD-ROM configuration. The key is the interface of the CD-ROM, could be one of `ideN`, `sataN`, `scsiN`, where N is the index of the interface. Note that <span pulumi-lang-nodejs="`q35`" pulumi-lang-dotnet="`Q35`" pulumi-lang-go="`q35`" pulumi-lang-python="`q35`" pulumi-lang-yaml="`q35`" pulumi-lang-java="`q35`" pulumi-lang-hcl="`q35`">`q35`</span> machine type only supports <span pulumi-lang-nodejs="`ide0`" pulumi-lang-dotnet="`Ide0`" pulumi-lang-go="`ide0`" pulumi-lang-python="`ide0`" pulumi-lang-yaml="`ide0`" pulumi-lang-java="`ide0`" pulumi-lang-hcl="`ide0`">`ide0`</span> and <span pulumi-lang-nodejs="`ide2`" pulumi-lang-dotnet="`Ide2`" pulumi-lang-go="`ide2`" pulumi-lang-python="`ide2`" pulumi-lang-yaml="`ide2`" pulumi-lang-java="`ide2`" pulumi-lang-hcl="`ide2`">`ide2`</span> of IDE interfaces.
     */
    cdrom?: pulumi.Input<{[key: string]: pulumi.Input<inputs.VmCdrom>} | undefined>;
    /**
     * The CPU configuration.
     */
    cpu?: pulumi.Input<inputs.VmCpu | undefined>;
    /**
     * Set to true to delete unreferenced disks on destroy (defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>).
     */
    deleteUnreferencedDisksOnDestroy?: pulumi.Input<boolean | undefined>;
    /**
     * The description of the VM.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The name of the VM. Doesn't have to be unique.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The name of the node where the VM is provisioned.
     */
    nodeName?: pulumi.Input<string | undefined>;
    /**
     * Set to true to purge the VM from backup configurations on destroy (defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>).
     */
    purgeOnDestroy?: pulumi.Input<boolean | undefined>;
    /**
     * Configure the RNG (Random Number Generator) device. The RNG device provides entropy to guests to ensure good quality random numbers for guest applications that require them. Can only be set by `root@pam.` See the [Proxmox documentation](https://pve.proxmox.com/pve-docs/pve-admin-guide.html#qm_virtual_machines_settings) for more information.
     */
    rng?: pulumi.Input<inputs.VmRng | undefined>;
    /**
     * Set to true to stop (rather than shutdown) the VM on destroy (defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>).
     */
    stopOnDestroy?: pulumi.Input<boolean | undefined>;
    /**
     * The tags assigned to the VM.
     */
    tags?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Set to true to create a VM template.
     */
    template?: pulumi.Input<boolean | undefined>;
    timeouts?: pulumi.Input<inputs.VmTimeouts | undefined>;
    /**
     * Configure the VGA Hardware. If you want to use high resolution modes (>= 1280x1024x16) you may need to increase the vga memory option. Since QEMU 2.9 the default VGA display type is <span pulumi-lang-nodejs="`std`" pulumi-lang-dotnet="`Std`" pulumi-lang-go="`std`" pulumi-lang-python="`std`" pulumi-lang-yaml="`std`" pulumi-lang-java="`std`" pulumi-lang-hcl="`std`">`std`</span> for all OS types besides some Windows versions (XP and older) which use <span pulumi-lang-nodejs="`cirrus`" pulumi-lang-dotnet="`Cirrus`" pulumi-lang-go="`cirrus`" pulumi-lang-python="`cirrus`" pulumi-lang-yaml="`cirrus`" pulumi-lang-java="`cirrus`" pulumi-lang-hcl="`cirrus`">`cirrus`</span>. The <span pulumi-lang-nodejs="`qxl`" pulumi-lang-dotnet="`Qxl`" pulumi-lang-go="`qxl`" pulumi-lang-python="`qxl`" pulumi-lang-yaml="`qxl`" pulumi-lang-java="`qxl`" pulumi-lang-hcl="`qxl`">`qxl`</span> option enables the SPICE display server. For win* OS you can select how many independent displays you want, Linux guests can add displays themself. You can also run without any graphic card, using a serial device as terminal. See the [Proxmox documentation](https://pve.proxmox.com/pve-docs/pve-admin-guide.html#qm_virtual_machines_settings) section 10.2.8 for more information and available configuration parameters.
     */
    vga?: pulumi.Input<inputs.VmVga | undefined>;
    /**
     * The unique identifier of the VM in the Proxmox cluster.
     */
    vmId?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a Vm resource.
 */
export interface VmArgs {
    /**
     * The CD-ROM configuration. The key is the interface of the CD-ROM, could be one of `ideN`, `sataN`, `scsiN`, where N is the index of the interface. Note that <span pulumi-lang-nodejs="`q35`" pulumi-lang-dotnet="`Q35`" pulumi-lang-go="`q35`" pulumi-lang-python="`q35`" pulumi-lang-yaml="`q35`" pulumi-lang-java="`q35`" pulumi-lang-hcl="`q35`">`q35`</span> machine type only supports <span pulumi-lang-nodejs="`ide0`" pulumi-lang-dotnet="`Ide0`" pulumi-lang-go="`ide0`" pulumi-lang-python="`ide0`" pulumi-lang-yaml="`ide0`" pulumi-lang-java="`ide0`" pulumi-lang-hcl="`ide0`">`ide0`</span> and <span pulumi-lang-nodejs="`ide2`" pulumi-lang-dotnet="`Ide2`" pulumi-lang-go="`ide2`" pulumi-lang-python="`ide2`" pulumi-lang-yaml="`ide2`" pulumi-lang-java="`ide2`" pulumi-lang-hcl="`ide2`">`ide2`</span> of IDE interfaces.
     */
    cdrom?: pulumi.Input<{[key: string]: pulumi.Input<inputs.VmCdrom>} | undefined>;
    /**
     * The CPU configuration.
     */
    cpu?: pulumi.Input<inputs.VmCpu | undefined>;
    /**
     * Set to true to delete unreferenced disks on destroy (defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>).
     */
    deleteUnreferencedDisksOnDestroy?: pulumi.Input<boolean | undefined>;
    /**
     * The description of the VM.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The name of the VM. Doesn't have to be unique.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The name of the node where the VM is provisioned.
     */
    nodeName: pulumi.Input<string>;
    /**
     * Set to true to purge the VM from backup configurations on destroy (defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>).
     */
    purgeOnDestroy?: pulumi.Input<boolean | undefined>;
    /**
     * Configure the RNG (Random Number Generator) device. The RNG device provides entropy to guests to ensure good quality random numbers for guest applications that require them. Can only be set by `root@pam.` See the [Proxmox documentation](https://pve.proxmox.com/pve-docs/pve-admin-guide.html#qm_virtual_machines_settings) for more information.
     */
    rng?: pulumi.Input<inputs.VmRng | undefined>;
    /**
     * Set to true to stop (rather than shutdown) the VM on destroy (defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>).
     */
    stopOnDestroy?: pulumi.Input<boolean | undefined>;
    /**
     * The tags assigned to the VM.
     */
    tags?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Set to true to create a VM template.
     */
    template?: pulumi.Input<boolean | undefined>;
    timeouts?: pulumi.Input<inputs.VmTimeouts | undefined>;
    /**
     * Configure the VGA Hardware. If you want to use high resolution modes (>= 1280x1024x16) you may need to increase the vga memory option. Since QEMU 2.9 the default VGA display type is <span pulumi-lang-nodejs="`std`" pulumi-lang-dotnet="`Std`" pulumi-lang-go="`std`" pulumi-lang-python="`std`" pulumi-lang-yaml="`std`" pulumi-lang-java="`std`" pulumi-lang-hcl="`std`">`std`</span> for all OS types besides some Windows versions (XP and older) which use <span pulumi-lang-nodejs="`cirrus`" pulumi-lang-dotnet="`Cirrus`" pulumi-lang-go="`cirrus`" pulumi-lang-python="`cirrus`" pulumi-lang-yaml="`cirrus`" pulumi-lang-java="`cirrus`" pulumi-lang-hcl="`cirrus`">`cirrus`</span>. The <span pulumi-lang-nodejs="`qxl`" pulumi-lang-dotnet="`Qxl`" pulumi-lang-go="`qxl`" pulumi-lang-python="`qxl`" pulumi-lang-yaml="`qxl`" pulumi-lang-java="`qxl`" pulumi-lang-hcl="`qxl`">`qxl`</span> option enables the SPICE display server. For win* OS you can select how many independent displays you want, Linux guests can add displays themself. You can also run without any graphic card, using a serial device as terminal. See the [Proxmox documentation](https://pve.proxmox.com/pve-docs/pve-admin-guide.html#qm_virtual_machines_settings) section 10.2.8 for more information and available configuration parameters.
     */
    vga?: pulumi.Input<inputs.VmVga | undefined>;
    /**
     * The unique identifier of the VM in the Proxmox cluster.
     */
    vmId?: pulumi.Input<number | undefined>;
}
