---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: wildbitca-provider-family-cloudflare
spec:
  package: oci.chezmoi.sh/xpkg.upbound.io/wildbitca/provider-family-cloudflare:v0.2.6
  runtimeConfigRef:
    name: hardened
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: wildbitca-provider-cloudflare-account
spec:
  package: oci.chezmoi.sh/xpkg.upbound.io/wildbitca/provider-cloudflare-account:v0.2.6
  runtimeConfigRef:
    name: hardened
  skipDependencyResolution: true
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: wildbitca-provider-cloudflare-zone
spec:
  package: oci.chezmoi.sh/xpkg.upbound.io/wildbitca/provider-cloudflare-zone:v0.2.6
  runtimeConfigRef:
    name: hardened
  skipDependencyResolution: true
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: wildbitca-provider-cloudflare-dns
spec:
  package: oci.chezmoi.sh/xpkg.upbound.io/wildbitca/provider-cloudflare-dns:v0.2.6
  runtimeConfigRef:
    name: hardened
  skipDependencyResolution: true
