---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-family-oci
spec:
  package: oci.chezmoi.sh/ghcr.io/oracle/provider-family-oci:v1.1.0
  runtimeConfigRef:
    name: hardened
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-oci-core
spec:
  package: oci.chezmoi.sh/ghcr.io/oracle/provider-oci-core:v1.1.0
  runtimeConfigRef:
    name: hardened
  skipDependencyResolution: true
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-oci-objectstorage
spec:
  package: oci.chezmoi.sh/ghcr.io/oracle/provider-oci-objectstorage:v1.1.0
  runtimeConfigRef:
    name: hardened
  skipDependencyResolution: true
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-oci-networking
spec:
  package: oci.chezmoi.sh/ghcr.io/oracle/provider-oci-networking:v1.1.0
  runtimeConfigRef:
    name: hardened
  skipDependencyResolution: true
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-oci-networkfirewall
spec:
  package: oci.chezmoi.sh/ghcr.io/oracle/provider-oci-networkfirewall:v1.1.0
  runtimeConfigRef:
    name: hardened
  skipDependencyResolution: true
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-oci-blockstorage
spec:
  package: oci.chezmoi.sh/ghcr.io/oracle/provider-oci-blockstorage:v1.1.0
  runtimeConfigRef:
    name: hardened
  skipDependencyResolution: true
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-oci-compute
spec:
  package: oci.chezmoi.sh/ghcr.io/oracle/provider-oci-compute:v1.1.0
  runtimeConfigRef:
    name: hardened
  skipDependencyResolution: true
