---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
spec:
  config:
    server:
      root_url: https://o11y.chezmoi.sh
    auth.generic_oauth:
      enabled: "true"
      name: Pocket ID
      auth_url: https://auth.chezmoi.sh/authorize
      token_url: https://auth.chezmoi.sh/api/oidc/token
      api_url: https://auth.chezmoi.sh/api/oidc/userinfo
      scopes: openid profile email
      use_pkce: "true"
      allow_sign_up: "true"
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              envFrom:
                - secretRef:
                    name: grafana-oidc-client
                - secretRef:
                    name: grafana-admin-credentials
