---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc-client
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    name: grafana-oidc-client
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .client_id }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .client_secret }}"
  data:
    - secretKey: client_id
      remoteRef:
        key: rhodes.akn/grafana/auth/oidc-client
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: rhodes.akn/grafana/auth/oidc-client
        property: client_secret
