apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: o11y-system

helmCharts:
  - repo: https://grafana.github.io/helm-charts
    name: grafana-operator
    # renovate: datasource=helm depName=grafana-operator registryUrl=https://grafana.github.io/helm-charts
    version: v5.24.0
    releaseName: grafana-operator
    namespace: o11y-system
    valuesFile: ../../../../../../catalog/kubernetes/o11y/helm/grafana/default.helmvalues.yaml

resources:
  - security/
  - grafana.instance.yaml
  - grafana.oidc.externalsecret.yaml
  - grafana.admin-credentials.externalsecret.yaml
  - grafana.database.externalsecret.yaml
  - grafana.cnpg.objectstore.yaml
  - grafana.cnpg.cluster.yaml
  - grafana.cnpg.scheduledbackup.yaml
  - grafana.main.httproute.yaml
  - datasources/
  - dashboards/

images:
  - name: ghcr.io/grafana/grafana-operator
    newName: oci.chezmoi.sh/ghcr.io/grafana/grafana-operator
  - name: docker.io/grafana/grafana
    newName: oci.chezmoi.sh/docker.io/grafana/grafana
