// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { SignupTokensArgs } from "./signupTokens";
export type SignupTokens = import("./signupTokens").SignupTokens;
export const SignupTokens: typeof import("./signupTokens").SignupTokens = null as any;
utilities.lazyLoad(exports, ["SignupTokens"], () => require("./signupTokens"));

export { UsersArgs } from "./users";
export type Users = import("./users").Users;
export const Users: typeof import("./users").Users = null as any;
utilities.lazyLoad(exports, ["Users"], () => require("./users"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "pocket-id-api:users:SignupTokens":
                return new SignupTokens(name, <any>undefined, { urn })
            case "pocket-id-api:users:Users":
                return new Users(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("pocket-id-api", "users", _module)
