---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale-system

resources:
  # Required secrets and ProxyClass for Tailscale Operator
  - restricted.proxyclass.yaml
  - operator-oauth.externalsecret.yaml

helmCharts:
  - repo: https://pkgs.tailscale.com/helmcharts
    name: tailscale-operator
    version: 1.98.3

    releaseName: tailscale-operator
    namespace: tailscale-system

    valuesInline:
      operatorConfig:
        hostname: lungmen-akn
    valuesFile: tailscale.helmvalues/default.yaml
    additionalValuesFiles:
      - tailscale.helmvalues/hardened.yaml
    includeCRDs: true

images:
  - name: tailscale/k8s-operator
    newName: oci.chezmoi.sh/docker.io/tailscale/k8s-operator
