// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ApiToken extends pulumi.CustomResource {
	/**
	 * Get an existing ApiToken resource's state with the given name, ID, and optional extra
	 * properties used to qualify the lookup.
	 *
	 * @param name The _unique_ name of the resulting resource.
	 * @param id The _unique_ provider ID of the resource to lookup.
	 * @param state Any extra arguments used during the lookup.
	 * @param opts Optional settings to control the behavior of the CustomResource.
	 */
	public static get(
		name: string,
		id: pulumi.Input<pulumi.ID>,
		state?: ApiTokenState,
		opts?: pulumi.CustomResourceOptions,
	): ApiToken {
		return new ApiToken(name, <any>state, { ...opts, id: id });
	}

	/** @internal */
	public static readonly __pulumiType = "pbs:index/apiToken:ApiToken";

	/**
	 * Returns true if the given object is an instance of ApiToken.  This is designed to work even
	 * when multiple copies of the Pulumi SDK have been loaded into the same process.
	 */
	public static isInstance(obj: any): obj is ApiToken {
		if (obj === undefined || obj === null) {
			return false;
		}
		return obj["__pulumiType"] === ApiToken.__pulumiType;
	}

	/**
	 * Optional token comment. PBS token metadata is treated as immutable here, so changes force replacement.
	 */
	public declare readonly comment: pulumi.Output<string | undefined>;
	/**
	 * Opaque digest returned by PBS for optimistic locking.
	 */
	public declare readonly /*out*/ digest: pulumi.Output<string>;
	/**
	 * Whether the token is enabled. PBS token metadata is treated as immutable here, so changes force replacement.
	 */
	public declare readonly enable: pulumi.Output<boolean | undefined>;
	/**
	 * Token expiration time as a Unix timestamp. PBS token metadata is treated as immutable here, so changes force replacement.
	 */
	public declare readonly expire: pulumi.Output<number | undefined>;
	/**
	 * Token name segment appended to the user ID, for example <span pulumi-lang-nodejs="`terraform`" pulumi-lang-dotnet="`Terraform`" pulumi-lang-go="`terraform`" pulumi-lang-python="`terraform`" pulumi-lang-yaml="`terraform`" pulumi-lang-java="`terraform`" pulumi-lang-hcl="`terraform`">`terraform`</span> in `backup-operator@pbs!terraform`.
	 */
	public declare readonly tokenName: pulumi.Output<string>;
	/**
	 * Full PBS token ID in `userid!token_name` format.
	 */
	public declare readonly /*out*/ tokenid: pulumi.Output<string>;
	/**
	 * The PBS user ID that owns the token, for example `backup-operator@pbs`.
	 */
	public declare readonly userid: pulumi.Output<string>;
	/**
	 * One-time token secret returned by PBS when the token is created. PBS does not return this value again on subsequent reads.
	 */
	public declare readonly /*out*/ value: pulumi.Output<string>;

	/**
	 * Create a ApiToken resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 * @param opts A bag of options that control this resource's behavior.
	 */
	constructor(
		name: string,
		args: ApiTokenArgs,
		opts?: pulumi.CustomResourceOptions,
	);
	constructor(
		name: string,
		argsOrState?: ApiTokenArgs | ApiTokenState,
		opts?: pulumi.CustomResourceOptions,
	) {
		let resourceInputs: pulumi.Inputs = {};
		opts = opts || {};
		if (opts.id) {
			const state = argsOrState as ApiTokenState | undefined;
			resourceInputs["comment"] = state?.comment;
			resourceInputs["digest"] = state?.digest;
			resourceInputs["enable"] = state?.enable;
			resourceInputs["expire"] = state?.expire;
			resourceInputs["tokenName"] = state?.tokenName;
			resourceInputs["tokenid"] = state?.tokenid;
			resourceInputs["userid"] = state?.userid;
			resourceInputs["value"] = state?.value;
		} else {
			const args = argsOrState as ApiTokenArgs | undefined;
			if (args?.tokenName === undefined && !opts.urn) {
				throw new Error("Missing required property 'tokenName'");
			}
			if (args?.userid === undefined && !opts.urn) {
				throw new Error("Missing required property 'userid'");
			}
			resourceInputs["comment"] = args?.comment;
			resourceInputs["enable"] = args?.enable;
			resourceInputs["expire"] = args?.expire;
			resourceInputs["tokenName"] = args?.tokenName;
			resourceInputs["userid"] = args?.userid;
			resourceInputs["digest"] = undefined; /*out*/
			resourceInputs["tokenid"] = undefined; /*out*/
			resourceInputs["value"] = undefined; /*out*/
		}
		opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
		const secretOpts = { additionalSecretOutputs: ["value"] };
		opts = pulumi.mergeOptions(opts, secretOpts);
		super(
			ApiToken.__pulumiType,
			name,
			resourceInputs,
			opts,
			false /*dependency*/,
			utilities.getPackage(),
		);
	}
}

/**
 * Input properties used for looking up and filtering ApiToken resources.
 */
export interface ApiTokenState {
	/**
	 * Optional token comment. PBS token metadata is treated as immutable here, so changes force replacement.
	 */
	comment?: pulumi.Input<string | undefined>;
	/**
	 * Opaque digest returned by PBS for optimistic locking.
	 */
	digest?: pulumi.Input<string | undefined>;
	/**
	 * Whether the token is enabled. PBS token metadata is treated as immutable here, so changes force replacement.
	 */
	enable?: pulumi.Input<boolean | undefined>;
	/**
	 * Token expiration time as a Unix timestamp. PBS token metadata is treated as immutable here, so changes force replacement.
	 */
	expire?: pulumi.Input<number | undefined>;
	/**
	 * Token name segment appended to the user ID, for example <span pulumi-lang-nodejs="`terraform`" pulumi-lang-dotnet="`Terraform`" pulumi-lang-go="`terraform`" pulumi-lang-python="`terraform`" pulumi-lang-yaml="`terraform`" pulumi-lang-java="`terraform`" pulumi-lang-hcl="`terraform`">`terraform`</span> in `backup-operator@pbs!terraform`.
	 */
	tokenName?: pulumi.Input<string | undefined>;
	/**
	 * Full PBS token ID in `userid!token_name` format.
	 */
	tokenid?: pulumi.Input<string | undefined>;
	/**
	 * The PBS user ID that owns the token, for example `backup-operator@pbs`.
	 */
	userid?: pulumi.Input<string | undefined>;
	/**
	 * One-time token secret returned by PBS when the token is created. PBS does not return this value again on subsequent reads.
	 */
	value?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ApiToken resource.
 */
export interface ApiTokenArgs {
	/**
	 * Optional token comment. PBS token metadata is treated as immutable here, so changes force replacement.
	 */
	comment?: pulumi.Input<string | undefined>;
	/**
	 * Whether the token is enabled. PBS token metadata is treated as immutable here, so changes force replacement.
	 */
	enable?: pulumi.Input<boolean | undefined>;
	/**
	 * Token expiration time as a Unix timestamp. PBS token metadata is treated as immutable here, so changes force replacement.
	 */
	expire?: pulumi.Input<number | undefined>;
	/**
	 * Token name segment appended to the user ID, for example <span pulumi-lang-nodejs="`terraform`" pulumi-lang-dotnet="`Terraform`" pulumi-lang-go="`terraform`" pulumi-lang-python="`terraform`" pulumi-lang-yaml="`terraform`" pulumi-lang-java="`terraform`" pulumi-lang-hcl="`terraform`">`terraform`</span> in `backup-operator@pbs!terraform`.
	 */
	tokenName: pulumi.Input<string>;
	/**
	 * The PBS user ID that owns the token, for example `backup-operator@pbs`.
	 */
	userid: pulumi.Input<string>;
}
