// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getNamespaces(
	args: GetNamespacesArgs,
	opts?: pulumi.InvokeOptions,
): Promise<GetNamespacesResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invoke(
		"pbs:index/getNamespaces:getNamespaces",
		{
			maxDepth: args.maxDepth,
			prefix: args.prefix,
			store: args.store,
		},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of arguments for invoking getNamespaces.
 */
export interface GetNamespacesArgs {
	maxDepth?: number;
	prefix?: string;
	store: string;
}

/**
 * A collection of values returned by getNamespaces.
 */
export interface GetNamespacesResult {
	/**
	 * The provider-assigned unique ID for this managed resource.
	 */
	readonly id: string;
	readonly maxDepth?: number;
	readonly namespaces: outputs.GetNamespacesNamespace[];
	readonly prefix?: string;
	readonly store: string;
}
export function getNamespacesOutput(
	args: GetNamespacesOutputArgs,
	opts?: pulumi.InvokeOutputOptions,
): pulumi.Output<GetNamespacesResult> {
	opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
	return pulumi.runtime.invokeOutput(
		"pbs:index/getNamespaces:getNamespaces",
		{
			maxDepth: args.maxDepth,
			prefix: args.prefix,
			store: args.store,
		},
		opts,
		utilities.getPackage(),
	);
}

/**
 * A collection of arguments for invoking getNamespaces.
 */
export interface GetNamespacesOutputArgs {
	maxDepth?: pulumi.Input<number | undefined>;
	prefix?: pulumi.Input<string | undefined>;
	store: pulumi.Input<string>;
}
