// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class MetricsServer extends pulumi.CustomResource {
	/**
	 * Get an existing MetricsServer resource's state with the given name, ID, and optional extra
	 * properties used to qualify the lookup.
	 *
	 * @param name The _unique_ name of the resulting resource.
	 * @param id The _unique_ provider ID of the resource to lookup.
	 * @param state Any extra arguments used during the lookup.
	 * @param opts Optional settings to control the behavior of the CustomResource.
	 */
	public static get(
		name: string,
		id: pulumi.Input<pulumi.ID>,
		state?: MetricsServerState,
		opts?: pulumi.CustomResourceOptions,
	): MetricsServer {
		return new MetricsServer(name, <any>state, { ...opts, id: id });
	}

	/** @internal */
	public static readonly __pulumiType = "pbs:index/metricsServer:MetricsServer";

	/**
	 * Returns true if the given object is an instance of MetricsServer.  This is designed to work even
	 * when multiple copies of the Pulumi SDK have been loaded into the same process.
	 */
	public static isInstance(obj: any): obj is MetricsServer {
		if (obj === undefined || obj === null) {
			return false;
		}
		return obj["__pulumiType"] === MetricsServer.__pulumiType;
	}

	/**
	 * InfluxDB bucket name where metrics will be stored. Required for `influxdb-http` type.
	 */
	public declare readonly bucket: pulumi.Output<string | undefined>;
	/**
	 * A comment describing this metrics server configuration.
	 */
	public declare readonly comment: pulumi.Output<string | undefined>;
	/**
	 * Enable or disable metrics export to this server. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
	 */
	public declare readonly enable: pulumi.Output<boolean>;
	/**
	 * Maximum body size for HTTP requests in bytes. Only applicable for `influxdb-http` type. Defaults to <span pulumi-lang-nodejs="`25000000`" pulumi-lang-dotnet="`25000000`" pulumi-lang-go="`25000000`" pulumi-lang-python="`25000000`" pulumi-lang-yaml="`25000000`" pulumi-lang-java="`25000000`" pulumi-lang-hcl="`25000000`">`25000000`</span> (25MB).
	 */
	public declare readonly maxBodySize: pulumi.Output<number>;
	/**
	 * Maximum transmission unit for the metrics connection. Defaults to <span pulumi-lang-nodejs="`1500`" pulumi-lang-dotnet="`1500`" pulumi-lang-go="`1500`" pulumi-lang-python="`1500`" pulumi-lang-yaml="`1500`" pulumi-lang-java="`1500`" pulumi-lang-hcl="`1500`">`1500`</span>.
	 */
	public declare readonly mtu: pulumi.Output<number>;
	/**
	 * The unique name identifier for the metrics server. This is used to identify the metrics server configuration.
	 */
	public declare readonly name: pulumi.Output<string>;
	/**
	 * InfluxDB organization name. Required for `influxdb-http` type.
	 */
	public declare readonly organization: pulumi.Output<string | undefined>;
	/**
	 * The server port. Typical ports: <span pulumi-lang-nodejs="`8089`" pulumi-lang-dotnet="`8089`" pulumi-lang-go="`8089`" pulumi-lang-python="`8089`" pulumi-lang-yaml="`8089`" pulumi-lang-java="`8089`" pulumi-lang-hcl="`8089`">`8089`</span> (InfluxDB UDP), <span pulumi-lang-nodejs="`8086`" pulumi-lang-dotnet="`8086`" pulumi-lang-go="`8086`" pulumi-lang-python="`8086`" pulumi-lang-yaml="`8086`" pulumi-lang-java="`8086`" pulumi-lang-hcl="`8086`">`8086`</span> (InfluxDB HTTP). Can be used instead of <span pulumi-lang-nodejs="`url`" pulumi-lang-dotnet="`Url`" pulumi-lang-go="`url`" pulumi-lang-python="`url`" pulumi-lang-yaml="`url`" pulumi-lang-java="`url`" pulumi-lang-hcl="`url`">`url`</span> for backwards compatibility.
	 */
	public declare readonly port: pulumi.Output<number | undefined>;
	/**
	 * Protocol for InfluxDB UDP connection. Valid values: <span pulumi-lang-nodejs="`udp`" pulumi-lang-dotnet="`Udp`" pulumi-lang-go="`udp`" pulumi-lang-python="`udp`" pulumi-lang-yaml="`udp`" pulumi-lang-java="`udp`" pulumi-lang-hcl="`udp`">`udp`</span>, <span pulumi-lang-nodejs="`tcp`" pulumi-lang-dotnet="`Tcp`" pulumi-lang-go="`tcp`" pulumi-lang-python="`tcp`" pulumi-lang-yaml="`tcp`" pulumi-lang-java="`tcp`" pulumi-lang-hcl="`tcp`">`tcp`</span>. Only applicable for `influxdb-udp` type.
	 */
	public declare readonly protocol: pulumi.Output<string | undefined>;
	/**
	 * The server address (hostname or IP) of the metrics server. Can be used instead of <span pulumi-lang-nodejs="`url`" pulumi-lang-dotnet="`Url`" pulumi-lang-go="`url`" pulumi-lang-python="`url`" pulumi-lang-yaml="`url`" pulumi-lang-java="`url`" pulumi-lang-hcl="`url`">`url`</span> for backwards compatibility.
	 */
	public declare readonly server: pulumi.Output<string | undefined>;
	/**
	 * HTTP request timeout in seconds. Only applicable for `influxdb-http` type. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
	 */
	public declare readonly timeout: pulumi.Output<number>;
	/**
	 * InfluxDB API token for authentication. Required for `influxdb-http` type.
	 */
	public declare readonly token: pulumi.Output<string | undefined>;
	/**
	 * The type of metrics server. Valid values: `influxdb-udp`, `influxdb-http`.
	 */
	public declare readonly type: pulumi.Output<string>;
	/**
	 * Full URL for InfluxDB HTTP, including protocol (e.g., `http://influxdb:8086` or `https://influxdb:443`). If specified, this takes precedence over separate <span pulumi-lang-nodejs="`server`" pulumi-lang-dotnet="`Server`" pulumi-lang-go="`server`" pulumi-lang-python="`server`" pulumi-lang-yaml="`server`" pulumi-lang-java="`server`" pulumi-lang-hcl="`server`">`server`</span> and <span pulumi-lang-nodejs="`port`" pulumi-lang-dotnet="`Port`" pulumi-lang-go="`port`" pulumi-lang-python="`port`" pulumi-lang-yaml="`port`" pulumi-lang-java="`port`" pulumi-lang-hcl="`port`">`port`</span> fields. Only applicable for `influxdb-http` type.
	 */
	public declare readonly url: pulumi.Output<string | undefined>;
	/**
	 * Whether to verify TLS certificate for HTTPS connections. Only applicable for `influxdb-http` type. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
	 */
	public declare readonly verifyTls: pulumi.Output<boolean>;

	/**
	 * Create a MetricsServer resource with the given unique name, arguments, and options.
	 *
	 * @param name The _unique_ name of the resource.
	 * @param args The arguments to use to populate this resource's properties.
	 * @param opts A bag of options that control this resource's behavior.
	 */
	constructor(
		name: string,
		args: MetricsServerArgs,
		opts?: pulumi.CustomResourceOptions,
	);
	constructor(
		name: string,
		argsOrState?: MetricsServerArgs | MetricsServerState,
		opts?: pulumi.CustomResourceOptions,
	) {
		let resourceInputs: pulumi.Inputs = {};
		opts = opts || {};
		if (opts.id) {
			const state = argsOrState as MetricsServerState | undefined;
			resourceInputs["bucket"] = state?.bucket;
			resourceInputs["comment"] = state?.comment;
			resourceInputs["enable"] = state?.enable;
			resourceInputs["maxBodySize"] = state?.maxBodySize;
			resourceInputs["mtu"] = state?.mtu;
			resourceInputs["name"] = state?.name;
			resourceInputs["organization"] = state?.organization;
			resourceInputs["port"] = state?.port;
			resourceInputs["protocol"] = state?.protocol;
			resourceInputs["server"] = state?.server;
			resourceInputs["timeout"] = state?.timeout;
			resourceInputs["token"] = state?.token;
			resourceInputs["type"] = state?.type;
			resourceInputs["url"] = state?.url;
			resourceInputs["verifyTls"] = state?.verifyTls;
		} else {
			const args = argsOrState as MetricsServerArgs | undefined;
			if (args?.type === undefined && !opts.urn) {
				throw new Error("Missing required property 'type'");
			}
			resourceInputs["bucket"] = args?.bucket;
			resourceInputs["comment"] = args?.comment;
			resourceInputs["enable"] = args?.enable;
			resourceInputs["maxBodySize"] = args?.maxBodySize;
			resourceInputs["mtu"] = args?.mtu;
			resourceInputs["name"] = args?.name;
			resourceInputs["organization"] = args?.organization;
			resourceInputs["port"] = args?.port;
			resourceInputs["protocol"] = args?.protocol;
			resourceInputs["server"] = args?.server;
			resourceInputs["timeout"] = args?.timeout;
			resourceInputs["token"] = args?.token
				? pulumi.secret(args.token)
				: undefined;
			resourceInputs["type"] = args?.type;
			resourceInputs["url"] = args?.url;
			resourceInputs["verifyTls"] = args?.verifyTls;
		}
		opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
		const secretOpts = { additionalSecretOutputs: ["token"] };
		opts = pulumi.mergeOptions(opts, secretOpts);
		super(
			MetricsServer.__pulumiType,
			name,
			resourceInputs,
			opts,
			false /*dependency*/,
			utilities.getPackage(),
		);
	}
}

/**
 * Input properties used for looking up and filtering MetricsServer resources.
 */
export interface MetricsServerState {
	/**
	 * InfluxDB bucket name where metrics will be stored. Required for `influxdb-http` type.
	 */
	bucket?: pulumi.Input<string | undefined>;
	/**
	 * A comment describing this metrics server configuration.
	 */
	comment?: pulumi.Input<string | undefined>;
	/**
	 * Enable or disable metrics export to this server. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
	 */
	enable?: pulumi.Input<boolean | undefined>;
	/**
	 * Maximum body size for HTTP requests in bytes. Only applicable for `influxdb-http` type. Defaults to <span pulumi-lang-nodejs="`25000000`" pulumi-lang-dotnet="`25000000`" pulumi-lang-go="`25000000`" pulumi-lang-python="`25000000`" pulumi-lang-yaml="`25000000`" pulumi-lang-java="`25000000`" pulumi-lang-hcl="`25000000`">`25000000`</span> (25MB).
	 */
	maxBodySize?: pulumi.Input<number | undefined>;
	/**
	 * Maximum transmission unit for the metrics connection. Defaults to <span pulumi-lang-nodejs="`1500`" pulumi-lang-dotnet="`1500`" pulumi-lang-go="`1500`" pulumi-lang-python="`1500`" pulumi-lang-yaml="`1500`" pulumi-lang-java="`1500`" pulumi-lang-hcl="`1500`">`1500`</span>.
	 */
	mtu?: pulumi.Input<number | undefined>;
	/**
	 * The unique name identifier for the metrics server. This is used to identify the metrics server configuration.
	 */
	name?: pulumi.Input<string | undefined>;
	/**
	 * InfluxDB organization name. Required for `influxdb-http` type.
	 */
	organization?: pulumi.Input<string | undefined>;
	/**
	 * The server port. Typical ports: <span pulumi-lang-nodejs="`8089`" pulumi-lang-dotnet="`8089`" pulumi-lang-go="`8089`" pulumi-lang-python="`8089`" pulumi-lang-yaml="`8089`" pulumi-lang-java="`8089`" pulumi-lang-hcl="`8089`">`8089`</span> (InfluxDB UDP), <span pulumi-lang-nodejs="`8086`" pulumi-lang-dotnet="`8086`" pulumi-lang-go="`8086`" pulumi-lang-python="`8086`" pulumi-lang-yaml="`8086`" pulumi-lang-java="`8086`" pulumi-lang-hcl="`8086`">`8086`</span> (InfluxDB HTTP). Can be used instead of <span pulumi-lang-nodejs="`url`" pulumi-lang-dotnet="`Url`" pulumi-lang-go="`url`" pulumi-lang-python="`url`" pulumi-lang-yaml="`url`" pulumi-lang-java="`url`" pulumi-lang-hcl="`url`">`url`</span> for backwards compatibility.
	 */
	port?: pulumi.Input<number | undefined>;
	/**
	 * Protocol for InfluxDB UDP connection. Valid values: <span pulumi-lang-nodejs="`udp`" pulumi-lang-dotnet="`Udp`" pulumi-lang-go="`udp`" pulumi-lang-python="`udp`" pulumi-lang-yaml="`udp`" pulumi-lang-java="`udp`" pulumi-lang-hcl="`udp`">`udp`</span>, <span pulumi-lang-nodejs="`tcp`" pulumi-lang-dotnet="`Tcp`" pulumi-lang-go="`tcp`" pulumi-lang-python="`tcp`" pulumi-lang-yaml="`tcp`" pulumi-lang-java="`tcp`" pulumi-lang-hcl="`tcp`">`tcp`</span>. Only applicable for `influxdb-udp` type.
	 */
	protocol?: pulumi.Input<string | undefined>;
	/**
	 * The server address (hostname or IP) of the metrics server. Can be used instead of <span pulumi-lang-nodejs="`url`" pulumi-lang-dotnet="`Url`" pulumi-lang-go="`url`" pulumi-lang-python="`url`" pulumi-lang-yaml="`url`" pulumi-lang-java="`url`" pulumi-lang-hcl="`url`">`url`</span> for backwards compatibility.
	 */
	server?: pulumi.Input<string | undefined>;
	/**
	 * HTTP request timeout in seconds. Only applicable for `influxdb-http` type. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
	 */
	timeout?: pulumi.Input<number | undefined>;
	/**
	 * InfluxDB API token for authentication. Required for `influxdb-http` type.
	 */
	token?: pulumi.Input<string | undefined>;
	/**
	 * The type of metrics server. Valid values: `influxdb-udp`, `influxdb-http`.
	 */
	type?: pulumi.Input<string | undefined>;
	/**
	 * Full URL for InfluxDB HTTP, including protocol (e.g., `http://influxdb:8086` or `https://influxdb:443`). If specified, this takes precedence over separate <span pulumi-lang-nodejs="`server`" pulumi-lang-dotnet="`Server`" pulumi-lang-go="`server`" pulumi-lang-python="`server`" pulumi-lang-yaml="`server`" pulumi-lang-java="`server`" pulumi-lang-hcl="`server`">`server`</span> and <span pulumi-lang-nodejs="`port`" pulumi-lang-dotnet="`Port`" pulumi-lang-go="`port`" pulumi-lang-python="`port`" pulumi-lang-yaml="`port`" pulumi-lang-java="`port`" pulumi-lang-hcl="`port`">`port`</span> fields. Only applicable for `influxdb-http` type.
	 */
	url?: pulumi.Input<string | undefined>;
	/**
	 * Whether to verify TLS certificate for HTTPS connections. Only applicable for `influxdb-http` type. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
	 */
	verifyTls?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a MetricsServer resource.
 */
export interface MetricsServerArgs {
	/**
	 * InfluxDB bucket name where metrics will be stored. Required for `influxdb-http` type.
	 */
	bucket?: pulumi.Input<string | undefined>;
	/**
	 * A comment describing this metrics server configuration.
	 */
	comment?: pulumi.Input<string | undefined>;
	/**
	 * Enable or disable metrics export to this server. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
	 */
	enable?: pulumi.Input<boolean | undefined>;
	/**
	 * Maximum body size for HTTP requests in bytes. Only applicable for `influxdb-http` type. Defaults to <span pulumi-lang-nodejs="`25000000`" pulumi-lang-dotnet="`25000000`" pulumi-lang-go="`25000000`" pulumi-lang-python="`25000000`" pulumi-lang-yaml="`25000000`" pulumi-lang-java="`25000000`" pulumi-lang-hcl="`25000000`">`25000000`</span> (25MB).
	 */
	maxBodySize?: pulumi.Input<number | undefined>;
	/**
	 * Maximum transmission unit for the metrics connection. Defaults to <span pulumi-lang-nodejs="`1500`" pulumi-lang-dotnet="`1500`" pulumi-lang-go="`1500`" pulumi-lang-python="`1500`" pulumi-lang-yaml="`1500`" pulumi-lang-java="`1500`" pulumi-lang-hcl="`1500`">`1500`</span>.
	 */
	mtu?: pulumi.Input<number | undefined>;
	/**
	 * The unique name identifier for the metrics server. This is used to identify the metrics server configuration.
	 */
	name?: pulumi.Input<string | undefined>;
	/**
	 * InfluxDB organization name. Required for `influxdb-http` type.
	 */
	organization?: pulumi.Input<string | undefined>;
	/**
	 * The server port. Typical ports: <span pulumi-lang-nodejs="`8089`" pulumi-lang-dotnet="`8089`" pulumi-lang-go="`8089`" pulumi-lang-python="`8089`" pulumi-lang-yaml="`8089`" pulumi-lang-java="`8089`" pulumi-lang-hcl="`8089`">`8089`</span> (InfluxDB UDP), <span pulumi-lang-nodejs="`8086`" pulumi-lang-dotnet="`8086`" pulumi-lang-go="`8086`" pulumi-lang-python="`8086`" pulumi-lang-yaml="`8086`" pulumi-lang-java="`8086`" pulumi-lang-hcl="`8086`">`8086`</span> (InfluxDB HTTP). Can be used instead of <span pulumi-lang-nodejs="`url`" pulumi-lang-dotnet="`Url`" pulumi-lang-go="`url`" pulumi-lang-python="`url`" pulumi-lang-yaml="`url`" pulumi-lang-java="`url`" pulumi-lang-hcl="`url`">`url`</span> for backwards compatibility.
	 */
	port?: pulumi.Input<number | undefined>;
	/**
	 * Protocol for InfluxDB UDP connection. Valid values: <span pulumi-lang-nodejs="`udp`" pulumi-lang-dotnet="`Udp`" pulumi-lang-go="`udp`" pulumi-lang-python="`udp`" pulumi-lang-yaml="`udp`" pulumi-lang-java="`udp`" pulumi-lang-hcl="`udp`">`udp`</span>, <span pulumi-lang-nodejs="`tcp`" pulumi-lang-dotnet="`Tcp`" pulumi-lang-go="`tcp`" pulumi-lang-python="`tcp`" pulumi-lang-yaml="`tcp`" pulumi-lang-java="`tcp`" pulumi-lang-hcl="`tcp`">`tcp`</span>. Only applicable for `influxdb-udp` type.
	 */
	protocol?: pulumi.Input<string | undefined>;
	/**
	 * The server address (hostname or IP) of the metrics server. Can be used instead of <span pulumi-lang-nodejs="`url`" pulumi-lang-dotnet="`Url`" pulumi-lang-go="`url`" pulumi-lang-python="`url`" pulumi-lang-yaml="`url`" pulumi-lang-java="`url`" pulumi-lang-hcl="`url`">`url`</span> for backwards compatibility.
	 */
	server?: pulumi.Input<string | undefined>;
	/**
	 * HTTP request timeout in seconds. Only applicable for `influxdb-http` type. Defaults to <span pulumi-lang-nodejs="`5`" pulumi-lang-dotnet="`5`" pulumi-lang-go="`5`" pulumi-lang-python="`5`" pulumi-lang-yaml="`5`" pulumi-lang-java="`5`" pulumi-lang-hcl="`5`">`5`</span>.
	 */
	timeout?: pulumi.Input<number | undefined>;
	/**
	 * InfluxDB API token for authentication. Required for `influxdb-http` type.
	 */
	token?: pulumi.Input<string | undefined>;
	/**
	 * The type of metrics server. Valid values: `influxdb-udp`, `influxdb-http`.
	 */
	type: pulumi.Input<string>;
	/**
	 * Full URL for InfluxDB HTTP, including protocol (e.g., `http://influxdb:8086` or `https://influxdb:443`). If specified, this takes precedence over separate <span pulumi-lang-nodejs="`server`" pulumi-lang-dotnet="`Server`" pulumi-lang-go="`server`" pulumi-lang-python="`server`" pulumi-lang-yaml="`server`" pulumi-lang-java="`server`" pulumi-lang-hcl="`server`">`server`</span> and <span pulumi-lang-nodejs="`port`" pulumi-lang-dotnet="`Port`" pulumi-lang-go="`port`" pulumi-lang-python="`port`" pulumi-lang-yaml="`port`" pulumi-lang-java="`port`" pulumi-lang-hcl="`port`">`port`</span> fields. Only applicable for `influxdb-http` type.
	 */
	url?: pulumi.Input<string | undefined>;
	/**
	 * Whether to verify TLS certificate for HTTPS connections. Only applicable for `influxdb-http` type. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
	 */
	verifyTls?: pulumi.Input<boolean | undefined>;
}
