---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - repo: oci://ghcr.io/sergelogvinov/charts
    name: proxmox-cloud-controller-manager
    # renovate: datasource=helm depName=proxmox-cloud-controller-manager registryUrl=oci://ghcr.io/sergelogvinov/charts
    version: 0.2.28

    releaseName: proxmox-cloud-controller-manager
    namespace: kube-system

    valuesFile: helmvalues/default.yaml
