---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespaces
  - namespace.chezmoi-sh.yaml

  # Required modules
  - ../../../../../catalog/crossplane/domainidentity.amazonses.chezmoi.sh
  - ../../../../../catalog/crossplane/clustervault.vault.chezmoi.sh

  # Crossplane global configuration
  - functions.yaml
  - runtimeconfigs.yaml

  # Cloudflare resources
  - cloudflare.iam.observability.yaml
  - cloudflare.iam.oci-registry.yaml
  - cloudflare.iam.omni.yaml
  - cloudflare.iam.terraform-provider.yaml

  # Tailscale resources
  - tailscale.oauth.observability.yaml

  # AWS resources
  - aws.domainidentity.yaml

patches:
  - # NOTE: Crossplane API extensions must be applied before applying the resources
    patch: |
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-1"
    target:
      group: apiextensions.crossplane.io
