# TODO: need to configure ESO to use Tailscale with specific rights to
#       access the secrets.
---
extraObjects:
  # NOTE: kubevault is the default secret store for External Secrets Operator.
  #       Because this cluster is the same as the one where the secrets are
  #       stored, we don't need any trickery to access the secrets.
  - apiVersion: external-secrets.io/v1
    kind: ClusterSecretStore
    metadata:
      name: kubevault
    spec:
      provider: {} # TODO: configure this to use Tailscale
  - apiVersion: external-secrets.io/v1
    kind: ClusterSecretStore
    metadata:
      name: vault.amiya.akn
    spec:
      provider:
        vault:
          server: https://vault.chezmoi.sh
          path: secret/data/amiya.akn
          version: v2
          auth:
            kubernetes:
              mountPath: amiya.akn
              role: amiya.akn-eso-role
              serviceAccountRef:
                name: external-secrets
                namespace: external-secrets-system
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: external-secrets-operator:system:auth-delegator
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: system:auth-delegator
    subjects:
      - kind: ServiceAccount
        name: external-secrets
        namespace: external-secrets-system
