---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-database-linkding
spec:
  dataFrom:
    - extract:
        key: lungmen.akn/linkding/database/postgresql
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    name: linkding-database-linkding
    template:
      data:
        username: linkding
        password: "{{ .password }}"
