---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-admin-credentials
spec:
  dataFrom:
    - extract:
        key: lungmen.akn/forgejo/admin/credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    name: forgejo-admin-credentials
    template:
      type: Opaque
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
