---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo

labels:
  - pairs:
      app.kubernetes.io/name: forgejo
      app.kubernetes.io/instance: forgejo
    includeTemplates: true
    includeSelectors: true

resources:
  - forgejo.deployment.yaml
  - forgejo.httproute.yaml
  - forgejo.database.externalsecret.yaml
  - forgejo.admin.externalsecret.yaml
  - forgejo.oidc.externalsecret.yaml

  - security/

images:
  # renovate: datasource=docker depName=codeberg.org/forgejo/forgejo
  - name: codeberg.org/forgejo/forgejo
    newTag: "13.0"
