---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/zone: internal
  name: openbao-internal
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: internal
      namespace: ingress-gateway-system
      sectionName: chezmoi.sh-websecure
  hostnames:
    - vault.chezmoi.sh
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: openbao-ui
          port: 8200
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
