#ENC[AES256_GCM,data:XVMNXcOx3MAA+Zzwbju53djE9jwTWK/GUmBibbQWsBg3ODSoR7Q6ZIYpMHJaJIqLgZqKd/gm0jgI1sNNHPMY/yz03kgJ4kzwFSO/k+qO7NN4,iv:aojaLXsUEkakbUoQid921o1O3vR5te06vXCEjCwx8T0=,tag:uCCV4wjZByRBG8DAdkNh3A==,type:comment]
#ENC[AES256_GCM,data:JsYWp1BcmFcHpFHPzRb2mV5YmGiZ2dZqj9g2BAKj3leSohl0,iv:KjmNMZVTFfgCrO9l9xiPEhiqGSDPRppyNDkCTyjxaMw=,tag:zEIWZCrc2X9A8j9kxdwiMA==,type:comment]
#ENC[AES256_GCM,data:66ypMxTW0bxJPmK/bIHfDWbOWbJzkBmhA9SY3jbBavPc0SySVbsqsUIJT3XO6jeivD7qXJd3Z5zl+xnWUcxC2bJ8WWzafSeDjC2WixShjwK5IDVF0z95Bsp7angN5tYypWvXJnPN3ki2,iv:SNIf8pVVCh2gi+OMHxONsflumXTF9Uplb2hcsHmwzUw=,tag:239cgXHmaj30Nw+8YnPY+g==,type:comment]
cloudflare_dns_api_token: ENC[AES256_GCM,data:MMLd7YhUyZcn3UmQHWYdtW4GmEPVDByqyop3uhuGiU3MzHlQngfyWpk7VYX8waIEP3s5e+M=,iv:TNuXziSV2E7OT9/Op4N3NqY7nCqJJcFh6szrKHzf2yg=,tag:3sxLGCPQXLD09gfMHI7iUw==,type:str]
#ENC[AES256_GCM,data:wJG9fXPvlv98r7NO0m2RNmRMq18H+CBrFzjq6S8rTYvn6aag/FbCnDT523j9awEnrJjLH4iJlwhrnW7bZO6plwYpcQBRQ3u9fT9FxZYaJe7dfNGCjizMJfrcV+lYAHbGr5H05VfU0go=,iv:LTqc1S2zFe7iLOTvhggnbLO/w3Wnw2FgpV7PgECaq3c=,tag:02XwSwRoadaAGkVzHRpTcw==,type:comment]
pangolin_server_secret: ENC[AES256_GCM,data:iPFoojMxKZSx62A9T9TlbnRpnUoX1NJTjWlvOBehP/ghja52h9FCFXZCoUI=,iv:lWThW+vDYbAVnrpR9A9R9NSgM6a3rG6fcPDtIyDt+wc=,tag:jmh0UDRWx6ur+BxM1MVp6A==,type:str]
pangolin_smtp_user: ENC[AES256_GCM,data:GDwUM1rlPQTpTvu84l1mGMJky2+RVNc/hsXlkc7dG2w=,iv:s61gT3ahS4qGGfQ4zx/35NWfK367Cial1bw245jwB6o=,tag:1UfQLH7zPzP8P23z8oRgEA==,type:str]
pangolin_smtp_pass: ENC[AES256_GCM,data:dDQHx5yOF+733aGAM1MweVDlqDL5xT0E9SAkjAEprk4=,iv:47knGeVVLwcEh+APZMjl4lsIbRBtw7eIk5zoxhbHX2Q=,tag:wPcBg4hf2FHz3g0YPGTRig==,type:str]
#ENC[AES256_GCM,data:zYUsh6BFOuxvc5i01shVjCZ4X1rQu7w0fvO/7w+OhppHV4AIgw0xDghgQ33QeSdgxDbPtZ9uY6aq6HHrpNUV3HogHyCZHvvL0cmFtXjpxfdX1SFdHjG1obPG1rR2ZbNXKJGzSBgO/k2UlttNAyLiO5Iovq/d7HbdvJVpU9+j,iv:YRGcAjPCdvgNhrG08mu33vwurmKJh4C7/J9lsoOwQbc=,tag:5zgs4c91rwIPV9xBVULF+Q==,type:comment]
tailscale_authkey: ENC[AES256_GCM,data:PKaLYSEof+0rvSpd1/Eq6aUahhcF61xVJTGTmQhigQqRTZSn5w0Pe5bvrqHGtrCThUy5DGiY3pU9etOd2A==,iv:3yfucrKoTgQlOtZDX0PM276Knjvq6/p+pYb2ejSkr00=,tag:C/PL1XxI7J4NcQ9NDbqSrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUjdrcTh1dmVYRkNDWGIz
            dVBhb1ZlVEZtaDFSTFNJdnEzSmorTmpiNGhnCjdpTXduTjg2ajNBOG5QRWkzWEI0
            UkJlbnBmQ1l5NWJCRGxPelNrZ3ZJMFUKLS0tIFMvQXJDSGNvUXBBdDlKWWRlbmJN
            Z202bHBiZ3Q2UU90NzNnK25NUUZueGsK3WGtxeyezwC6JZZTfhQupzFcTBDaCvOk
            NecfKzJNW8cSQcIVDItYxfRwjioebhEBVX20z5BKUfQSnapXTeJJiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fj0yj3na3n5udfjmnxfwrlkp80tvj49w80wh699x33dh48clnvnshtjxe9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOXUxRFZrREE4eERQQWsy
            aU9hVDh1QlFLa0tyRzl5TW4yYXAzdng1Q1FZCnF3M1gwL095dTYwV2pCRjBKRC9R
            c2luYUVxS0N1L29mYzNqQy85VjArdzAKLS0tIHN2UDhUK0RPaUhYMXhYMGE5Rzkr
            dENXWWphZm9IY3pkQ2x2bTQ2M0JHSXMKcqSb6lm+1VClp8z3Vpctu1f/FxQQNVQX
            GBJOnJM4N9Gw7neka0RCUhyZOoyPOk7/JDPhyVaaonAYNq+as2TNig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dwj7uy6h0k8zg3yhtc5sxjzy4u5hnsjywt6l8fcm5a75g8nfkd2svh0wr7
    lastmodified: "2026-10-10T12:52:28Z"
    mac: ENC[AES256_GCM,data:LFft9bOqzM15jiH+Ppb0Cj3t/fRN1WBMZwKaYeMmbkV74w0giawExJEtYNOgeG3/5jAKF1mefqOPZSxmwHZ+8v8QvloBsHqF4yxBtx3jyKo4Zlq+uPLytYRbJ4diq/ukDRtnfyNOmNL9uOuplJwg9q+58m5/xj0HucJXPPEv8hA=,iv:wAgT8suhPr1ZVrWElCt2IyrJ6x8QO65hzX9Z1foUsMc=,tag:TerSzBsYHpwwaI7grVTBsA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
