apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns-system

helmCharts:
  - repo: https://kubernetes-sigs.github.io/external-dns
    name: external-dns
    version: 1.21.1

    releaseName: external-dns-unifi
    namespace: external-dns-system

    valuesFile: unifi.helmvalues/default.yaml
    additionalValuesFiles:
      - unifi.helmvalues/hardened.yaml
    includeCRDs: true

resources:
  - unifi.externalsecret.yaml

images:
  - name: registry.k8s.io/external-dns/external-dns
    newName: oci.chezmoi.sh/registry.k8s.io/external-dns/external-dns
  - name: ghcr.io/kashalls/external-dns-unifi-webhook
    newName: oci.chezmoi.sh/ghcr.io/kashalls/external-dns-unifi-webhook
