apiVersion: v1
kind: Secret
metadata:
  name: external-dns-bind-secret
type: Opaque
stringData:
  tsig-secret: ENC[AES256_GCM,data:lGifVhctGdZgdhPW0l2flyFDDY+HoFA2HY3u4vJKRqBmqEqohFPHxLGT0Z4=,iv:IqaUCNNOCiW6MnEXcLOv3imJfG/QLaPBj99pSuuzTpM=,tag:52I6xWUTEoFvqt7VxfNe7g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNVJpWGlqcG81QlJJZlhx
        ZHBMTTNndi81cUxqc1pVZTZxVmpnWnZybVRJCkxNelNEK1FkQXQwUU4yU2pobFc2
        bXFESEtneXRTdlJjcGRlOTlZdkJwWTAKLS0tIHROV3ZpTnRNM1NrNmJ3NkQ4cTB2
        b25ZNEg0eS9PT0JHWEJnOHhDWit5czAKo3Zt9pc/4CQjOrLR5THx9M2jLi9/8emI
        07JxuWMLegiZLVzqthIF2MVPghFBWlZuVPCbUx9hIoCnwZyuW8J1yw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fj0yj3na3n5udfjmnxfwrlkp80tvj49w80wh699x33dh48clnvnshtjxe9
  encrypted_regex: ^(stringData|data)$
  lastmodified: "2026-07-27T14:31:22Z"
  mac: ENC[AES256_GCM,data:1Yt5VfyHT/DDWY9Vn8OX6q/ODuUCrkKehHV/Vsv15A8+0yhDIBINTN+6l5sDfpzLVje9+NXb/W6Lyc9b59NTkWjf5WMbh/bRB4JbOtRNnX6bFUH3y4aiJ/CGg0m4eqpPpsGMnmlTv/P4ImW6sQ5lOMU2T5vUFoyO6OuI9NMlREQ=,iv:XHPMQgZRzRkDWt6bxvB7Oe+BmH9br6P98kXgrd7uUJQ=,tag:X1588B5/mzWY81GEhCdn4Q==,type:str]
  version: 3.13.3
