---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: openbao-database
spec:
  backupOwnerReference: cluster
  cluster:
    name: openbao-database
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  schedule: "@weekly"
