---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spoolman

labels:
  - pairs:
      app.kubernetes.io/name: spoolman
      app.kubernetes.io/instance: spoolman
    includeTemplates: true
    includeSelectors: true

resources:
  - spoolman.database.externalsecret.yaml
  - spoolman.deployment.yaml
  - spoolman.httproute.yaml

  - security/

images:
  # renovate: datasource=docker depName=ghcr.io/donkie/spoolman
  - name: ghcr.io/donkie/spoolman
    newName: oci.chezmoi.sh/ghcr.io/donkie/spoolman
    newTag: "0.26.1"
