apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  annotations:
    policy.networking.k8s.io/description: |
      Allows n8n to access the mutualized PostgreSQL database.
  name: allow-n8n-to-databases
  namespace: n8n
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: n8n
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: databases
            app.kubernetes.io/instance: postgres-apps
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
