---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-mcp-to-kube-api
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: mcpremoteproxy
  egress:
    - toEntities:
        - kube-apiserver
