// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Apis extends pulumi.CustomResource {
    /**
     * Get an existing Apis resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Apis {
        return new Apis(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pocket-id-api:index:Apis';

    /**
     * Returns true if the given object is an instance of Apis.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Apis {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Apis.__pulumiType;
    }

    declare public /*out*/ readonly createdAt: pulumi.Output<string | undefined>;
    declare public readonly name: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly permissions: pulumi.Output<outputs.ApiApiPermissionResponseDto[] | undefined>;
    declare public readonly resource: pulumi.Output<string | undefined>;

    /**
     * Create a Apis resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApisArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.resource === undefined && !opts.urn) {
                throw new Error("Missing required property 'resource'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["resource"] = args?.resource;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["permissions"] = undefined /*out*/;
        } else {
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["permissions"] = undefined /*out*/;
            resourceInputs["resource"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Apis.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * The set of arguments for constructing a Apis resource.
 */
export interface ApisArgs {
    name: pulumi.Input<string>;
    resource: pulumi.Input<string>;
}
