// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ApisArgs } from "./apis";
export type Apis = import("./apis").Apis;
export const Apis: typeof import("./apis").Apis = null as any;
utilities.lazyLoad(exports, ["Apis"], () => require("./apis"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { ScimServiceProviderArgs } from "./scimServiceProvider";
export type ScimServiceProvider = import("./scimServiceProvider").ScimServiceProvider;
export const ScimServiceProvider: typeof import("./scimServiceProvider").ScimServiceProvider = null as any;
utilities.lazyLoad(exports, ["ScimServiceProvider"], () => require("./scimServiceProvider"));


// Export sub-modules:
import * as apikeys from "./apikeys";
import * as config from "./config";
import * as oidc from "./oidc";
import * as types from "./types";
import * as usergroups from "./usergroups";
import * as users from "./users";

export {
    apikeys,
    config,
    oidc,
    types,
    usergroups,
    users,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "pocket-id-api:index:Apis":
                return new Apis(name, <any>undefined, { urn })
            case "pocket-id-api:index:ScimServiceProvider":
                return new ScimServiceProvider(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("pocket-id-api", "index", _module)
pulumi.runtime.registerResourcePackage("pocket-id-api", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:pocket-id-api") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
