// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class ScimServiceProvider extends pulumi.CustomResource {
    /**
     * Get an existing ScimServiceProvider resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ScimServiceProvider {
        return new ScimServiceProvider(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pocket-id-api:index:ScimServiceProvider';

    /**
     * Returns true if the given object is an instance of ScimServiceProvider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ScimServiceProvider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ScimServiceProvider.__pulumiType;
    }

    declare public /*out*/ readonly createdAt: pulumi.Output<string | undefined>;
    declare public readonly endpoint: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly lastSyncedAt: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly oidcClient: pulumi.Output<outputs.DtoOidcClientMetaDataDto | undefined>;
    declare public readonly oidcClientId: pulumi.Output<string | undefined>;
    declare public readonly token: pulumi.Output<string | undefined>;

    /**
     * Create a ScimServiceProvider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ScimServiceProviderArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.endpoint === undefined && !opts.urn) {
                throw new Error("Missing required property 'endpoint'");
            }
            if (args?.oidcClientId === undefined && !opts.urn) {
                throw new Error("Missing required property 'oidcClientId'");
            }
            resourceInputs["endpoint"] = args?.endpoint;
            resourceInputs["oidcClientId"] = args?.oidcClientId;
            resourceInputs["token"] = args?.token;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["lastSyncedAt"] = undefined /*out*/;
            resourceInputs["oidcClient"] = undefined /*out*/;
        } else {
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["endpoint"] = undefined /*out*/;
            resourceInputs["lastSyncedAt"] = undefined /*out*/;
            resourceInputs["oidcClient"] = undefined /*out*/;
            resourceInputs["oidcClientId"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ScimServiceProvider.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * The set of arguments for constructing a ScimServiceProvider resource.
 */
export interface ScimServiceProviderArgs {
    endpoint: pulumi.Input<string>;
    oidcClientId: pulumi.Input<string>;
    token?: pulumi.Input<string | undefined>;
}
