apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - network-policy.default-hardened.yaml
  - network-policy.allow-openbao-from-cilium-gateway.yaml
  - network-policy.allow-openbao-to-kubernetes-api.yaml
  - network-policy.allow-openbao-to-lungmen-api.yaml
  - network-policy.allow-openbao-to-pocket-id.yaml
  - network-policy.allow-postgres-to-s3-backup.yaml
