---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless-ngx

labels:
  - pairs:
      app.kubernetes.io/name: paperless-ngx
      app.kubernetes.io/instance: paperless-ngx
    includeTemplates: true
    includeSelectors: true

resources:
  - paperless-ngx.configuration.externalsecret.yaml
  - paperless-ngx.httproute.yaml
  - paperless-ngx.postgresql-backup.yaml
  - paperless-ngx.postgresql-objectstore.yaml
  - paperless-ngx.postgresql.yaml
  - paperless-ngx.redis.yaml
  - paperless-ngx.smb-storage.yaml
  - paperless-ngx.statefulset.yaml

  - security/

images:
  # renovate: datasource=docker depName=ghcr.io/paperless-ngx/paperless-ngx
  - name: ghcr.io/paperless-ngx/paperless-ngx
    newTag: 2.20.15@sha256:6c86cad803970ea782683a8e80e7403444c5bf3cf70de63b4d3c8e87500db92f
  # renovate: datasource=docker depName=docker.io/library/redis
  - name: docker.io/library/redis
    newTag: 8.6.2-alpine@sha256:c5e375abb885e6b2021c0377879e4890bf76f9065b8922ffc113f2b226b9fc17
