---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless-ngx

labels:
  - pairs:
      app.kubernetes.io/name: paperless-ngx
      app.kubernetes.io/instance: paperless-ngx
    includeTemplates: true
    includeSelectors: true

resources:
  - paperless-ngx.configuration.externalsecret.yaml
  - paperless-ngx.httproute.yaml
  - paperless-ngx.postgresql-backup.yaml
  - paperless-ngx.postgresql-objectstore.yaml
  - paperless-ngx.postgresql.yaml
  - paperless-ngx.redis.yaml
  - paperless-ngx.smb-storage.yaml
  - paperless-ngx.statefulset.yaml

  - security/

images:
  # renovate: datasource=docker depName=ghcr.io/paperless-ngx/paperless-ngx
  - name: ghcr.io/paperless-ngx/paperless-ngx
    newTag: 2.20.14@sha256:b89f83345532cfba72690185257eb6c4f92fc2a782332a42abe19c07b7a6595f
  # renovate: datasource=docker depName=docker.io/library/redis
  - name: docker.io/library/redis
    newTag: 8.6.2-alpine@sha256:81b6f81d6a6c5b9019231a2e8eb10085e3a139a34f833dcc965a8a959b040b72
