---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-database-paperless
spec:
  dataFrom:
    - extract:
        key: lungmen.akn/paperless-ngx/database/postgresql
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    name: paperless-ngx-database-paperless
    template:
      data:
        username: paperless
        password: "{{ .password }}"
