---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-api-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    name: grafana-api-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: lungmen.akn/o11y/grafana/api-token
        property: token
