{{- /*
externalsecret.yaml
Renders one ExternalSecret per database user.
Consumes the locally generated password and produces a Kubernetes Secret 
that applications can use to connect.
*/ -}}

{{- $root := . -}}
{{- $clusterName  := include "mutualized-cnpg-databases.clusterName" . -}}
{{- $prefix := include "mutualized-cnpg-databases.resourcePrefix" . -}}

{{- range .Values.spec.databases -}}
  {{- $db := . -}}
  {{- range .users -}}
    {{- $user := . -}}
    {{- $secretName := include "mutualized-cnpg-databases.userCredentialsName" (dict "prefix" $prefix "db" $db "user" $user) -}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
  {{- $labels := include "mutualized-cnpg-databases.defaultLabels" (dict "root" $root "instance" $clusterName) | fromYaml }}
  labels:
    {{- toYaml $labels | nindent 4 }}
    mutualized.cloudnative-pg.io/database: {{ $db.name }}
    mutualized.cloudnative-pg.io/user: {{ $user.name }}
  {{- $annotations := include "mutualized-cnpg-databases.defaultAnnotations" (dict "root" $root) | fromYaml }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: "0" # Immutable passwords; change behavior to rotate.
  target:
    name: {{ $secretName }}
    template:
      engineVersion: v2
      metadata:
        {{- $labels := include "mutualized-cnpg-databases.defaultLabels" (dict "root" $root "instance" $clusterName) | fromYaml }}
        labels:
          {{- toYaml $labels | nindent 10 }}
          mutualized.cloudnative-pg.io/database: {{ $db.name }}
          mutualized.cloudnative-pg.io/user: {{ $user.name }}
        {{- $annotations := include "mutualized-cnpg-databases.defaultAnnotations" (dict "root" $root) | fromYaml }}
        {{- with $annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      data:
        username: '{{ `{{ .username }}` }}'
        password: '{{ `{{ .password }}` }}'
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: {{ include "mutualized-cnpg-databases.userCredentialsName" (dict "prefix" $prefix "db" $db "user" $user) }}
{{ end -}}
{{ end -}}
