{{- /*
externalsecret.yaml
Renders one ExternalSecret per database user.
Consumes the locally generated password and produces a Kubernetes Secret 
that applications can use to connect.
*/ -}}

{{- $root := . -}}
{{- $prefix := include "mutualized-cnpg-databases.resourcePrefix" . -}}

{{- range .Values.spec.databases -}}
  {{- $db := . -}}
  {{- range .users -}}
    {{- $user := . -}}
    {{- $secretName := include "mutualized-cnpg-databases.userSecretName" (dict "prefix" $prefix "db" $db "user" $user) -}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
  {{- include "mutualized-cnpg-databases.resourceMetadata" (dict "root" $root "instance" $prefix "extraLabels" (dict "mutualized-cnpg-databases/database" $db.name "mutualized-cnpg-databases/user" $user.name)) | nindent 2 }}
spec:
  refreshInterval: "0" # Immutable passwords; change behavior to rotate.
  target:
    name: {{ $secretName }}
    template:
      engineVersion: v2
      metadata:
        {{- include "mutualized-cnpg-databases.resourceMetadata" (dict "root" $root "instance" $prefix "extraLabels" (dict "mutualized-cnpg-databases/database" $db.name "mutualized-cnpg-databases/user" $user.name)) | nindent 8 }}
      data:
        username: '{{ `{{ .username }}` }}'
        password: '{{ `{{ .password }}` }}'
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: {{ include "mutualized-cnpg-databases.userGeneratorName" (dict "prefix" $prefix "db" $db "user" $user) }}
{{ end -}}
{{ end -}}
