{{- /*
passwordgenerator.yaml
Generates secure random passwords using the External Secrets Operator (ESO).
These passwords are used by ExternalSecrets and then pushed to Vault.
*/ -}}

{{- $root := . -}}
{{- $clusterName  := include "mutualized-cnpg-databases.clusterName" . -}}
{{- $prefix := include "mutualized-cnpg-databases.resourcePrefix" . -}}

{{- range .Values.spec.databases -}}
  {{- $db := . -}}
  {{- range .users -}}
    {{- $user := . -}}
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ include "mutualized-cnpg-databases.userCredentialsName" (dict "prefix" $prefix "db" $db "user" $user) }}
  {{- $labels := include "mutualized-cnpg-databases.defaultLabels" (dict "root" $root "instance" $clusterName) | fromYaml }}
  labels:
    {{- toYaml $labels | nindent 4 }}
    mutualized.cloudnative-pg.io/database: {{ $db.name }}
    mutualized.cloudnative-pg.io/user: {{ $user.name }}
  {{- $annotations := include "mutualized-cnpg-databases.defaultAnnotations" (dict "root" $root) | fromYaml -}}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  length: {{ $root.Values.spec.behavior.passwords.length | default 32 }}
  digits: {{ div ($root.Values.spec.behavior.passwords.length | default 32) 4 }}
  symbols: {{ div ($root.Values.spec.behavior.passwords.length | default 32) 8 }}
  symbolCharacters: "-._~"
  allowRepeat: true
{{ end -}}
{{ end -}}
