{{- /*
passwordgenerator.yaml
Generates secure random passwords using the External Secrets Operator (ESO).
These passwords are used by ExternalSecrets and then pushed to Vault.
*/ -}}

{{- $root := . -}}
{{- $prefix := include "mutualized-cnpg-databases.resourcePrefix" . -}}

{{- range .Values.spec.databases -}}
  {{- $db := . -}}
  {{- range .users -}}
    {{- $user := . -}}
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ include "mutualized-cnpg-databases.userGeneratorName" (dict "prefix" $prefix "db" $db "user" $user) }}
  {{- include "mutualized-cnpg-databases.resourceMetadata" (dict "root" $root "instance" $prefix "extraLabels" (dict "mutualized-cnpg-databases/database" $db.name "mutualized-cnpg-databases/user" $user.name)) | nindent 2 }}
spec:
  length: {{ $root.Values.spec.behavior.passwords.length | default 32 }}
  digits: {{ div ($root.Values.spec.behavior.passwords.length | default 32) 4 }}
  symbols: {{ div ($root.Values.spec.behavior.passwords.length | default 32) 8 }}
  symbolCharacters: "-._~"
  allowRepeat: true
{{ end -}}
{{ end -}}
