{{- /*
pushsecret.yaml
Pushes generated credentials from the local Kubernetes Secret to Vault.
Creates a PushSecret resources per user that points to the Read-Write service endpoint.
*/ -}}

{{- $root := . -}}
{{- $clusterName := include "mutualized-cnpg-databases.clusterName" . -}}
{{- $prefix := include "mutualized-cnpg-databases.resourcePrefix" . -}}

{{- range .Values.spec.databases -}}
  {{- $db := . -}}
  {{- range .users -}}
    {{- $user := . -}}
    {{- $secretName := include "mutualized-cnpg-databases.userCredentialsName" (dict "prefix" $prefix "db" $db "user" $user) -}}
    {{- $targetCluster := $db.cluster | default $clusterName -}}
    {{- $rwHost := printf "%s-rw.%s.svc" $targetCluster $root.Release.Namespace -}}
    {{- $roHost := printf "%s-ro.%s.svc" $targetCluster $root.Release.Namespace -}}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ include "mutualized-cnpg-databases.userCredentialsName" (dict "prefix" $prefix "db" $db "user" $user) }}
  {{- $labels := include "mutualized-cnpg-databases.defaultLabels" (dict "root" $root "instance" $clusterName) | fromYaml }}
  labels:
    {{- toYaml $labels | nindent 4 }}
    mutualized.cloudnative-pg.io/database: {{ $db.name }}
    mutualized.cloudnative-pg.io/user: {{ $user.name }}
  {{- $annotations := include "mutualized-cnpg-databases.defaultAnnotations" (dict "root" $root) | fromYaml }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ $root.Values.spec.behavior.passwords.pushInterval | default "5m" }}
  secretStoreRefs:
    - kind: {{ include "mutualized-cnpg-databases.userSecretStoreKind" (dict "root" $root "user" $user) }}
      name: {{ include "mutualized-cnpg-databases.userSecretStoreName" (dict "root" $root "user" $user) }}
  selector:
    secret:
      name: {{ $secretName }}
  updatePolicy: Replace
  deletionPolicy: Delete
  template:
    data:
      username: '{{ `{{ .username }}` }}'
      password: '{{ `{{ .password }}` }}'
      host: {{ $rwHost }}
      port: "5432"
      dbname: {{ $db.name }}
      uri: postgresql://{{ `{{ .username }}` }}:{{ `{{ .password }}` }}@{{ $rwHost }}:5432/{{ $db.name }}
      jdbc-uri: jdbc:postgresql://{{ $rwHost }}:5432/{{ $db.name }}?user={{ `{{ .username }}` }}&password={{ `{{ .password }}` }}
      pgpass: {{ $rwHost }}:5432:{{ $db.name }}:{{ `{{ .username }}` }}:{{ `{{ .password }}` }}
  data:
    - conversionStrategy: None
      match:
        secretKey: username
        remoteRef:
          remoteKey: {{ include "mutualized-cnpg-databases.userVaultKey" (dict "db" $db "user" $user) }}
          property: username
    - conversionStrategy: None
      match:
        secretKey: password
        remoteRef:
          remoteKey: {{ include "mutualized-cnpg-databases.userVaultKey" (dict "db" $db "user" $user) }}
          property: password
    - conversionStrategy: None
      match:
        secretKey: host
        remoteRef:
          remoteKey: {{ include "mutualized-cnpg-databases.userVaultKey" (dict "db" $db "user" $user) }}
          property: host
    - conversionStrategy: None
      match:
        secretKey: port
        remoteRef:
          remoteKey: {{ include "mutualized-cnpg-databases.userVaultKey" (dict "db" $db "user" $user) }}
          property: port
    - conversionStrategy: None
      match:
        secretKey: dbname
        remoteRef:
          remoteKey: {{ include "mutualized-cnpg-databases.userVaultKey" (dict "db" $db "user" $user) }}
          property: dbname    
    - conversionStrategy: None
      match:
        secretKey: uri
        remoteRef:
          remoteKey: {{ include "mutualized-cnpg-databases.userVaultKey" (dict "db" $db "user" $user) }}
          property: uri
    - conversionStrategy: None
      match:
        secretKey: jdbc-uri
        remoteRef:
          remoteKey: {{ include "mutualized-cnpg-databases.userVaultKey" (dict "db" $db "user" $user) }}
          property: jdbc-uri
    - conversionStrategy: None
      match:
        secretKey: pgpass
        remoteRef:
          remoteKey: {{ include "mutualized-cnpg-databases.userVaultKey" (dict "db" $db "user" $user) }}
          property: pgpass
{{ end -}}
{{- end -}}
