---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: in-gateway-system

resources:
  - default.gateway.yaml
  - redirect-http-to-https.httproute.yaml
  - wildcard.chezmoi.sh.certificate.yaml
