---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: apps-secured-paperless
spec:
  cluster:
    name: postgres-apps-secured
  name: paperless
  owner: paperless
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-database-credentials
spec:
  dataFrom:
    - extract:
        key: lungmen.akn/paperless-ngx/database/postgresql
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    template:
      data:
        username: paperless
        password: "{{ .password }}"
