// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("truenas");

/**
 * The API key for authenticating with TrueNAS SCALE. Can also be set via the TRUENAS_API_KEY environment variable.
 */
export declare const apiKey: string | undefined;
Object.defineProperty(exports, "apiKey", {
	get() {
		return __config.get("apiKey");
	},
	enumerable: true,
});

/**
 * When true, the provider refuses DELETE requests at the client layer while still allowing GET/POST/PUT through. This is the apply-safe rail for the first production mutations: creates and updates work normally but no resource can be destroyed until the flag is cleared. Equivalent to per-resource <span pulumi-lang-nodejs="`deletionProtection`" pulumi-lang-dotnet="`DeletionProtection`" pulumi-lang-go="`deletionProtection`" pulumi-lang-python="`deletion_protection`" pulumi-lang-yaml="`deletionProtection`" pulumi-lang-java="`deletionProtection`" pulumi-lang-hcl="`deletion_protection`">`deletionProtection`</span> flags found in major Terraform providers, but enforced at the wire for every resource in the provider at once. Layer it with `read_only=true` for Phase 0 (read-only plan against prod) and drop <span pulumi-lang-nodejs="`readOnly`" pulumi-lang-dotnet="`ReadOnly`" pulumi-lang-go="`readOnly`" pulumi-lang-python="`read_only`" pulumi-lang-yaml="`readOnly`" pulumi-lang-java="`readOnly`" pulumi-lang-hcl="`read_only`">`readOnly`</span> + keep `destroy_protection=true` for Phase 1 (safe-apply: create and update only). Can also be set via the TRUENAS_DESTROY_PROTECTION environment variable. Defaults to false for backwards compatibility; the docs/guides/phased-rollout.md guide strongly recommends setting this to true for any HCL pointed at production.
 */
export declare const destroyProtection: boolean | undefined;
Object.defineProperty(exports, "destroyProtection", {
	get() {
		return __config.getObject<boolean>("destroyProtection");
	},
	enumerable: true,
});

/**
 * Skip TLS certificate verification. Only use this for self-signed test environments. Can also be set via the TRUENAS_INSECURE_SKIP_VERIFY environment variable.
 */
export declare const insecureSkipVerify: boolean | undefined;
Object.defineProperty(exports, "insecureSkipVerify", {
	get() {
		return __config.getObject<boolean>("insecureSkipVerify");
	},
	enumerable: true,
});

/**
 * When true, the provider refuses every mutating request (POST/PUT/DELETE) before it reaches the network. Intended for phased production rollout, point the provider at a real TrueNAS instance, run `terraform plan`, and be physically unable to mutate anything. Any resource that would be changed surfaces as a normal Terraform error rather than a partial write. Can also be set via the TRUENAS_READONLY environment variable. Defaults to false.
 */
export declare const readOnly: boolean | undefined;
Object.defineProperty(exports, "readOnly", {
	get() {
		return __config.getObject<boolean>("readOnly");
	},
	enumerable: true,
});

/**
 * Per-request HTTP timeout, parsed via time.ParseDuration (e.g. "60s", "2m", "5m"). Raise this for loaded production TrueNAS instances where pool scrub status, large dataset listings, or replication checks may take longer than the default 60s. Lower it for local/CI testing. Can also be set via the TRUENAS_REQUEST_TIMEOUT environment variable. Values of zero or less are ignored so this attribute can never disable the timeout.
 */
export declare const requestTimeout: string | undefined;
Object.defineProperty(exports, "requestTimeout", {
	get() {
		return __config.get("requestTimeout");
	},
	enumerable: true,
});

/**
 * The base URL of the TrueNAS SCALE instance (e.g., https://truenas.example.com). Can also be set via the TRUENAS_URL environment variable.
 */
export declare const url: string | undefined;
Object.defineProperty(exports, "url", {
	get() {
		return __config.get("url");
	},
	enumerable: true,
});
