apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - network-policy.default-hardened.yaml
  - network-policy.allow-forgejo-from-cilium-gateway.yaml
  - network-policy.allow-forgejo-from-tailscale.yaml
  - network-policy.allow-forgejo-ssh.yaml
  - network-policy.allow-forgejo-to-databases.yaml
  - network-policy.allow-forgejo-to-sso.yaml
  - network-policy.allow-forgejo-to-git-mirrors.yaml
