---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-forgejo-to-databases
  namespace: forgejo
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: forgejo
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: databases
          podSelector:
            matchLabels:
              cnpg.io/cluster: postgres-apps
              cnpg.io/podRole: instance
      ports:
        - port: 5432
          protocol: TCP
