---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-forgejo-ssh
  namespace: forgejo
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: forgejo
  ingress:
    - toPorts:
        - ports:
            - port: "22"
              protocol: TCP
          rules:
            l7:
              - protocol: ssh
  egress:
    - toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
