#!/usr/bin/env sh
# Copyright (C) 2024 Alexandre Nicolaie (xunleii@users.noreply.github.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------

# Until the layer4 proxy is implemented directly into the caddy server nor the
# caddyfile, we need to merge the JSON configuration with the Caddyfile.
cp /etc/caddy/*.Caddyfile /var/run/caddy/
if [ -f /etc/caddy/caddy.layer4.json ]; then
	/usr/bin/caddy adapt --config /etc/caddy/Caddyfile |
		jq --slurp '.[0] * .[1]' - /etc/caddy/caddy.layer4.json --compact-output >/var/run/caddy/caddy.json
else
	/usr/bin/caddy adapt --config /etc/caddy/Caddyfile >/var/run/caddy/caddy.json
fi

exec /usr/bin/caddy run --config /var/run/caddy/caddy.json
