---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smb-csi-driver-system

resources:
  - security/

  - namespace.yaml

helmCharts:
  - repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
    name: csi-driver-smb
    version: 1.20.1

    releaseName: csi-driver-smb
    namespace: smb-csi-driver-system

images:
  - name: registry.k8s.io/sig-storage/csi-node-driver-registrar
    newName: oci.chezmoi.sh/registry.k8s.io/sig-storage/csi-node-driver-registrar
  - name: registry.k8s.io/sig-storage/csi-provisioner
    newName: oci.chezmoi.sh/registry.k8s.io/sig-storage/csi-provisioner
  - name: registry.k8s.io/sig-storage/csi-resizer
    newName: oci.chezmoi.sh/registry.k8s.io/sig-storage/csi-resizer
  - name: registry.k8s.io/sig-storage/livenessprobe
    newName: oci.chezmoi.sh/registry.k8s.io/sig-storage/livenessprobe
  - name: registry.k8s.io/sig-storage/smbplugin
    newName: oci.chezmoi.sh/registry.k8s.io/sig-storage/smbplugin
