---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zot-registry

labels:
  - pairs:
      app.kubernetes.io/name: zot
      app.kubernetes.io/instance: zot
      app.kubernetes.io/component: application
    includeSelectors: true
    includeTemplates: true
  - pairs:
      # renovate: datasource=helm depName=zot registryUrl=http://zotregistry.dev/helm-charts
      app.kubernetes.io/version: 0.1.91
    includeTemplates: true

resources:
  - namespace.yaml
  - zot.pvc.yaml
  - zot.volumesnapshot.yaml
  - zot.httproute.yaml
  - security/

helmCharts:
  - name: zot
    repo: http://zotregistry.dev/helm-charts
    releaseName: zot
    version: 0.1.91
    valuesFile: zot.helmvalues/default.yaml
