---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zot-storage
  namespace: zot-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: openebs-zfspv
