---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: zot-storage-snapshot
  namespace: zot-registry
spec:
  volumeSnapshotClassName: openebs-zfspv-snap
  source:
    persistentVolumeClaimName: zot-storage
