---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale-system

resources:
  # Required secrets and ProxyClass for Tailscale Operator
  - restricted.proxyclass.yaml
  - operator-oauth.externalsecret.yaml

  # Additional configuration for remote cluster resource access
  - remote-cluster.proxyclass.yaml
  - ts-dns.dnsconfig.yaml

  # Security policies (NetworkPolicies, PodSecurityStandards, etc.)
  - security/

helmCharts:
  - repo: https://pkgs.tailscale.com/helmcharts
    name: tailscale-operator
    version: 1.98.3

    releaseName: tailscale-operator
    namespace: tailscale-system

    valuesInline:
      operatorConfig:
        hostname: amiya-akn
    valuesFile: tailscale.helmvalues/default.yaml
    additionalValuesFiles:
      - tailscale.helmvalues/hardened.yaml
    includeCRDs: true
