---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default.image-catalog.yaml
  - cnpg.cluster-policy.allow-to-kubernetes-api.yaml
  - cnpg.cluster-policy.allow-from-operator.yaml
