---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

generators:
  - |-
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: ksops
      annotations:
        config.kubernetes.io/function: |
          exec:
            path: ksops
    files:
      - ../argocd.github.secrets.yaml
      - ../argocd.sops.secrets.yaml
