---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin-database-atuin
spec:
  dataFrom:
    - extract:
        key: lungmen.akn/atuin/database/postgresql
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    name: atuin-database-atuin
    template:
      engineVersion: v2
      data:
        uri: "postgres://atuin:{{ .password }}@postgres-apps-rw.databases.svc.cluster.local:5432/atuin"
