---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atuin

labels:
  - pairs:
      app.kubernetes.io/name: atuin
      app.kubernetes.io/instance: atuin
    includeTemplates: true
    includeSelectors: true

resources:
  - atuin.deployment.yaml
  - atuin.httproute.yaml
  - atuin.ingress.yaml
  - atuin.postgresql-backup.yaml
  - atuin.postgresql-objectstore.yaml
  - atuin.postgresql.yaml
  - atuin.storage.yaml

  - security/

images:
  # renovate: datasource=docker depName=ghcr.io/atuinsh/atuin
  - name: ghcr.io/atuinsh/atuin
    newTag: 18.13.4@sha256:510269642461d9eb3f5808bf14894e1eabda43756c135cdc0b7c63285f4c3da3
