---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atuin

labels:
  - pairs:
      app.kubernetes.io/name: atuin
      app.kubernetes.io/instance: atuin
    includeTemplates: true
    includeSelectors: true

resources:
  - atuin.deployment.yaml
  - atuin.httproute.yaml
  - atuin.ingress.yaml
  - atuin.postgresql-backup.yaml
  - atuin.postgresql-objectstore.yaml
  - atuin.postgresql.yaml
  - atuin.storage.yaml

  - security/

images:
  # renovate: datasource=docker depName=ghcr.io/atuinsh/atuin
  - name: ghcr.io/atuinsh/atuin
    newTag: 18.14.0@sha256:278ff96a1ace3d69c7d2d7fe8d7a99e8045d18d37926767db95cfeacf70f0ef3
