---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: in-gateway-system-to-zot
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: in-gateway-system
  to:
    - group: ""
      kind: Service
      name: zot
