apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - network-policy.allow-intra-namespace.yaml
  - network-policy.allow-external-dns-to-kubernetes-api.yaml
  - network-policy.allow-external-dns-to-unifi.yaml
  - network-policy.allow-external-dns-to-bind.yaml
