apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  annotations:
    policy.networking.k8s.io/description: |
      Allows the external-dns-unifi and external-dns-bind controllers to access the Kubernetes API
      server to watch Services, Ingresses and Gateway API routes for DNS record management.
  name: allow-external-dns-to-kubernetes-api
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  egress:
    - toEntities:
        - kube-apiserver
