# Cert-Manager Helm values — default + hardened
crds:
  enabled: true

# Security context
securityContext:
  fsGroup: 34983
  runAsGroup: 34983
  runAsNonRoot: true
  runAsUser: 34983
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
